### ISSUE TITLE
Side panel not updated after calling microsoftTeams.settings.setSettings() with new settings

### ISSUE THREAD

**Issue by antonhedstrom** [OfficeDev/microsoft-teams-library-js#679] opened 2021-10-13 10:07 UTC
Hi!
 
We are developing an app to be used in Teams (both in a Tab and during a meeting). We have encountered an issues while using the app _in a meeting_. If we try to reconfigure the content (setting a new URL) the Side panel is not updated. If we close our app and reopen it, the new configuration kicks in though. 

### Current behavior 

1. User adds app to a meeting and configure it to use **Entity A** (resuling in https://www.example.com/aaaaa to be loaded in sidepanel).
2. After clicking "Save", URL shows up as expected in side panel.
3. User clicks the three dots in the side panel and choose "Settings" to reconfigure the URL.
4. User take some actions and pick **Entity B** instead (resulting in https://www.example.com/bbbbb)
5. User clicks Save but **Entity A** is still current url.
6. After closing the side panel and opening it again, **Entity B** is present as expected.

### Expected behavior

1. After reconfiguring the app, the new URL should be loaded right away (no re-opening required).

### Code being used
 
Here is the snippet we are using for our configuration path:

```
  useEffect(() => {
    microsoftTeams.initialize();
    // Save configuration changes
    microsoftTeams.settings.registerOnSaveHandler((saveEvent) => {
      const BASE_URL = `${window.location.protocol}//${window.location.host}`;
      microsoftTeams.settings.setSettings({
        contentUrl: `${BASE_URL}/${currentEntity.id}`,
        entityId: currentEntity.id,
        suggestedDisplayName: currentEntity.title,
        websiteUrl: `${BASE_URL}/${currentEntity.id}`,
      });

      saveEvent.notifySuccess();
    });
  });
```

### Setup

SDK version: 1.5.2
Teams Desktop (Mac): 1.4.00.22368

**Comment by linuws** [comment] 2021-12-01 09:35
> We tried to repro this issue and facing the same issue. Until and unless we close that SidePanel, the second entity/url is not getting rendered. We have raised a bug for this issue and concerned team is looking into it.

Thanks for looking into this! Is there some way that we can see the progress of this ticket? Or just get some hint when it will be prioritised? Just asking so we don't have to write another comment here to see if how the work progresses 😅

**Comment by Prasad-MSFT** [comment] 2021-12-20 12:09
@linuws -  Engineering team is looking into it. We will update you once it gets fully rolled out. Thanks!

**Comment by Prasad-MSFT** [comment] 2022-02-01 06:19
@linuws , @antonhedstrom - The issue is fixed now and has been rolled out publicly.

**Closed** 2022-02-16 06:22 UTC
Labels: teams-developer-support
