### ISSUE TITLE
executeDeepLink - how to allow user to join a team link?

### ISSUE THREAD

**Issue by maryha** [OfficeDev/microsoft-teams-library-js#300] opened 2019-12-31 18:19 UTC
I am trying to create an SPFX tab that acts as a dashboard to other related teams to the current one (these are teams that are created programmatically with the Graph API).  These are public teams, and we want to be able to just jump to the Team from the Dashboard tab if the user is a member or prompt to join if not.

If we just have a link to the team in the dashboard, it opens as in the web with the prompt to open in the web or teams - not a very friendly experience.  If we use executeDeepLink, it works great **if** the user is already a member -> the user is just sent to the team within Teams without having to go to the browser and back again.  However, if the user is **not** already a member, they are just sent to the first team in their list and nothing else happens.

Is there anyway from that SPFX tab to redirect the user within Teams and prompt them to join?

Thanks,
Mary

**Comment by ydogandjiev** [comment] 2020-01-01 21:52
@maryha, can you please try adding a `&groupId=<group_ID_of_the_team>` QSP to the deep link you are executing. That should allow Teams to show a prompt to the user via which they can request to join the team.

**Comment by maryha** [comment] 2020-01-02 14:07
Thanks for the suggestion, @ydogandjiev!  The "deep link" I am passing in already contains a group ID.  Here is an example of the link I am using:
https://teams.microsoft.com/l/team/19:cf47c6214559437eb13c16d91cf82660@thread.skype/conversations?groupId=bfb93f1d-51fd-4834-8481-0186972729c7&tenantId=ea49421b-4e9a-44ef-8009-446e845c7348

Is there a different format that I should use?

**Comment by stijnbrouwers** [comment] 2020-02-04 12:03
I am interested in the same question as @maryha , any news for this?

**Comment by andreatosato** [comment] 2020-02-04 14:14
#241 same here

**Comment by maryha** [comment] 2020-02-14 21:20
If you need a code sample, @ydogandjiev, let me know.  I have a basic test component where I paste a deep link into a text box and click a button to call executeDeepLink to see what happens.  Right now, if I am not a member, I just to go a default Team rather than prompted to join.  If I click the same deep link from a conversation in Posts, I am prompted to join. :-/

This is the one thing really preventing us from using this method.

**Comment by ydogandjiev** [comment] 2020-02-14 21:48
Hi @maryha, I investigated the issue on our end and it looks like it's caused by a gap in our deep link handling. The logic that validates the team membership and shows the join team dialog only runs when a deep link is coming in via a change in our app's top-level route but not when it's handled internally in response to an `executeDeepLink` call. We will look into making a fix to address the problem. In the meantime, please consider working around the issue by throwing the deep link out to a new browser window by calling:
```
window.open("<deep_link>", "_blank");
```

**Comment by maryha** [comment] 2020-02-18 13:33
Thanks,@ydogandjiev, for responding and letting us know the status!  Yes, I already knew about that workaround, but was hoping to not open a browser window just to have the user redirected back to Teams.  It would be great if you are able to figure out a fix.

**Comment by Subhasish-msft** [comment] 2020-03-19 11:28
Created a bug for this.

**Comment by maryha** [comment] 2020-05-11 13:23
@Subhasish-msft, a similar scenario has been coming up in another situation - linking someone to a channel in a team where they are not a member.  Teams just sends them to their default team.  Is there any way for me to get visibility into the bug and its progress in being fixed?

**Comment by agtenr** [comment] 2020-08-05 09:06
I am facing the same issue. For me this is quite a gap in the executeDeepLink functionality. Can you provide us with a status for this? 

Thanks!

**Comment by LudwigVanGysel** [comment] 2020-08-07 13:05
I have a similar issue, I'd like to offer the possibility to navigate a public team from within my personal teams application. Could this be given a higher priority? @Subhasish-msft, what is the status on this bug?

**Comment by petecuttriss** [comment] 2020-08-26 23:20
Hi everyone, we are also seeing the same issue.  Just checking to see if there has been any change to the status of this bug, thanks @Subhasish-msft

**Comment by DovOps** [comment] 2020-11-12 09:36
Has this been fixed, or is there any other status update on this - @Subhasish-msft  = any updates here would be very much appreciated.  The only way I've found to trigger the correct behavior right now is to put links to teams inside Wikis. That app seems to trigger the correct behavior when the links are clicked, and might be a sufficient workround for some, but I really need executeDeepLink to, well, execute the deep link properly.!

**Comment by petecuttriss** [comment] 2021-02-25 19:23
Hi everyone, I've checked in a couple of tenancies and this functionality now appears to be fixed.  I can click on a link that calls executeDeepLink and if I don't have access to the Team I now get the Join prompt.  Can anyone else confirm that this is now working for them?

**Comment by DovOps** [comment] 2021-03-01 15:55
Yes this works for me now! Thank you very much @petecuttriss

**Comment by ChetanSharma-msft** [comment] 2022-11-16 11:37
We are closing this issue for now, please feel free to reopen it, if required.

**Closed by ChetanSharma-msft** 2022-11-16 11:37 UTC
Labels: bug
