### ISSUE TITLE
Disabled by admin for locally side loaded app.

### ISSUE THREAD

**Issue by sylvesteraswin** [OfficeDev/microsoft-teams-library-js#1524] opened 2023-01-10 14:07 UTC
Hello Team,

I am getting the below message when I try to load my Tab meeting app and share the meeting with another person. I am not sure whats the error here.

here is my local manifest file

```json
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.14/MicrosoftTeams.schema.json",
  "manifestVersion": "1.14",
  "version": "1.0.0",
  "id": "ccf624cc-46af-575c-9e99-38d981781769",
  "packageName": "com.microsoft.teams.extension",
  "developer": {
    "name": "",
    "websiteUrl": "https://localhost:53000",
    "privacyUrl": "https://localhost:53000/privacy",
    "termsOfUseUrl": "https://localhost:53000/termsofuse"
  },
  "icons": {
    "color": "resources/color.png",
    "outline": "resources/outline.png"
  },
  "name": {
    "short": "App (Local)",
    "full": "App (Local)"
  },
  "description": {
    "short": "App",
    "full": "App longer descriptions should go here."
  },
  "accentColor": "#FFFFFF",
  "bots": [],
  "composeExtensions": [],
  "configurableTabs": [
    {
      "configurationUrl": "https://localhost:53000/config",
      "canUpdateConfiguration": true,
      "scopes": ["team", "groupchat"],
      "context": [
        "channelTab",
        "privateChatTab",
        "meetingChatTab",
        "meetingSidePanel",
        "callingSidePanel",
        "meetingDetailsTab",
        "meetingStage"
      ]
    }
  ],
  "staticTabs": [
    {
      "entityId": "index",
      "name": "Observability tab",
      "contentUrl": "https://localhost:53000",
      "websiteUrl": "https://localhost:53000",
      "scopes": ["personal", "team"]
    },
    {
      "entityId": "test",
      "name": "Workbook",
      "contentUrl": "https://localhost:53000/test",
      "websiteUrl": "https://localhost:53000/test",
      "scopes": ["personal", "team"]
    }
  ],
  "permissions": ["identity", "messageTeamMembers"],
  "validDomains": ["localhost"],
  "webApplicationInfo": {
    "id": "<aad-id>",
    "resource": "api://localhost:53000/<aad-id>"
  }
}

```

![Screenshot 2023-01-10 at 13 47 25](https://user-images.githubusercontent.com/555596/211571925-0b310dcb-2491-4ac1-9fd5-48e2552d9bd5.jpg)

**Comment by ChetanSharma-msft** [comment] 2023-01-10 16:15
Hello @sylvesteraswin - Thanks for reporting your issue.
We will investigate on your issue and let you know the updates.

**Comment by sayali-MSFT** [comment] 2023-01-11 06:40
@sylvesteraswin -It looks like the admin disallow sideloading of app for end-users.
Could you please Confirm, it is happened only for single user or with all users?
Could you please check the [Admin Center](https://admin.teams.microsoft.com/dashboard) below setting is on or off?
![custom-app-orgwide-setting](https://user-images.githubusercontent.com/93527375/211733686-2b5f9f53-22f0-4116-9862-b80748b238ac.png)

Reference Document-https://learn.microsoft.com/en-us/microsoftteams/teams-custom-app-policies-and-settings#understand-sideloading-of-custom-apps

**Comment by sylvesteraswin** [comment] 2023-01-11 09:22
@sayali-MSFT Thanks for the quick response. 

Unfortunately I do not have access to `admin.microsoft.com`. I am not sure if it's an issue with side loading because I am able to side load the custom app for a single user. Here is how to reproduce this issue

1. Start a new meeting with only me in it.
2. Side load my custom app which is running in `localhost`.
3. Side panel opens up with the opens to share to meeting stage.
4. Click on a link in the side panel, the app gets shared to meeting stage and my localhost application is loaded.

At this point, I know my app is working as intended with a single user in the meeting.

But, when I add another **user** to the meeting while the app is running in meeting stage, the new user gets the above error message I have mentioned.

> Note: I do not see any error message in the console of the new user also

Hope this brings more clarity to this issue.

**Comment by sylvesteraswin** [comment] 2023-01-11 14:49
I have been trying to debug the app today, I can see the below error message in my second users console when the main user started to share a meeting stage

```js
["CID[main] ExtensibleAppContainer: getAppDefinition failed for: 895b37c3-bbe7-4dce-809f-ad9cb7fbfa89 Error Details: Get AppDefinition failed - AppsHelper - NotPresent. TeamsCallId- 5"]
```

`895b37c3-bbe7-4dce-809f-ad9cb7fbfa89` seems to be App id which is created when I side loaded the application into teams, but as per the `manifest.json` which I uploaded to teams, the `id` I provided is different.

**Comment by sayali-MSFT** [comment] 2023-01-12 06:14
@sylvesteraswin -Thank you for detailed information, we are trying it from our end and get back to you.

**Comment by sylvesteraswin** [comment] 2023-01-12 11:17
Here is a quick way to reproduce this issue:

1. Git clone git@github.com:sylvesteraswin/sample-sso-tab-reproduce.git
2. Open the repo in VSCode with [Teams FX Plugin](https://github.com/OfficeDev/TeamsFx/tree/main/packages/vscode-extension). This should help to open the Edge debugger automatically.
3. Run Edge Debug locally.

Now that you have the app running locally. Follow the below steps to have more than 1 user added to a meeting:
1. Start a new meeting with only me in it.
1. Side load my custom app which is running in localhost.
1. Side panel opens up with the opens to share to meeting stage.
1. Click on a link in the side panel, the app gets shared to meeting stage and my localhost application is loaded.

And even with this simple App I get the same error.

Here is a [video](https://microsofteur-my.sharepoint.com/:v:/g/personal/sstanley_microsoft_com/EXWglUN24CFKl_-YKfruvvABcYgouAwFagEiHZF6Pxa7nQ?e=Keciyz) of the above flow.

**Comment by sayali-MSFT** [comment] 2023-01-13 13:23
@sylvesteraswin -Thanks for the repro steps, we are trying it from our end and if it is repro, we will raise bug accordingly and let you know the update. thanks

**Comment by sayali-MSFT** [comment] 2023-01-18 10:01
@sylvesteraswin - We are able to repro that issue, we are checking it internally if it's bug or byDesign behaviour for web client and let you know once we get any updates. 
![image](https://user-images.githubusercontent.com/93527375/213141649-e7216544-de59-40e0-97e3-d0168b46d1cb.png)

**Comment by sylvesteraswin** [comment] 2023-01-18 15:59
@sayali-MSFT Thanks for confirming, It looks to me a bug since it was working a couple of weeks ago, and this the current recommended workflow to develop apps inside teams.

**Comment by ChetanSharma-msft** [comment] 2023-01-24 13:26
Hello @sylvesteraswin - 
Hope you are doing well!!

We have raised an internal bug and assigned to the engineering team.
We will let you know once we get any input from engineering team.

**Comment by xerosanyam** [comment] 2023-01-27 07:10
@ChetanSharma-msft, @sayali-MSFT We are also facing the same issue.
For us, if the attendee if the attendee joins from Mac or browser - they are seeing this issue, else its working.

**Comment by sayali-MSFT** [comment] 2023-01-29 12:20
@xerosanyam @sylvesteraswin -Sorry for delay in response!!
We are actively checking the status of bug with engineering team and let you know the updates, if we have any.

**Comment by julianbrasolin** [comment] 2023-02-03 15:02
We are facing this issue too, a couple of weeks ago everything was working fine. We are getting the same popup error with different error message, instead of "your admin has disabled the app that is being shared" we get:
![imagen](https://user-images.githubusercontent.com/99664120/216635944-f1614c54-1bf9-40a8-9444-6c26a8f36cc0.png)

we can not connect either from browser or teams app, only the presenter can see the content being shared

**Comment by freistli** [comment] 2023-02-06 02:12
Hi @sayali-MSFT I hit the same issue when working on Teams Live Share SDK scenario which uses the same Teams Meeting extension method to share stage. One month ago, the same Teams LiveShare SDK package worked very well.

Here is the similar error reported in my Teams:

![image](https://user-images.githubusercontent.com/8623897/216866517-5fca3321-9887-421e-bc17-8b1764a423d7.png)

![image](https://user-images.githubusercontent.com/8623897/216866789-95d66ae6-ef18-411b-a0d2-2a2e5e37d293.png)


getAppDefinition failed for: 06221320-32e2-4a77-b9c9-4db86e6cb9fe Error Details: Get AppDefinition failed - AppsHelper - NotPresent. TeamsCallId- 1

Please kindly let us know and accelerate the fix progress with Teams team, as it is a **huge** block for customers to use MS LiveShare SDK (the new feature released in Oct, 2022) or all other teams meeting extensions to share stage in meeting.

Thanks in advance.

**Comment by ChetanSharma-msft** [comment] 2023-02-06 09:28
Hello Everyone,
Hope you are doing well!!

We have raised a bug for it and informed engineering team.
We will let you know once we get any update from engineering team.

**Comment by gunner13** [comment] 2023-02-08 19:38
From @freistli 
> If App was released in org A but not in org B, when users of A shared stage, users of B will see this error

This's exactly what we're facing too.

**Comment by sayali-MSFT** [comment] 2023-02-09 04:07
@gunner13 -We are actively checking the status of bug with engineering team and let you know the updates, if we have any.
Thanks!!

**Comment by ChetanSharma-msft** [comment] 2023-02-09 16:07
Hello @Everyone,
This bug has been fixed internally and will take some time to roll out publicly.
Currently we don't have exact ETA to share but we will let you know the updates.

**Comment by gunner13** [comment] 2023-02-18 19:37
> Hello @everyone, This bug has been fixed internally and will take some time to roll out publicly. Currently we don't have exact ETA to share but we will let you know the updates.
> 
> As a Workaround for now, you can try installing the app in personal scope for attendee and it will mitigate the issue.

Thank you for the update. However, can you please be more detailed on the suggested workaround? 

If your suggestion was about adding a static tab with the "personal" scope and then ask the attendee to install it as a personal tab to his Teams before joining the meeting, it didn't work for me. I saw the same error message when trying this. 

And if it was about asking the attendee to install the app to the same meeting, it's impossible as the attendee is from the other organization so he won't be able to add the app to the meeting.

**Comment by gunner13** [comment] 2023-02-26 15:32
Hi @ChetanSharma-msft, do you have any updates on this one?

**Comment by sayali-MSFT** [comment] 2023-02-27 07:13
@gunner13 - We are actively checking the status of bug with engineering team and let you know the updates, if we have any.
Thanks!!

**Comment by sayali-MSFT** [comment] 2023-02-27 08:17
@gunner13  @sylvesteraswin -Issue is resolved. Could you please check it once and confirm the same?
Microsoft Teams Version 1.6.00.5081 (64-bit).
![image](https://user-images.githubusercontent.com/93527375/221509163-96b9d951-d38d-480a-b628-e119cbe9eb04.png)

**Comment by gunner13** [comment] 2023-03-02 15:02
Seems like the version 1.6.00.5081 hasn't been published yet. I tried to update my MS Teams today, but it said I had the latest version already, and it was only 1.6.00.4472. 
![image](https://user-images.githubusercontent.com/10414256/222465618-45669a72-7ce2-430f-b31b-ff06004f62b2.png)

Do you have any ideas when that version will be able for everyone?

**Comment by GyllionElderen** [comment] 2023-03-03 12:45
> @gunner13 @sylvesteraswin -Issue is resolved. Could you please check it once and confirm the same? Microsoft Teams Version 1.6.00.5081 (64-bit). ![image](https://user-images.githubusercontent.com/93527375/221509163-96b9d951-d38d-480a-b628-e119cbe9eb04.png)

I have checked this in the Developer Preview version (on web) and it works.

**Comment by sayali-MSFT** [comment] 2023-03-03 17:32
@gunner13 @GyllionElderen -We will check it internally and get back to you. meanwhile could you please check it once updates?
![update](https://user-images.githubusercontent.com/93527375/222787256-f44f316b-7654-4ad4-b08d-58d3238e3825.png)

**Comment by gunner13** [comment] 2023-03-05 10:14
I had tried to click on that "Check for updates" menu, but it was still 1.6.00.4472 after that. 
I also tried to download the installer from this site https://www.microsoft.com/en-us/microsoft-teams/download-app#desktopAppDownloadregion and reinstalled the app, the version then became 1.6.00.1xxx, older than what I had. So I clicked on "Check for updates" one more time, and still got 1.6.00.4472 at the end of the day.

**Comment by gunner13** [comment] 2023-03-08 06:54
I found this link where I was able to download a newer version of MS Teams https://staticsint.teams.cdn.office.net/production-windows-x64/1.6.00.6680/Teams_windows_x64.exe, my MS Teams is 1.6.00.6680 (64-bit) now, but the issue is still there. 

![image](https://user-images.githubusercontent.com/10414256/223639747-5bb948ce-9541-441c-8520-84b3c910ebc0.png)
![6](https://user-images.githubusercontent.com/10414256/223639680-9b1e2668-0512-4bc1-aeb2-1c930b7a03b5.png)

Note that the issue happens to the external user only, the flow is: 
- User A from the tenant A creates the meeting and adds the app to the meeting. 
- User B from the tenant B joins the meeting
- User A click on the "Share" button (a custom button using the microsoftTeams.meeting.shareAppContentToStage function)
- User B sees the error message as seen in the screenshot #2 above.

Both have the 1.6.00.6680

**Comment by sayali-MSFT** [comment] 2023-03-08 09:46
@gunner13 -We are reopening the bug as able to reproduce as above scenario for external user.
We will let you know once we get any update.

> Here is a quick way to reproduce this issue:
> 
> 1. Git clone this [repo](https://github.com/sylvesteraswin/sample-sso-tab-reproduce).
> 2. Open the repo in VSCode with [Teams FX Plugin](https://github.com/OfficeDev/TeamsFx/tree/main/packages/vscode-extension). This should help to open the Edge debugger automatically.
> 3. Run Edge Debug locally.
> 
> Now that you have the app running locally. Follow the below steps to have more than 1 user added to a meeting:
> 
> 1. Start a new meeting with only you in it.
> 2. Side load my custom app which is running in localhost.
> 3. Side panel opens up with the opens to share to meeting stage.
> 4. Click on a link in the side panel, the app gets shared to meeting stage and my localhost application is loaded.
> 5. Try adding yourself or another person in this meeting while the meeting stage is open.
> 
> And even with this simple App I get the same error.
> 
> Here is a [video](https://microsofteur-my.sharepoint.com/:v:/g/personal/sstanley_microsoft_com/EXWglUN24CFKl_-YKfruvvABcYgouAwFagEiHZF6Pxa7nQ?e=Keciyz) of the above flow.

Previously we have checked the above scenario, for this scenario it is working fine now.

**Comment by gunner13** [comment] 2023-03-09 11:00
> @gunner13 -We are reopening the bug as able to reproduce as above scenario for external user. We will let you know once we get any update.
> 
> > Here is a quick way to reproduce this issue:
> > 
> > 1. Git clone this [repo](https://github.com/sylvesteraswin/sample-sso-tab-reproduce).
> > 2. Open the repo in VSCode with [Teams FX Plugin](https://github.com/OfficeDev/TeamsFx/tree/main/packages/vscode-extension). This should help to open the Edge debugger automatically.
> > 3. Run Edge Debug locally.
> > 
> > Now that you have the app running locally. Follow the below steps to have more than 1 user added to a meeting:
> > 
> > 1. Start a new meeting with only you in it.
> > 2. Side load my custom app which is running in localhost.
> > 3. Side panel opens up with the opens to share to meeting stage.
> > 4. Click on a link in the side panel, the app gets shared to meeting stage and my localhost application is loaded.
> > 5. Try adding yourself or another person in this meeting while the meeting stage is open.
> > 
> > And even with this simple App I get the same error.
> > Here is a [video](https://microsofteur-my.sharepoint.com/:v:/g/personal/sstanley_microsoft_com/EXWglUN24CFKl_-YKfruvvABcYgouAwFagEiHZF6Pxa7nQ?e=Keciyz) of the above flow.
> 
> Previously we have checked the above scenario, for this scenario it is working fine now.

Should we create another issue for my scenario, @sayali-MSFT ? Seems like this and the original posted by @sylvesteraswin  were mixed up. I and @freistli reported the exact same issue about one month ago and you've confirmed a few times that it had been fixed

**Comment by gunner13** [comment] 2023-03-20 04:24
@sayali-MSFT , thanks for that, will we have any feedbacks on that soon?

**Comment by sayali-MSFT** [comment] 2023-03-20 04:53
@gunner13 -Got the reply from engineering team.
" This is by design. Cross-tenant is not supposed to work."

**Comment by gunner13** [comment] 2023-03-20 07:12
> @gunner13 -Got the reply from engineering team. " This is by design. Cross-tenant is not supposed to work."

I believed it was working when I tested with one of your examples around two months ago. Do you think we have any workarounds for this?

**Comment by sayali-MSFT** [comment] 2023-03-20 07:34
@gunner13 -We will check it internally, is there any workaround for this or not and get back to you once we get any update.

**Comment by gunner13** [comment] 2023-03-20 17:25
@sayali-MSFT , I tried one more thing today, I invited the user B to join a team in the tenant A today following this guide https://support.microsoft.com/en-us/office/add-guests-to-a-team-in-teams-fccb4fa6-f864-4508-bdde-256e7384a14f?ui=en-us&rs=en-us&ad=us#ID0EBD=Desktop . I faced the same issue, I thought adding the guest as an external user should work, as it is not cross-tenant now.

FYI, below is the console log message from my chrome
![image](https://user-images.githubusercontent.com/10414256/226413061-fc4a03b2-10f1-4dd1-814f-88c7add41035.png)

Is this also a limitation by design, or I'm doing something wrong?

**Comment by ChetanSharma-msft** [comment] 2023-05-11 14:04
I apologize for delay in response.
We will look into it and let you know the updates.

Thanks!!

**Comment by sayali-MSFT** [comment] 2023-05-12 06:29
@gunner13 -Got the reply through engineering team that,"Currently it is not possible, User B doesn't have access to the file. They can't load a file they don't have access to."

For investigation purpose Could you please provide the below details-

1. value of the flag: retryForAttendeeGetAppDefinitionFailure
2. are you seeing the error in the browser console
3. Retry App definition for attendee
4. What is the meaning of adding guest as external user?  Want to confirm if its anon user or external user added as guest?
5. Repro video of the issue.
6. Response from chatentitlements call in the network tab
7. screenshot of the error.  there is only console error log screen.
8. Also, is it possible to report a BRB logs for the issue. That will help get more details

**Closed as completed** 2023-05-22 19:01 UTC
Labels: bug, teams-developer-support, needs author feedback, status: no recent activity
