### ISSUE TITLE
User.Read permission not requested in consent prompt for non-admin user

### ISSUE THREAD

**Issue by rabindra-harlalka** [OfficeDev/microsoft-teams-library-js#698] opened 2021-11-10 16:07 UTC
I am following the https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-personal-sso-quickstart sample app.

I have an app registration created in Azure AD with both Access tokens (implicit flows) and ID tokens (implicit and hybrid flows) checked in the authentication page and the `https://graph.microsoft.com/User.Read` Graph permission added to API permissions, including others like openid, profile, email, etc.

The above app registration is meant for a Teams tab app, running in different tenant than the tenant where the app registration lives (multitenant has been checked in the account types), which calls the `microsoftTeams.authentication.getAuthToken()` API. For a user who hasn't consented before, this triggers user consent flow.

![image](https://user-images.githubusercontent.com/8935231/141142296-ce830837-525a-4030-9fa5-282850524e56.png)

![image](https://user-images.githubusercontent.com/8935231/141142522-8335ff39-fa59-4403-8877-2fbb888004bd.png)

### The issue
The above example is for a user who is the tenant admin. For a non-admin user, the consent doesn't include "Sign you in and read your profile" but just "View your basic profile".

![image](https://user-images.githubusercontent.com/8935231/141145851-2fa82243-f579-4f72-bc31-5cef00967c7b.png)

Even if an explicit authentication/consent request is triggered using `https://login.microsoftonline.com/common/oauth2/authorize?client_id={client_id}&response_type=id_token token&response_mode=fragment&resource=https://graph.microsoft.com&redirect_uri=https://{host}/Auth/End&nonce=7318ea1b-3239-4fb1-a99f-2b5f1c5c979c&state=c7f8354c-8f3a-4628-a611-9a230b0bf6bc&login_hint={user}`, the returned access_token doesn't have the User.Read scope. It's the same even if I explicitly add the `scope=openid email profile User.Read offline_access` query parameter to the request.

I couldn't find any documentation which can explain this behavior. Is there anything special about User.Read permission?

**Comment by Nivedipa-MSFT** [comment] 2021-11-11 07:00
@rabindra-harlalka - We are looking into this issue.We will update you.

**Comment by Nivedipa-MSFT** [comment] 2021-11-19 07:12
@rabindra-harlalka - Could you please go through below doc which explains scenarios in which users see consent prompts.
https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/application-sign-in-unexpected-user-consent-prompt#scenarios-in-which-users-see-consent-prompts

**Comment by Prasad-MSFT** [comment] 2021-11-22 10:07
@rabindra-harlalka , Is your issue resolved with above suggestion or still looking for any help?

**Comment by rabindra-harlalka** [comment] 2021-11-22 11:06
@Prasad-MSFT , I am yet to go through the suggestion. I will get back once I have tried it, most likely next week.

**Comment by v-chetsh** [comment] 2021-12-11 08:35
@rabindra-harlalka - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by rabindra-harlalka** [comment] 2021-12-13 16:17
@v-chetsh , @Prasad-MSFT , @Nivedipa-MSFT ,
I don't the given [link ](https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/application-sign-in-unexpected-user-consent-prompt#scenarios-in-which-users-see-consent-prompts) talks about the scenario I am describing. In my case, the user does get the user consent prompt but without the Graph permission.

I have already followed the information given in the page
https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso#get-an-access-token-with-graph-permissions, which is linked from here: https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso#1-create-your-aad-application.
I do the same as suggested here in my application but as I have described in the original issue it only works for the admin user and not for others.

**Comment by Nivedipa-MSFT** [comment] 2021-12-20 13:49
@rabindra-harlalka - You can reach out to [Azure Active Directory Developer Support Team](https://blogs.aaddevsup.xyz/about-us/)

**Comment by Nivedipa-MSFT** [comment] 2021-12-31 13:31
We have tried the https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-personal-sso-quickstart sample 
Following results we get

1. **Same Tenant Admin** we have not get any consent. 

2. **Same Tenant Non Admin User** 

![same tenant user_LI](https://user-images.githubusercontent.com/92150070/147825207-b61ca7de-de31-43b8-a7c8-13fd8893b18e.jpg)

3. **Different Tenant Admin**

![image](https://user-images.githubusercontent.com/92150070/147825280-8116c625-adcc-4053-a51d-a4063bf155a2.png)

4. **Different Tenant Non-Admin user**

![image](https://user-images.githubusercontent.com/92150070/147825469-48f89221-011a-48ca-9bf7-f6e2e9fe6eae.png)

**Looks like this is by design behaviour.**

For further query you can reach out to [Active Directory Developer Support Team](https://blogs.aaddevsup.xyz/about-us/)

**Comment by v-chetsh** [comment] 2022-01-04 07:40
We are closing this issue for now, Please feel free to reopen it, if required.

**Closed by v-chetsh** 2022-01-04 07:40 UTC
Labels: teams-developer-support, needs author feedback
