### ISSUE TITLE
iOS M365 - Something went wrong [2400] error with webApplicationInfo section

### ISSUE THREAD

**Issue by onmomo** [OfficeDev/microsoft-teams-library-js#2217] opened 2024-03-13 16:12 UTC
We learned that iOS M365 app is not able to load a teams app with `webApplicationInfo` section correctly.

![IMG_0806](https://github.com/OfficeDev/microsoft-teams-library-js/assets/1713109/d86980de-b749-42e6-a25d-c94586da72a6)

Once we removed the complete section, the error was gone
```
"webApplicationInfo": {
   "id": "{{APPLICATION_ID}}",
   "resource": "api://{{PUBLIC_HOSTNAME}}/{{APPLICATION_ID}}"
}
```
Just changing the resource string to something like `"resource": "api://{{APPLICATION_ID}}"` did not resolve it in the end.

@vikramtha could you escalate this again internally, please?

cross post of (don't know where to report mobile app bugs actually)
* https://learn.microsoft.com/en-us/answers/questions/1614150/ms-teams-integrated-app-on-m365-mobile-(ios)-somet?comment=question

**Comment by TrevorJoelHarris** [comment] 2024-03-13 20:04
Hi @onmomo, just wanted to check. Is this something you're running into on the iOS client of Teams specifically, or is it somewhere else?

**Comment by onmomo** [comment] 2024-03-13 21:01
> Hi @onmomo, just wanted to check. Is this something you're running into on the iOS client of Teams specifically, or is it somewhere else?

Hi @TrevorJoelHarris, this occurs if our teams app is opened inside the iOS M365 native app with said manifest.json version 1.13

**Comment by ChetanSharma-msft** [comment] 2024-03-15 07:28
Hello @onmomo - Could you please confirm whether you have implemented any SSO in your application?
Could you please share the exact repro steps including Manifest and code snippets so that we can try to repro it?

**Comment by onmomo** [comment] 2024-03-15 12:55
@ChetanSharma-msft thanks for coming back to me. We implemented external SSO flow but this does not matter here, since the error occurs even before our app is even requested.

This is the most basic manifest.json I was able to come up with. It allows to easily reproduce the error. Please also find the attached packaged app to reproduce it quickly. 
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/teams/v1.13/MicrosoftTeams.schema.json",
  "manifestVersion": "1.13",
  "id": "{{APPLICATION_ID}}",
  "version": "{{VERSION}}",
  "packageName": "{{PACKAGE_NAME}}",
  "developer": {
    "name": "acme corp",
    "websiteUrl": "https://www.acme.ai",
    "privacyUrl": "https://www.acme.ai/privacy-policy",
    "termsOfUseUrl": "https://www.acme.ai/terms-of-use",
    "mpnId": "6187884"
  },
  "name": {
    "short": "{{NAME_SHORT}}",
    "full": "{{NAME_FULL}}"
  },
  "description": {
    "short": "short",
    "full": "full"
  },
  "icons": {
    "outline": "icon_rest_32.png",
    "color": "icon_color_192.png"
  },
  "accentColor": "#5135C1",
  "publisherDocsUrl": "https://acme.com/docs",
  "staticTabs": [
    {
      "entityId": "helpTab",
      "name": "ACME CORP",
      "contentUrl": "https://en.wikipedia.org/wiki/Acme_Corporation",
      "scopes": [
        "personal"
      ]
    }
  ],
  "webApplicationInfo": {
    "id": "{{APPLICATION_ID}}",
    "resource": "api://{{PUBLIC_HOSTNAME}}/{{APPLICATION_ID}}"
  }
}

```

Once the `webApplicationInfo` section is removed, the error won't be shown again for m365 iOS app.
[error-2400.zip](https://github.com/OfficeDev/microsoft-teams-library-js/files/14615689/error-2400.zip)

**Comment by sakov-ms** [comment] 2024-03-19 23:01
Hi @onmomo, thanks for the detailed repro! We are checking this issue and will provide updates soon.

**Comment by AE-MS** [comment] 2024-04-10 23:14
@onmomo I just want to let you know that I'm able to reproduce the problem with the sample app you provided (Thanks!) and I'm working with the M365 app team to make traction on the cause. We haven't forgotten about you!

**Comment by AE-MS** [comment] 2024-04-17 16:20
Thanks for your patience while I investigated this issue. The M365 app team is located on the other side of the world than I am so collaboration has taken a little longer than usual due to time zone differences.

I don't have a clear fix for the issue yet, but we've been able to debug that the problem exhibited by the sample app you provided is because of how our system tries to prefetch authentication tokens for apps as a performance improvement for when they actually later request the auth token. In your sample app, one problem is that the `contentUrl` doesn't match the domain in the `resource` provided and that seems to be the cause of the issue (apps aren't allowed to request tokens for resources where the domains don't match).

I am still getting to the bottom of this and will report back when I have more details. Thanks!

**Comment by AE-MS** [comment] 2024-04-19 17:52
@onmomo Related to what I wrote above, the issue that repros with the sample app you provided is because apps are only allowed to request tokens for domains that their app lives on. E.g., if the URL of the page requesting a token is `example.com`, the only allowed resource for which it can request a token also has to be on `example.com`. In the example you provided it's a little different because the "app" (Wikipedia) isn't intentionally requesting a token, but is instead triggering our automatic prefetch logic (we try to retrieve the token on initialization so that it's ready if and when the app does ask for it).

Obviously we have a bug to fix because our prefetch action shouldn't ever trigger UI, even in the case of an error, since it will be confusing to the user and/or developer since it won't be clear what caused it.

However, given the sample manifest you provided, the app could never actually work like that because the content URL domain (`wikipedia.org`) doesn't match the resource domain (`starmind-christian.eu.ngrok.io`). In the situation you have actually been trying to enable (i.e. not the sample you provided), do the domains in question match?

**Comment by onmomo** [comment] 2024-06-04 14:54
@AE-MS thanks for looking into this. Note, our app does actually not request any tokens or implements SSO with Entra Id . As you suggested, I think the app should not forward this "error" to the user and the implementation should take into account that there might be apps that only require this for sending activity notifications to the user via backend service and not for SSO purposes.

In the real file we have
```
"id": "{{APPLICATION_ID}}",
"webApplicationInfo": {
    "id": "{{APPLICATION_ID}}",
    "resource": "api://{{PUBLIC_HOSTNAME}}/{{APPLICATION_ID}}"
  },
"validDomains": [
    "{{PUBLIC_HOSTNAME}}"
  ]
```
We added this section to allow sending notifications to the user via GraphAPI. Without this section we get
```
Application with AAD App Id '{{APPLICATION_ID}}' is not authorized to generate custom text notifications about '/v1.0/users/73ba1114-08f1-4d3a-8a88-0c2b1ea12345/teamwork/Microsoft.Teams.GraphSvc.sendActivityNotification' to the recipient.
```

I checked again the docs, and I found the NOTE
![Screenshot 2024-06-04 at 16 22 26](https://github.com/OfficeDev/microsoft-teams-library-js/assets/1713109/01d2336a-b60c-49f2-9da7-dcf411a458d4)

Changing this now to an **invalid** url as suggested, seems to workaround the reported issue. I can no longer reproduce this issue and our GraphAPI sendActivityNotification request still works. It is just a bit dirty IMHO. :-)

```
"webApplicationInfo": {
    "id": "{{APPLICATION_ID}}",
    "resource": "api://sso-not-implemented"
  }
```

**Comment by onmomo** [comment] 2024-06-06 16:19
> Thanks for the extra details. In response to these details, I've been looking into why the documentation has that seemingly strange note about requiring a dummy string (it's apparently been there for a long time).
> 
> Can you help me better understand your scenario so I can ensure we improve the process, docs, or code to better and more clearly support it? When you say that you are sending activity notifications to the user, do you mean that you're using the MS Graph API endpoint like [this one](https://learn.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-1.0&tabs=http)? If so, how are you authenticating to the API (e.g., what token are you putting in the Bearer header when making the REST call)? Is it a token you're getting by calling [authentication.getAuthToken](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.authentication?view=msteams-client-js-1.13.1#@microsoft-teams-js-microsoftteams-authentication-getauthtoken) or something different?
> 
> Thanks!
@AE-MS 
Yes, we are using MS Graph API (POST https://graph.microsoft.com/v1.0/users/${graphUserId}/teamwork/sendActivityNotification). The token used is fetched via "grant_type: 'client_credentials'" from `https://login.microsoftonline.com/${tenantId}/oauth2/v2.0/token`. The provided credentials are configured for the registered app on Azure.

It looks like the dummy domains does the trick, tough. The something went wrong [2400] error is resolved for the M365 iOS app and we can still send activity notifications for the user.

**Comment by onmomo** [comment] 2024-06-21 07:48
@ChetanSharma-msft @AE-MS  I already provided the feedback. What is the status on this issue, when will this fix you mentioned be implemented for the M365 iOS app?

**Comment by sakov-ms** [comment] 2024-06-21 20:25
Hello @onmomo, thank you so much for patience! We have fixed this issue, and it is available in M365 iOS app in versions 2.85.* and above. Please load your app in the latest M365 iOS app and let us know if you face any issues.

**Comment by onmomo** [comment] 2024-06-24 08:48
@sakov-ms I just tested with version 2.86.1 and the issue is still there if I don't remove the workaround documented above with the dummy url in the manifest.
![IMG_35688E504856-1](https://github.com/OfficeDev/microsoft-teams-library-js/assets/1713109/2b61eb82-d856-44e1-8d83-75d08b2d59e4)

**Comment by sakov-ms** [comment] 2024-06-24 18:15
Okay. Thanks for getting back on this. We are checking this and will get back with an update.

**Comment by sakov-ms** [comment] 2024-07-02 20:53
Hello @onmomo, sorry for the delay but could you share the logs from this error? It will help us debug faster. Thanks!

**Comment by maglims** [comment] 2024-07-08 22:14
Hi @onmomo , thanks for your patience. While we are still doing some internal checks here, could you help us to understand a few more questions?

1. In your initial poster, is our understanding correct that there was no activity notification involved? i,e, when you try to load the test app in M365 iOS app, it gave the error "Something went wrong. [2400]". It has no SSO auth or activity notification involved and it is just a simple app loading.

2. If #1 is true, are you still seeing the exact same error today "Something went wrong. [2400]", after you update to the newer M365 iOS app version?

3. Could you also help us to understand how activity notification works in your app? Is it be triggered after the app loading finishes, it is something else? 

Is that right assumption that you also see the error "Something went wrong. [2400]" while you are in the activity notification  flow?

Looking forward to hearing from you!

**Comment by maglims** [comment] 2024-07-16 17:08
@onmomo , if the issue is still going on, could you please provide the information in previous message to help us understand further? Thanks.

**Comment by sakov-ms** [comment] 2024-08-06 20:18
Hi @onmomo, could you please provide the information requested by @maglims in the previous comments? Thanks for your help!

**Comment by sakov-ms** [comment] 2024-08-13 20:39
Closing this issue for now. We will re-open it whenever customer responds.

**Closed** 2024-08-13 20:40 UTC
Labels: teams-developer-support, needs attention, v2

**Comment by onmomo** [comment] 2024-08-19 07:57
@maglims @sakov-ms 
As long as I have the following workaround in the manifest.json in place, the issue no longer persists

```
"webApplicationInfo": {
    "id": "${{APPLICATION_ID}}",
    "resource": "api://sso-not-implemented"
  }
``` 

This work for us, since we don't plan to implement SSO support via EntraId.
