### ISSUE TITLE
Tab not reload when it is changed to another tab then gets back, in Microsoft Teams on Mobile platform.

### ISSUE THREAD

**Issue by Tower450** [OfficeDev/microsoft-teams-library-js#1448] opened 2022-11-10 16:44 UTC
Hi,

i am currently developing a team app application and i have an issue with tab refreshing. When i signin/out from the application in browser everything is fine but on mobile i am obligated to refresh the tab when i change tab to see my authentification status applied. I found the exact same issue reported on learn.microsoft.com. Is there a way to make it refresh without forcing the user to reload it manually.

[https://learn.microsoft.com/en-us/answers/questions/884107/tab-not-reload-when-it-is-changed-to-another-tab-a.html](https://learn.microsoft.com/en-us/answers/questions/884107/tab-not-reload-when-it-is-changed-to-another-tab-a.html)

Kind regards

**Comment by Tower450** [comment] 2022-11-14 14:38
I want to refresh the tab when i change tab on mobile simple as that, i am just looking for the same behaviour that happens in Teams on Desktop and on Browser so all chromium based version. Is it possible? Or, can you indicate where the transpiling for mobile is done do i can investigate in the code where i could make tab refreshing.

**Comment by Nivedipa-MSFT** [comment] 2022-11-16 11:29
@Tower450 - We are checking this with engineering team. We will update you.

**Comment by Nivedipa-MSFT** [comment] 2022-11-18 07:21
@Tower450 - We have checked with engineering team and got an update that it is by design behaviour. If an app has multiple tabs in mobile, we keep those pages in memory. This helps in smooth navigation between the tabs and improves performance. And we don't reload tabs if user switches tab when the app has multiple tabs.
Could you please help by suggesting this feature on - [Microsoft Teams · Community](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472)

**Comment by Tower450** [comment] 2022-11-18 14:27
@Nivedipa-MSFT Thanks for the quick reply it is really appreciatee. I was already aware of the pages in memory behaviour and i understand why, it is also the point of if the issue here, on mobile there is no way to refresh programmatically.

**Comment by Nivedipa-MSFT** [comment] 2022-11-18 18:17
@Tower450 - We have raised a documentation bug for it and will add a note saying, "If a mobile app has multiple tabs, the tab does not reload whenever user switches tab".
Issue link for Documentation bug: [Please add a note saying "If a mobile app has multiple tabs, the tab does not reload whenever user switches tab"](https://github.com/MicrosoftDocs/msteams-docs/issues/7474#top)

**Comment by Tower450** [comment] 2022-11-24 19:35
thanks

**Comment by Nivedipa-MSFT** [comment] 2022-11-25 04:51
@Tower450 - Could you please share your [Feedback](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FDevSupportFeedback&data=05%7C01%7Cv-nivedipasu%40microsoft.com%7C99577f8c47b947c4a7e308dabbf85ef4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638028972748606110%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MPvWEVRKT1wEKtU%2FuJJaYeU9vGV%2FentV8vqQsm7H0R8%3D&reserved=0) here.

**Comment by Wajeed-msft** [comment] 2022-12-06 14:31
Documentation update is published. Closing this from the issue tracking list, please feel free to raise a feature ask on [Microsoft Teams Feedback portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472). Please feel free to re-open this if you have any further question on the same.

**Closed by Wajeed-msft** 2022-12-06 14:31 UTC
Labels: request: feature, teams-developer-support
