### ISSUE TITLE
 removeEvent.notifyFailure does not have any effect

### ISSUE THREAD

**Issue by bajzat** [OfficeDev/microsoft-teams-library-js#179] opened 2019-02-25 15:46 UTC
Hi! 

I'm working on a Teams integration and facing an issue. The following code sample does not work, the users can remove the Teams tab even if the removeEvent.NotifyFailure is called. 

```javascript
    MicrosoftTeams.settings.registerOnRemoveHandler((removeEvent: MicrosoftTeams.settings.RemoveEvent) => {
      removeEvent.notifyFailure('You cannot remove this tab.');
    });
```

My application starts listening to this event when the iframe is loaded and the remove button click triggers the event handler as it's expected. When the app call the nofifyFailure the teams writes an entry to the console but removes the tab.

![image](https://user-images.githubusercontent.com/1759750/53349198-deb85280-391c-11e9-8847-d1ba43150208.png)

Thanks,

Tamas

**Comment by ydogandjiev** [comment] 2019-02-25 18:59
Hi @bajzat, unfortunately the behavior you have described is currently by design. We cannot allow failures in an app (either intentional or otherwise) to create a loss of control situation for our users wherein they cannot remove a tab.

**Comment by bajzat** [comment] 2019-03-01 08:18
Hi @ydogandjiev , thanks for the information. Is there any chance to change this behaviour? I understand you don't want to let the application controls the removal process in 100% but currently, anyone from the team can remove a tab even if the person is not team owner and this operation affect the whole team.

**Comment by Wajeed-msft** [comment] 2022-11-16 03:18
Closing old questions from the tracking items. Please feel free to re-open.

**Closed by Wajeed-msft** 2022-11-16 03:18 UTC
