### ISSUE TITLE
Deeplink to stage view doesn't work in new MS Teams (Version 23306.3406.2547.5131)

### ISSUE THREAD

**Issue by andrii-ilin** [OfficeDev/microsoft-teams-library-js#2082] opened 2023-12-06 21:44 UTC
Hi!!! In our app, we are using deeplink mechanism to open the stage view with the link to part of our system.

We are using SDK 2.x

`microsoftTeams.app.openLink(dest_url)`

example of `dest_url` from https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/tabs-link-unfurling#stage-view

`https://teams.microsoft.com/l/stage/{appId}/0?context={"contentUrl":"contentUrl","websiteUrl":"websiteUrl","name":"Contoso"}`

our URL looks like the same (I omit appId)

<img width="1109" alt="Screenshot 2023-12-06 at 14 29 03" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/95683510/196b2e82-0814-4c53-8565-b41802a13d2f">

It is working without any problem in old MS Teams (MS Teams classic)

Stop working after the update, Promise returned by `microsoftTeams.app.openLink(dest_url)` resolves successfully, with no errors and a clean console

**Comment by Prasad-MSFT** [comment] 2023-12-07 07:50
@andrii-ilin - We are able to repro this issue in New Teams both in Web and Desktop client. In Teams Classic it works fine.
We have raised a bug for the same. We will inform you once we get any further update from engineering team. 

Thanks!

**Comment by tiennguyen1293** [comment] 2023-12-15 08:23
i'm facing this issue :(.

**Comment by hoanjon** [comment] 2023-12-16 10:29
hi @Prasad-MSFT , we got the same issue when use  `microsoftTeams.app.openLink(deepLinkURL)` in Teams New.
It shows “Your link points to a tab that no longer exists“ 
<img width="449" alt="Screenshot 2023-12-16 at 17 27 08" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/107026484/8b956208-a212-4385-91f8-e198bdc9d684">
 but actually it redirect to correct tab, This not happen in Teams Classic

**Comment by Prasad-MSFT** [comment] 2023-12-29 09:47
Hi @tiennguyen1293 , @hoanjon - We have informed engineering team about multiple reports on the issue. Currently we don't have any update to share. Once we get further info, we will share in this thread. Thanks!

**Comment by andrii-ilin** [comment] 2024-02-22 02:19
Hi @Prasad-MSFT , any updates? The 2.20.0 version was released but the issue persists

**Comment by saketkintali** [comment] 2024-03-07 21:16
We debugged the issue and found that the issue is within turnitin app. provided them with steps to fix their logic to have their logic call  our SDK. this could be closed.

**Comment by ChetanSharma-msft** [comment] 2024-03-14 12:22
We are closing this issue for now, please feel free to reopen it, if required.

**Closed by ChetanSharma-msft** 2024-03-14 12:22 UTC
Labels: bug, teams-developer-support, T2.1
