### ISSUE TITLE
Updating a custom Teams app with a new manifest containing Resource Specific Consent (RSC) doesn't update the App's permission on the team right away.

### ISSUE THREAD

**Issue by ingmaramzan** [OfficeDev/microsoft-teams-library-js#1543] opened 2023-01-20 07:12 UTC
We are developing a custom Teams App and we plan to move our notifications from our chatbot to the user's activity feed.
For this purpose, we plan to add the `TeamsActivity.Send.Group` RSC so that we can send notifications to our users through Graph API from our back app.
So we needed to update our App's manifest to include this required permission.

Right now, we are testing this through a sideloaded App. We updated our app with a new manifest containing our desired RSC.

After updating the App by following this prompt above the tab of our Application. 
![image](https://user-images.githubusercontent.com/40421267/213637353-d73cc1c9-de34-4979-9332-155e2e79e86a.png)

We checked whether our App has the permission or not by following this documentation [Check your app for added RSC permission in a team](https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent#check-your-app-for-added-rsc-permissions-in-a-team)
But the request returned empty, only after uninstalling the App from the Manage Team section and then reinstalling the app does the permission added to the app.

Is this a bug or are we missing something, we cannot afford this to happen in our Production App which we already publish to Appsource.

Any help will be appreciated!

Thanks.

**Comment by Nivedipa-MSFT** [comment] 2023-01-20 07:28
@ingmaramzan - If I am not wrong, you are uploading an app in Teams admin center and adding that app in personal scope. Later you are updating the app in team's admin center by uploading updated package and on accessing the app you are getting message that newer version app is available. However, the permission details are not yet updated. Right? Could you please let us know how much time you have taken to check if the updates are reflected? Could you please wait sometime after updating, so that changes will get reflected. Also please share your older and updated manifest along with repro steps, so that we can check once from our end.

**Comment by ingmaramzan** [comment] 2023-01-20 10:29
Hi, thank you for the quick response. 
I would like to clarify a few things first:
1. I am uploading the app via Teams through the steps: App => Manage your apps => Upload an app => Upload an app to your org's app catalogue => add the app to a team
2. Yes I updated the app's manifest through the team's admin center.
3. Yes, the permission details are not updated.

To answer your questions:
1. Yes the permission details are not yet updated, the last time I tested (today) I wait for around 5 minutes. But previously I had also waited for hours if not overnight.
2. And here are the manifest and the repro steps

OLD MANIFEST:
```
{
   "$schema":"https://developer.microsoft.com/en-us/json-schemas/teams/v1.11/MicrosoftTeams.schema.json",
   "version":"1.0.0",
   "manifestVersion":"1.11",
   "id":"357ddca8-daf8-4691-9652-8a1abb73f655",
   "packageName":"com.package.name",
   "name":{
      "short":"Application TEST",
      "full":"Application TEST"
   },
   "developer":{
      "name":"Application Developer",
      "mpnId":"",
      "websiteUrl":"https://www.myapplication.com",
      "privacyUrl":"https://www.myapplication.com/privacy",
      "termsOfUseUrl":"https://www.myapplication.com/termsofuse"
   },
   "description":{
      "short":"Short description of our app",
      "full":"This is a testing environment for our app"
   },
   "icons":{
      "outline":"outline.png",
      "color":"color.png"
   },
   "accentColor":"#FFFFFF",
   "configurableTabs":[
      {
         "configurationUrl":"https://www.myapplication.com/#/config",
         "canUpdateConfiguration":false,
         "scopes":[
            "team"
         ],
         "context":[
            "channelTab"
         ]
      }
   ],
   "staticTabs":[
      {
         "entityId":"conversations",
         "scopes":[
            "personal"
         ]
      },
      {
         "entityId":"about",
         "scopes":[
            "personal"
         ]
      }
   ],
   "bots":[
      {
         "botId":"93d3a759-ceff-4463-b863-ad930662f6ca",
         "scopes":[
            "personal"
         ],
         "isNotificationOnly":true,
         "supportsCalling":false,
         "supportsVideo":false,
         "supportsFiles":false
      }
   ],
   "validDomains":[
      "www.myapplication.com"
   ],
   "webApplicationInfo":{
      "id":"ae0c9a67-6c31-4c05-858e-55a1c79e3cc6",
      "resource":""
   }
}
``` 

NEW MANIFEST: 
```
{
   "$schema":"https://developer.microsoft.com/en-us/json-schemas/teams/v1.15/MicrosoftTeams.schema.json",
   "version":"1.0.1",
   "manifestVersion":"1.15",
   "id":"357ddca8-daf8-4691-9652-8a1abb73f655",
   "packageName":"com.package.name",
   "name":{
      "short":"Application TEST",
      "full":"Application TEST"
   },
   "developer":{
      "name":"Application Developer",
      "mpnId":"",
      "websiteUrl":"https://www.myapplication.com",
      "privacyUrl":"https://www.myapplication.com/privacy",
      "termsOfUseUrl":"https://www.myapplication.com/termsofuse"
   },
   "description":{
      "short":"Short description of our app",
      "full":"This is a testing environment for our app"
   },
   "icons":{
      "outline":"outline.png",
      "color":"color.png"
   },
   "accentColor":"#FFFFFF",
   "configurableTabs":[
      {
         "configurationUrl":"https://www.myapplication.com/#/config",
         "canUpdateConfiguration":false,
         "scopes":[
            "team"
         ],
         "context":[
            "channelTab"
         ]
      }
   ],
   "staticTabs":[
      {
         "entityId":"conversations",
         "scopes":[
            "personal"
         ]
      },
      {
         "entityId":"about",
         "scopes":[
            "personal"
         ]
      }
   ],
   "bots":[
      {
         "botId":"93d3a759-ceff-4463-b863-ad930662f6ca",
         "scopes":[
            "personal"
         ],
         "isNotificationOnly":true,
         "supportsCalling":false,
         "supportsVideo":false,
         "supportsFiles":false
      }
   ],
   "validDomains":[
      "https://www.myapplication.com",
   ],
   "webApplicationInfo":{
      "id":"ae0c9a67-6c31-4c05-858e-55a1c79e3cc6",
      "resource":"api://https://www.myapplication.com/ae0c9a67-6c31-4c05-858e-55a1c79e3cc6"
   },
   "activities":{
      "activityTypes":[
         {
            "type":"sendNotif",
            "description":"You received a new notification!",
            "templateText":"{message}"
         }
      ]
   },
   "authorization":{
      "permissions":{
         "orgWide":[
            
         ],
         "resourceSpecific":[
            {
               "name":"TeamsActivity.Send.Group",
               "type":"Application"
            }
         ]
      }
   }
}
```

To reproduce:
1. Upload the old manifest through Teams: App => Manage your apps => Upload an app => Upload an app to your org's app catalogue
2. Create a new tabulation of the app in a team channel
3. Check for the app's permission through Graph
4. Update the app's manifest from team's admin center
5. Update the app in the team through the prompt shown above the app's tabulation when the tabulation is opened
6. Check for the app's permission through Graph again

**Comment by Nivedipa-MSFT** [comment] 2023-01-20 11:11
@ingmaramzan - Thanks for your details. We will test this and update you soon.

**Comment by ingmaramzan** [comment] 2023-01-24 02:18
Hi @Nivedipa-MSFT, we are testing this on the web using Google Chrome.

**Comment by Nivedipa-MSFT** [comment] 2023-01-25 04:48
@ingmaramzan - We will test this on web using Google Chrome and update you soon.

**Comment by ingmaramzan** [comment] 2023-01-30 12:43
Hi, sorry I hadn't get back to you sooner. I didn't get any notifications from your update.

Here please use this manifest instead of the one I sent you.
OLD MANIFEST:
```
{
   "$schema":"https://developer.microsoft.com/en-us/json-schemas/teams/v1.11/MicrosoftTeams.schema.json",
   "version":"1.0.0",
   "manifestVersion":"1.11",
   "id":"357ddca8-daf8-4691-9652-8a1abb73f655",
   "packageName":"com.package.name",
   "name":{
      "short":"Application TEST",
      "full":"Application TEST"
   },
   "developer":{
      "name":"Application Developer",
      "mpnId":"",
      "websiteUrl":"https://www.myapplication.com",
      "privacyUrl":"https://www.myapplication.com/privacy",
      "termsOfUseUrl":"https://www.myapplication.com/termsofuse"
   },
   "description":{
      "short":"Short description of our app",
      "full":"This is a testing environment for our app"
   },
   "icons":{
      "outline":"outline.png",
      "color":"color.png"
   },
   "accentColor":"#FFFFFF",
   "configurableTabs":[
      {
         "configurationUrl":"https://checklistapptest.z22.web.core.windows.net/#/config",
         "canUpdateConfiguration":false,
         "scopes":[
            "team"
         ],
         "context":[
            "channelTab"
         ]
      }
   ],
   "staticTabs":[
      {
         "entityId":"conversations",
         "scopes":[
            "personal"
         ]
      },
      {
         "entityId":"about",
         "scopes":[
            "personal"
         ]
      }
   ],
   "bots":[
      {
         "botId":"93d3a759-ceff-4463-b863-ad930662f6ca",
         "scopes":[
            "personal"
         ],
         "isNotificationOnly":true,
         "supportsCalling":false,
         "supportsVideo":false,
         "supportsFiles":false
      }
   ],
   "validDomains":[
      "checklistapptest.z22.web.core.windows.net"
   ],
   "webApplicationInfo":{
      "id":"ae0c9a67-6c31-4c05-858e-55a1c79e3cc6",
      "resource":""
   }
}
```

NEW MANIFEST:
```
{
   "$schema":"https://developer.microsoft.com/en-us/json-schemas/teams/v1.11/MicrosoftTeams.schema.json",
   "version":"1.0.0",
   "manifestVersion":"1.11",
   "id":"357ddca8-daf8-4691-9652-8a1abb73f655",
   "packageName":"com.package.name",
   "name":{
      "short":"Application TEST",
      "full":"Application TEST"
   },
   "developer":{
      "name":"Application Developer",
      "mpnId":"",
      "websiteUrl":"https://www.myapplication.com",
      "privacyUrl":"https://www.myapplication.com/privacy",
      "termsOfUseUrl":"https://www.myapplication.com/termsofuse"
   },
   "description":{
      "short":"Short description of our app",
      "full":"This is a testing environment for our app"
   },
   "icons":{
      "outline":"outline.png",
      "color":"color.png"
   },
   "accentColor":"#FFFFFF",
   "configurableTabs":[
      {
         "configurationUrl":"https://checklistapptest.z22.web.core.windows.net/#/config",
         "canUpdateConfiguration":false,
         "scopes":[
            "team"
         ],
         "context":[
            "channelTab"
         ]
      }
   ],
   "staticTabs":[
      {
         "entityId":"conversations",
         "scopes":[
            "personal"
         ]
      },
      {
         "entityId":"about",
         "scopes":[
            "personal"
         ]
      }
   ],
   "bots":[
      {
         "botId":"93d3a759-ceff-4463-b863-ad930662f6ca",
         "scopes":[
            "personal"
         ],
         "isNotificationOnly":true,
         "supportsCalling":false,
         "supportsVideo":false,
         "supportsFiles":false
      }
   ],
   "validDomains":[
      "checklistapptest.z22.web.core.windows.net"
   ],
   "webApplicationInfo":{
      "id":"ae0c9a67-6c31-4c05-858e-55a1c79e3cc6",
      "resource":"api://https://www.myapplication.com/ae0c9a67-6c31-4c05-858e-55a1c79e3cc6"
   },
   "activities":{
      "activityTypes":[
         {
            "type":"sendNotif",
            "description":"You received a new notification!",
            "templateText":"{message}"
         }
      ]
   },
   "authorization":{
      "permissions":{
         "orgWide":[
            
         ],
         "resourceSpecific":[
            {
               "name":"TeamsActivity.Send.Group",
               "type":"Application"
            }
         ]
      }
   }
}
```

**Comment by Nivedipa-MSFT** [comment] 2023-01-30 13:45
@ingmaramzan - We will test this with new manifest and update you soon.

**Comment by Nivedipa-MSFT** [comment] 2023-02-17 10:24
@ingmaramzan - We are actively checking the status of the bug with engineering team. We will let you know once we get any updates on it.

**Comment by Nivedipa-MSFT** [comment] 2023-03-05 06:50
@ingmaramzan - We are actively checking the status of the bug with engineering team. We will let you know once we get any updates on it.

**Comment by ChetanSharma-msft** [comment] 2023-05-16 13:46
I apologize for delay in response.
We are actively checking the status of bug fixes with engineering team and will update this thread, once it is fixed.

Thanks!!

**Comment by Nivedipa-MSFT** [comment] 2023-09-25 18:11
@ingmaramzan - We received an update from the engineering team stating that this is by design behavior. The banner in the personal app for sideloaded apps only updates the personal app. Single consent for updates applies only to published apps, which have a stable app ID.

**Comment by ChetanSharma-msft** [comment] 2023-09-26 09:42
We are closing this issue for now, please feel free to reopen it, if required.

**Closed by ChetanSharma-msft** 2023-09-26 09:42 UTC
Labels: bug, teams-developer-support, needs author feedback
