### ISSUE TITLE
AADSTS65001: The user or administrator has not consented to use the application with ID 'e418adde-0a06-4892-b20c-8b03a856bec4' named 'pfnew local 2'. Send an interactive authorization request for this user and resource.\r\nTrace ID: ae035d6a-c83c-4e6c-a25d-c7b1dbdb1000\r\nCorrelation ID: 0cfa2557-d675-474b-ae4c-e584b814d6f7\r\nTimestamp: 2023-05-25 16:11:09Z

### ISSUE THREAD

**Issue by aoneahsan** [OfficeDev/microsoft-teams-library-js#1770] opened 2023-05-25 18:10 UTC
AADSTS65001: The user or administrator has not consented to use the application with ID 'e418adde-0a06-4892-b20c-8b03a856bec4' named 'pfnew local 2'. Send an interactive authorization request for this user and resource.\r\nTrace ID: ae035d6a-c83c-4e6c-a25d-c7b1dbdb1000\r\nCorrelation ID: 0cfa2557-d675-474b-ae4c-e584b814d6f7\r\nTimestamp: 2023-05-25 16:11:09Z

------------------------------------------------------------------------------------------
<img width="1211" alt="Screenshot 2023-05-25 at 11 09 01 PM" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/37369204/3559bf00-1a86-4143-b8cd-9212e90990ed">

Here's a video explaining the error I'm facing in detail (JFR, I created this video to explain the error to my colleague (shoaib))

Video Part 1
https://www.youtube.com/watch?v=39X-qHWA7yU
https://www.awesomescreenshot.com/video/17738171?key=0ad1e2fdc214349efe814d06f039bb9e
Video Part 2
https://www.awesomescreenshot.com/video/17739595?key=e90dae212cf3ebe04fadc64dca61541c

------------------------------------------------------------------------------------------
Complete Error I'm getting when hitting the API (I have added a screen shot showing the API I'm hitting in postman)

{
    "error": "invalid_grant",
    "error_description": "AADSTS65001: The user or administrator has not consented to use the application with ID 'e418adde-0a06-4892-b20c-8b03a856bec4' named 'pfnew local 2'. Send an interactive authorization request for this user and resource.\r\nTrace ID: 80151ab6-ed70-4d0e-8d6b-bab0cde11800\r\nCorrelation ID: 44e40bac-7839-4812-abc3-96f66403c66d\r\nTimestamp: 2023-05-25 18:09:53Z",
    "error_codes": [
        65001
    ],
    "timestamp": "2023-05-25 18:09:53Z",
    "trace_id": "80151ab6-ed70-4d0e-8d6b-bab0cde11800",
    "correlation_id": "44e40bac-7839-4812-abc3-96f66403c66d",
    "suberror": "consent_required"
}

------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------

**Comment by ChetanSharma-msft** [comment] 2023-05-26 07:25
Hello @aoneahsan - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by ChetanSharma-msft** [comment] 2023-05-26 07:29
Hello @aoneahsan - Could you please try to Exchange the token ID with the server-side token.
Reference doc link: https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-graph-api?tabs=dotnet#exchange-the-token-id-with-the-server-side-token

Reference sample link: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/69c76fded29d7ae0fde49841d4ec9af7597ceedd/samples/tab-sso

Also, please check if Admin consent is required for any of your Graph Permissions and if yes, please give admin consent and try it again.

**Comment by aoneahsan** [comment] 2023-05-26 07:31
Thanks @ChetanSharma-msft 
(it's a task assigned to me a week ago, I tried many different flows mentioned on ms teams sso and azure msal integration pages, but none of them worked for me so far).

I'm available if you have any questions so please do ask.

**Comment by aoneahsan** [comment] 2023-05-26 07:34
> Hello @aoneahsan - Could you please try to Exchange the token ID with the server-side token. Reference doc link: https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-graph-api?tabs=dotnet#exchange-the-token-id-with-the-server-side-token
> 
> Reference sample link: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/69c76fded29d7ae0fde49841d4ec9af7597ceedd/samples/tab-sso
> 
> Also, please check if Admin consent is required for any of your Graph Permissions and if yes, please give admin consent and try it again. ![image](https://user-images.githubusercontent.com/59052547/241150130-2706fc3e-4bdc-4416-b39a-2f26c14d3526.png)

@ChetanSharma-msft 
if you see the video i shared i did follow that link (shown in first or second video) it's not working, that function is giving this error I shared here.

and none of the permissions I have selected so far need admin consent (as shown in the video) so that should not be a problem (but just for recorded I have tried giving admin consent as well but the error remains the same.

**Comment by ChetanSharma-msft** [comment] 2023-05-26 07:36
Hello @aoneahsan - I apologize for your trouble.
Could you please refer below sample which is already in running condition and let me know if you still need any further help here:

Reference sample link: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/69c76fded29d7ae0fde49841d4ec9af7597ceedd/samples/tab-sso

**Comment by ChetanSharma-msft** [comment] 2023-05-26 07:44
You can also refer these threads where similar issues are resolved:

https://stackoverflow.com/questions/71945646/azure-registered-app-error-the-user-or-administrator-has-not-consented-to-use-t

https://stackoverflow.com/questions/59282141/aadsts65001-the-user-or-administrator-has-not-consented-to-use-the-application

https://learn.microsoft.com/en-us/answers/questions/545439/aadsts65001-the-user-or-administrator-has-not-cons

Please let us know if you still face the same issue after following these steps.

**Comment by aoneahsan** [comment] 2023-05-26 07:46
@ChetanSharma-msft 
here is what I'm looking for.

a simple newly created "react app" with just the "@microsoft/teams-js" package, 

get the "id token" using the "getAuthToken()" (which is working)

the scopes I'm requesting right now are

https://graph.microsoft.com/User.Read Channel.ReadBasic.All ChannelMessage.Send email offline_access opened profile Team.ReadBasic.All

and when I try to exchange this for access token using that link flow or direct API flow, it fails and gives this error (issue ticket error)

**Comment by ChetanSharma-msft** [comment] 2023-05-26 07:55
Thanks @aoneahsan - We will look into it from our end and let you know the updates.

Thanks!!

**Comment by aoneahsan** [comment] 2023-05-26 07:58
okay

**Comment by ChetanSharma-msft** [comment] 2023-05-26 08:03
Hello @aoneahsan - Are you targeting to test your app in iOS or Android mobile as well or only on Web or Desktop Teams client?

**Comment by aoneahsan** [comment] 2023-05-26 08:04
i have not tested it on mobile yet, but i will need to. right now I'm only testing it on web.

**Comment by ChetanSharma-msft** [comment] 2023-05-26 08:05
Which Teams JS library version you are using currently?

**Comment by aoneahsan** [comment] 2023-05-26 08:19
@ChetanSharma-msft 
Here are the auth Microsoft packages i have used so far (with their version numbers.


<img width="528" alt="Screenshot 2023-05-26 at 1 17 10 PM" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/37369204/6e779666-19fc-4787-a408-434ad2144264">
<img width="303" alt="Screenshot 2023-05-26 at 1 17 28 PM" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/37369204/349a962c-e5e6-4fa2-9075-ad2e9bbeebd7">
<img width="666" alt="Screenshot 2023-05-26 at 1 17 45 PM" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/37369204/0f3467cc-7d9c-4254-a4b6-0e105e9ea852">

and here is the react version we are using

<img width="673" alt="Screenshot 2023-05-26 at 1 18 39 PM" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/37369204/6b547814-12b5-4e62-8f18-d898292c72cd">

**Comment by aoneahsan** [comment] 2023-05-26 10:18
> You can also refer these threads where similar issues are resolved:
> 
> https://stackoverflow.com/questions/71945646/azure-registered-app-error-the-user-or-administrator-has-not-consented-to-use-t
> 
> https://stackoverflow.com/questions/59282141/aadsts65001-the-user-or-administrator-has-not-consented-to-use-the-application
> 
> https://learn.microsoft.com/en-us/answers/questions/545439/aadsts65001-the-user-or-administrator-has-not-cons
> 
> Please let us know if you still face the same issue after following these steps.

@ChetanSharma-msft 
I have tried these and still getting the error (some times I do get a access token back, but when I try to get data against that access token from graph API, e.g: for this API 
"https://graph.microsoft.com/v1.0/me/joinedTeams"

then it does not work.

**Comment by iambmelt** [comment] 2023-05-26 17:27
>The user or administrator has not consented to use the application with ID 'e418adde-0a06-4892-b20c-8b03a856bec4' named 'pfnew local 2'. Send an interactive authorization request for this user and resource.\r\nTrace ID: ae035d6a-c83c-4e6c-a25d-c7b1dbdb1000\r\nCorrelation ID: 0cfa2557-d675-474b-ae4c-e584b814d6f7\r\nTimestamp: 2023-05-25 16:11:09Z

This error means that Azure AD cannot issue a token because there is no recorded consent to do so. In order to issue a token for this resource, for this application, (as the message suggests) either the user or the tenant administrator must grant consent.

If this application is deployed in your enterprise and users do not have the ability to grant consent, then you must use [admin consent](https://learn.microsoft.com/en-us/azure/active-directory/manage-apps/grant-admin-consent?pivots=portal) to preauthorize the application.

In the case where users _can_ grant consent, you need to proxy this error to your application front-end, such that an [authentication dialog can be opened](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/authentication?view=msteams-client-js-latest#@microsoft-teams-js-authentication-authenticate) and the user can grant the necessary permissions. ([more info](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-graph-api?tabs=dotnet#known-limitations))

The prompt looks like this:
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/990063/b14abbff-637a-45ac-8481-9635c2cc49d5)

**Comment by aoneahsan** [comment] 2023-05-30 09:59
hi @ChetanSharma-msft 

any update on this?

it's a task I need to finish which is blocking our next production deployment, so any help is appreciated.

if you can provide a simple (create react app) code with these graph apis working, then I can continue with this, if the teams-js package is not working for any reason, then I'm fine with any other azure-msal package.

as long as the access token obtained from that package works against the ms graph apis.

APIs that are required (to work/return data against given access tokens).
1) user joined the team's list
2) team info by giving team id
3) channels list of the team by giving the team id
4) send a message to the channel using the team and channel id

right now I need these APIs working.

so if you can provide a demo react app with either Microsoft/teams-js package or any other Azure msal package (azure/msal-react | azure/msal-browser) which returns a working access token that works against these mentioned APIs.

Thanks in advance.

I look forward to hearing from you soon.

**Comment by aoneahsan** [comment] 2023-05-30 10:04
Hi @iambmelt 
Thanks for the comment.

I have already tried these links.

"authenticate() from microsoft/teams-js package"
"SSO in teams tab app"

I have even tried the "azure/msal-react" & "azure/msal-browser" packages to get an access token.

using these packages when I ask users to give consent they do see the screen where it shows a list of permissions I have asked for.

but the access token I get back either does not work at all, or when times works, it only works against the "/me" graph API, and gives this same "ticket error" when I try to use that against other mentioned APIs (mentioned in the above comment.

so yes, if you can, please check the video I have shared in the starting comments of this ticket, you will see I have shared a video showing what I have tried so far, and the issue I am facing.

and also, if you can provide a simple demo react app with these four APIs (mentioned in the last/above comment) working that will be great.

Thanks in advance.

I look forward to hearing from you soon.

**Comment by ChetanSharma-msft** [comment] 2023-05-30 13:12
> 

Hello @aoneahsan - Have you tried this sample?

**Comment by ChetanSharma-msft** [comment] 2023-05-30 13:33
> 

You can refer below sample:
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/graph-channel-lifecycle/nodejs/views/lifeCycleDemo.ejs#LL131C35-L131C35

**Comment by aoneahsan** [comment] 2023-05-30 15:33
@ChetanSharma-msft 
I know the API I need to hit to get the data, the issue is "access token" which is the reason I have created this ticket.

the access token I'm getting from "microsoft/teams-js" or other "azure msal" packages is giving this error when I try to hit these APIs "https://graph.microsoft.com/v1.0/teams/"+teamId+"/channels"

I have tried "microsoft-graph-client" as well.
as the issue is with the access token and not how I'm hitting the API, so that also failed with the same error.

@ChetanSharma-msft as I requested, if possible, please provide a simple react app with these 4 mentioned APIs working, so I can check what I was doing wrong.

Thanks in advance.

I look forward to hearing from you soon.

**Comment by ChetanSharma-msft** [comment] 2023-05-30 17:22
Hello @aoneahsan - We have investigated your error and here are our findings.
1) You have configured your application with multi-tenant app registrations and looks like you haven't granted consent for the Graph API's permissions. 

So, you need to handle the error and provide interactive button to grant the consent.
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/tab-personal-sso-quickstart/js/src/components/Tab.js#L72

https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/tab-personal-sso-quickstart/js/src/components/Tab.js#L90

Please refer this sample: 
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-personal-sso-quickstart/js/src/components

**Comment by aoneahsan** [comment] 2023-06-01 06:56
hi @ChetanSharma-msft 
i'm trying these links you shared, I will get back to you once I'm done implementing these mentioned solutions.

**Comment by Meghana-MSFT** [comment] 2023-06-01 06:56
Could you please let us know if your issue is resolved?

**Comment by aoneahsan** [comment] 2023-06-01 06:57
@meghana-msft

no the issue is not resolved yet.

> Could you please let us know if your issue is resolved?

**Comment by aoneahsan** [comment] 2023-06-01 15:43
this is the function giving this error

<img width="1029" alt="exchangeClientTokenForServerToken" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/37369204/060e320d-f672-4111-b6fd-8f940893475f">

**Comment by ChetanSharma-msft** [comment] 2023-06-02 07:09
Hello @aoneahsan - Sorry for your trouble.
We will try it from our end and let you know the updates.

**Comment by Meghana-MSFT** [comment] 2023-06-02 16:07
We tried to setup the sample we are also getting error at getGraphAccessToken - 

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/81138249/6ada49e5-3a83-4bb5-83f6-48f04a9310bf)

**Comment by asadtechlead** [comment] 2023-07-09 20:15
Hi @ChetanSharma-msft, @Meghana-MSFT asking on behalf of @aoneahsan. is this issue is resolved or any update on this? Thanks

**Comment by aoneahsan** [comment] 2023-07-09 21:35
Hi @ChetanSharma-msft 
the task is assigned to @asadtechlead (he's senior developer here at perkforce)
(I'm currently on leaves).

**Comment by aoneahsan** [comment] 2023-07-27 18:09
hi @ChetanSharma-msft 
i just got back from leaves.
wanted to check if there is any update on this issue?

**Comment by aoneahsan** [comment] 2023-07-27 18:11
@Meghana-MSFT just checking if you had any luck getting the correct output?
anything changed in package?
or any update at all?
i just got back, so I will be working again on this task to see if that MS Teams auth package error is resolved, if it's resolved than I can finally finish my project task :]

**Comment by Meghana-MSFT** [comment] 2023-07-28 16:29
@aoneahsan - Apologies for the delay we will check and get back to you.

**Comment by aoneahsan** [comment] 2023-07-28 19:05
@Meghana-MSFT 
Thanks a lot.

I'm trying it again.
so yes please do let me know if it works for you this time.

Thanks in advance and have a great day ☺️

**Comment by Meghana-MSFT** [comment] 2023-08-03 20:45
Apologies, we are checking internally about this error. We will get back to you.

**Comment by perkforce** [comment] 2023-08-12 21:23
@Meghana-MSFT thanks for prioritizing this.
We are also having the same issue that @aoneahsan details above.
We are lucky to be members of Microsoft for Startups programme, but this issue is quite specific...please can you help us.
Kindest regards,
Al

**Comment by aoneahsan** [comment] 2023-08-15 07:09
Hi @Meghana-MSFT 
basically @perkforce is my employer, so it's basically me how's working on code side, he just replied as he is also watching this issue.

and yes i tried, it's still not working for me, please do let me know if it's any different for you, Thanks in advance.

**Comment by aoneahsan** [comment] 2023-08-19 06:50
Hi there

@ChetanSharma-msft @Meghana-MSFT @Wajeed-msft 

Do we have any update on this issue?

Has anybody got it working?

I tried but still not working for me.

Please let me know if it's working for you guys.

Thanks, and have a great day.

**Comment by perkforce** [comment] 2023-08-19 23:07
> @perkforce - Could you please confirm if you are also facing this issue [#1770 (comment)](https://github.com/OfficeDev/microsoft-teams-library-js/issues/1770#issuecomment-1572295465) ?

Hi @Meghana-MSFT 
Yes, the exact same issue, @aoneahsan is on the team.
We would greateful of any help with this, we've tried multiple solutions.
Thank you!

**Comment by ChetanSharma-msft** [comment] 2023-08-21 05:51
Hello Everyone - Sorry for delay in response.
I will look into it and let you know the updates.

**Comment by TheUncharted** [comment] 2023-08-21 06:48
Hi everyone 
We have the same type of problem
First our problem is that we can't reproduce it locally in a sand boxed organization because the admin has automatically the consent. So the popup doesn't appear
How can you reproduce the problem locally ? Is there a way to  disable the admin consent  and force the popup to show ?

**Comment by ChetanSharma-msft** [comment] 2023-08-21 07:27
Hello @TheUncharted - Could you please share the recent repro steps that you have tried?

**Comment by ChetanSharma-msft** [comment] 2023-08-21 18:11
Hello Everyone,
I have setup this sample locally: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-personal-sso-quickstart/js

**1) Updated all the required permissions in the app registration:**

![MicrosoftTeams-image (6)](https://github.com/OfficeDev/microsoft-teams-library-js/assets/59052547/54deb851-cc41-4a2b-8c8f-a9d9073ca312)

**2) Updated graph scopes in all the required places in the code:**

![MicrosoftTeams-image (7)](https://github.com/OfficeDev/microsoft-teams-library-js/assets/59052547/1751c37e-2875-4ae9-a25a-146ff33edd2c)

3) When I execute the application, I am getting the consent popup like below for the first time:

![MicrosoftTeams-image (8)](https://github.com/OfficeDev/microsoft-teams-library-js/assets/59052547/f259c9c4-79c1-440e-b61e-0ee49660ebde)

4) After granting the consent, I am getting access token:

![MicrosoftTeams-image (10)](https://github.com/OfficeDev/microsoft-teams-library-js/assets/59052547/58b45a76-839f-4790-a443-f8370229f75b)

5) Once I call the API **"https://graph.microsoft.com/v1.0/me/joinedTeams"** using Postman, I am getting proper output:

![MicrosoftTeams-image (9)](https://github.com/OfficeDev/microsoft-teams-library-js/assets/59052547/d1f4e5b0-8aa0-475a-8351-1d73131df138)

So, I am still not able to repro the issue.
Kindly make sure that you have configured your application properly and please test the app again.

Also, you can refer this sample: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-personal-sso-quickstart/js

**Comment by TheUncharted** [comment] 2023-08-22 06:18
Hello @ChetanSharma-msft 
Thanks for you example, can you publish it as a production app so we can test to install it in our sandboxed organization ?
To check that your example works for the consent ? If it works we may as you maybe more screenshots of your setting so we can compare with ours

**Comment by ChetanSharma-msft** [comment] 2023-08-22 06:56
Sure, I will deploy it and let you know the updates.

**Comment by TheUncharted** [comment] 2023-08-22 10:03
By the way I asked our developer, the settings the API permissions  are different of yours and are  like that
I wonder if the permissions/scope are correct ?
Our goal is to retrieve all the users profile and groups of our customer's organization to create users in our app/database 

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/24917492/932d9dff-89bb-4d26-8642-8fe3f59314bf)

**Comment by ChetanSharma-msft** [comment] 2023-08-22 10:08
Hello @TheUncharted - I have just added few permissions and try to get the access token which is working fine for us.
Could you please let me know any specific permission that I can add and test it from our end?

**Comment by aoneahsan** [comment] 2023-08-22 16:17
Hi @ChetanSharma-msft 
Please try with the permissions I have tried in this video.
https://www.youtube.com/watch?v=39X-qHWA7yU

Permissions needed are

Team.ReadBasic.All
Channel.ReadBasic.All
ChannelMessage.Send
User.Read
profile
email
openid
offline_access


Can you please try with these permissions?

and let me know if you can get an "ID Token" from MS Teams app (using the "microsoft/teams-js" package)
and then get an "Access Token" using the "ID Token" you got from the last step; that "Access Token" should work with MS Graph API.

So that is the whole flow.

1) get "ID Token" with requested permissions from MS Teams
2) get "Access Token" using that "ID Token"
3) and finally, get proper data from MS Graph API on behave of the user.

I'm facing this issue (this ticket issue) at step 2.

**Comment by ChetanSharma-msft** [comment] 2023-08-23 11:02
Hello @aoneahsan - I already tried with above permission only:
I have configured below scopes in the code:

GRAPH_SCOPES=User.Read Channel.ReadBasic.All ChannelMessage.Send email offline_access openid profile Team.ReadBasic.All

I am able to get the access token and able to call the Graph API using postman as mentioned last time.

**Comment by ChetanSharma-msft** [comment] 2023-08-23 11:21
> 

Hello @aoneahsan - I have gone through your video.
You are using delegated permissions in your application which required user consent and you are not able to handle and show consent popup because your application is not a web application.

Can you please try to give admin consent for APIs in your app registration and test it once?

**Comment by aoneahsan** [comment] 2023-08-23 11:54
@ChetanSharma-msft 
I tried that.

Provided "Admin Consent" when adding permissions.

But it still does not work.

Please let me know if it works for you (a demo video if possible, showing the steps you took and final working state)

Thanks for your help.

**Comment by TheUncharted** [comment] 2023-08-23 12:10
@ChetanSharma-msft by the way is your test ran on a web browser ?
our problem is also on the ms team app

**Comment by ChetanSharma-msft** [comment] 2023-08-23 12:12
Hello @TheUncharted - I am running my app inside Teams web client.

**Comment by aoneahsan** [comment] 2023-08-30 13:57
@ChetanSharma-msft @Meghana-MSFT @iambmelt @TheUncharted @Wajeed-msft 
Hi there guys

just to check if anybody was able to kill the bug 

our MS Teams App Production release is stuck due to this issue, so if anyone finds a solution for this issue, please share it with others.

Thanks, have a great day.

Please do let me know if anything is needed from my side (another video to explain some missing parts of the problem or any questions).

**Comment by aoneahsan** [comment] 2023-09-04 16:57
Hi @ChetanSharma-msft 
I have tried it, and the "/me" ms-graph API works fine.

but when i try any other API, like teams etc then it fails

**Comment by ChetanSharma-msft** [comment] 2023-09-04 18:16
Hello @aoneahsan - Thanks for the information.
Could you please make sure that you have granted consent for all the required permissions other than Profile and Offline access scope and also make sure that you used same permissions while [exchanging token](https://youtu.be/39X-qHWA7yU?t=665).

**Comment by aoneahsan** [comment] 2023-09-04 18:42
@ChetanSharma-msft 
yes, i provided the consent for all mentioned permissions (admin consent, even when none of the permissions i'm using require a admin consent).
and yes when i request a access token i only mention the permissions i have given consent to in auth process.

**Comment by ChetanSharma-msft** [comment] 2023-09-04 18:47
Hello @aoneahsan - Thanks for the further information.
Could you please try decoding your access token using this: https://jwt.io/ 
Please check if decoded token contains all the Graph API permissions before calling the API?
If it does not contain required permissions, that means there is permission scopes issue in the code while exchanging the token to get actual access token.

**Comment by aoneahsan** [comment] 2023-09-04 18:58
okay,
i will retry that tomorrow and will share a new video recording.
please let me know if you need anything else from my side.

**Comment by ChetanSharma-msft** [comment] 2023-09-04 19:09
Hello @aoneahsan - Please try that steps and share the steps, so that we can further investigate your issue.

**Comment by aoneahsan** [comment] 2023-09-04 19:17
sure, i will share a video recording.

**Comment by ChetanSharma-msft** [comment] 2023-09-05 17:34
Hello @aoneahsan - Any updates on this?

**Comment by aoneahsan** [comment] 2023-09-06 18:22
hi @ChetanSharma-msft 
sorry, i was not able to check it today either.

i have added this on top in my todo for tomorrow (INSHAALLAH)
will send you the requested details by tomorrow day end (Pakistan time zone).

Thanks a lot for your support

**Comment by aoneahsan** [comment] 2023-09-07 17:35
Hi @ChetanSharma-msft 
update
-
i'm working on retesting it.
as during this time our code base has changed a lot, so i had to redo it.
i will continue on it tomorrow and INSHAALLAH by tomorrow day end will send you a video.
-
Please let me know if you have any questions or suggestions.

Thanks again for your support.

Have a good day.

**Comment by ChetanSharma-msft** [comment] 2023-09-11 04:43
Hello @aoneahsan  - Did you get a chance to check on it?
Could you please let us know so that we can check it from our end as well.

**Comment by aoneahsan** [comment] 2023-09-11 13:59
hi @ChetanSharma-msft 
i'm working on it right now, will let you know before I take off today.

**Comment by aoneahsan** [comment] 2023-09-11 15:50
hi @ChetanSharma-msft 
this is where i'm right now

https://www.awesomescreenshot.com/video/20667308?key=572b18a7e116560e12d0bfb882c83f66

i'm solving this error right now

if you know anything about this let me know, otherwise I will share next video recording after resolving this error.

**Comment by aoneahsan** [comment] 2023-09-11 16:49
@ChetanSharma-msft i'm facing this error right now, 
last time this was working, but this time it's giving error on this part, please let me know if it's working for you or not, please provide I sample code if possible

let me know if you need sample code from my side as well or not.

**Comment by ChetanSharma-msft** [comment] 2023-09-12 05:11
Hello @aoneahsan - Please add client id's for Web/Desktop in Expose an API section and check it again.
Could you please also check the access token in JWT if you are able to see the actual permissions in it?

**Comment by sayali-MSFT** [comment] 2023-09-12 11:59
Hello @aoneahsan -We are currently reviewing the provided video. Could you please set the redirect URL and then verify it once? You can also refer to the readme file below for instructions on setting the URL.

Link- https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-personal-sso-quickstart/js#setup

**Comment by aoneahsan** [comment] 2023-09-12 19:34
Hi @ChetanSharma-msft @sayali-MSFT 

Here is my today's update

The error I faced is resolved due to client IDs for the team web and desktop app, which is needed to expose API as apps are allowed to use the scope.


Right now, we are facing another error. 

{
    "el": "authentication.getAuthToken error 1",
    "em": "App does not have the required permissions for this operation,"
    "error": {}
}

<img width="875" alt="Screenshot 2023-09-13 at 12 27 26 AM" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/37369204/07241ee0-ebba-421c-b013-9fcfea0b7756">

Please let me know if you guys have an idea about this error; I will continue from here tomorrow and resolve this error and continue.

@ChetanSharma-msft I will check the token and let you know the result once I get an access token. Right now, I'm facing these errors.

I have recorded a video to show my changes to the project; please provide a sample project and a video showing the total flow you have taken that works for you. I will try and replicate that on my system.

The video is currently uploading on slow internet. :(
I will add a link to the uploaded video tomorrow in this chat.

**Comment by aoneahsan** [comment] 2023-09-12 19:40
<img width="1714" alt="Screenshot 2023-09-13 at 12 40 14 AM" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/37369204/d161fb54-b700-441b-a38c-21c74f6dba11">


video uploading in progress, i will share this tomorrow.

**Comment by aoneahsan** [comment] 2023-09-12 19:55
@ChetanSharma-msft @sayali-MSFT 
Is this relevant to me??

https://stackoverflow.com/questions/60621983/registering-your-app-in-teams-is-failing-with-error-you-dont-have-permissions

As shown in the last video, I can upload a custom app.. this is a test tenant account I created to do this task, and I'm logged in using the main admin account.

In the past, I could complete this process until an ID token from this function without any issue, so why is it not working now?

Do you guys have any idea?

**Comment by ChetanSharma-msft** [comment] 2023-09-13 05:33
> Hello Everyone, I have setup this sample locally: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-personal-sso-quickstart/js
> 
> **1) Updated all the required permissions in the app registration:** (Registered app as multi-tenant)
> 
> ![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/59052547/262109280-54deb851-cc41-4a2b-8c8f-a9d9073ca312.png)
> 
> **2) Updated graph scopes in all the required places in the code including below file :**
> 
> ![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/59052547/262109318-1751c37e-2875-4ae9-a25a-146ff33edd2c.png)
> 
> 3. When I execute the application, I am getting the consent popup like below for the first time:
> 
> ![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/59052547/262109415-f259c9c4-79c1-440e-b61e-0ee49660ebde.png)
> 
> 4. After granting the consent, I am getting access token which has all the configured scopes (after exchanging the id token inside code):
> 
> ![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/59052547/262109470-58b45a76-839f-4790-a443-f8370229f75b.png)
> 
> 5. Once I call the Graph API **"https://graph.microsoft.com/v1.0/me/joinedTeams"** using Postman with above token, I am getting proper output:
> 
> ![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/59052547/262109511-d1f4e5b0-8aa0-475a-8351-1d73131df138.png)
> 
> So, I am still not able to repro the issue. Kindly make sure that you have configured your application properly and please test the app again.
> 
> Also, you can refer this sample: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-personal-sso-quickstart/js
> 
> Please feel free to connect if you still have any issue.

Hello @aoneahsan - I would suggest you to please setup this sample and test it from your end via adding extra required permissions. Also, please check the generated access token whether you are able to see all the required permissions in it.

**Comment by aoneahsan** [comment] 2023-09-13 08:30
okay @ChetanSharma-msft 
let me try this sample code.

**Comment by aoneahsan** [comment] 2023-09-13 08:57
@ChetanSharma-msft 
please do share the link of flow you are using to exchange ID token for access token.

**Comment by ChetanSharma-msft** [comment] 2023-09-14 05:10
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/tab-personal-sso-quickstart/js/src/components/Tab.js#L66

**Comment by aoneahsan** [comment] 2023-09-14 10:45
hi @ChetanSharma-msft 
i'm checking it right now will let you know the update in few hour

**Comment by aoneahsan** [comment] 2023-09-14 18:43
MS Teams SSO Login and Data from MS Graph API:
Part1:
https://www.awesomescreenshot.com/video/20771301?key=2fb157d1519f1b7b40c7826a16fb763c

Part2:
https://www.awesomescreenshot.com/video/20773455?key=d2c87a74d0f1197cf99d53914523c507

Part3:
https://www.awesomescreenshot.com/video/20775215?key=898a1cd26cb67c0afd38e993ef3a49ce


Github:
https://github.com/aoneahsan/perkforce-msteams-task-sample-app

@ChetanSharma-msft, it worked; thanks a lot for your great support (a prominent feature in our app was stuck due to this MS Teams Error; now we will be able to get that done).

Thanks, @everyone else as well, who was part of it.

I have added these 3 video recordings and this sample code for any of you still facing this error.

I hope it will help you, 

Have a great day.

**Comment by ChetanSharma-msft** [comment] 2023-09-15 04:42
Hello @aoneahsan - Good to hear that your issue has resolved now.
Kindy share your valuable feedback as it is important for us: https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u

**Comment by sayali-MSFT** [comment] 2023-09-15 09:36
We are closing this issue for now, Please feel free to reopen it, if required.

**Closed** 2023-09-15 09:58 UTC
Labels: teams-developer-support, needs author feedback

**Comment by aoneahsan** [comment] 2023-10-03 16:09
As I am a text-based AI and cannot personally experience service or provide feedback, I cannot offer a review. However, if you've had an experience with a support team and you've received a message like this, they are asking for your feedback to understand how well they resolved your issue.

👍: Indicates that your issue was resolved and you are satisfied with the support you received.
👎: Indicates that your issue was not resolved or you are not satisfied with the support.
❤️: Indicates that you had an excellent experience beyond your expectations.

Typically, support teams use this feedback to improve their service, so your input is usually highly valued. If you also have the option to provide more detailed feedback through a link, that's an opportunity to explain what specifically you liked or didn't like about the support experience.

**Comment by aoneahsan** [comment] 2024-02-14 15:55
> Hi all, i have the same bug: AADSTS65001: The user or administrator has not consented to use the application with ID 'f49ea541-3d90-4251-a897-056fcd518611' named 'Partner Center Web App 1'. Send an interactive authorization request for this user and resource. Trace ID: c651d7d9-5e8c-40b8-a6f0-1b069af7ab00 Correlation ID: e31a4d21-a54c-4a81-8727-277746a2a293 Timestamp: 2024-02-13 18:48:13Z.
> 
> In my case, i am trying to get price sheet from the Partner Center API. I do get the refresh token, but when i use the refresh token to try to generate an access token, i get the above error.

Just for record, I had a call with @abrantie11z 

and discussed his problem, it's a different problem, and I requested him to create a new ticket for it.

i think he is not requested the required scopes and missing few other points in between, but because his requirement is quite different from mine I can not say for sure.

happy to help :)
