### ISSUE TITLE
Tabs: Caching issue

### ISSUE THREAD

**Issue by sueess** [OfficeDev/microsoft-teams-library-js#1205] opened 2022-06-09 11:58 UTC
We experience often Caching issues with the MS Teams Tabs of our bot app. If we deploy new versions of the web page, which is displayed in the tab, the tab still tries to load old resources. It does that also, if the resources do not exist anymore. We could see that using the DevTools.

**What did not work:**

- We tried multiple times to reload the page using the "reload" button on the upper-right corner.
- We restarted MS Teams

**What worked:**
- We logged-out and in again. This worked. But this is not a solution for hundreds of users of our app.

<img width="986" alt="Bildschirmfoto 2022-06-09 um 13 41 42" src="https://user-images.githubusercontent.com/6587992/172840688-2b20f57f-1f1a-4df1-b01d-9dae446b9521.png">

**Solution:**

- The caching musst be more defensive
- At least it should do a hard reload, if somebody manually clicks on the refresh icon

**Comment by sayali-MSFT** [comment] 2022-06-28 10:22
@sueess - We are looking into this I will get back to you soon.

**Comment by ChetanSharma-msft** [comment] 2022-06-28 10:22
Hello @sueess, @MajaEffenberg -  I apologize for the delay in response.
Thanks for reporting this issue.

We will look into it and get back to you.

**Comment by sueess** [comment] 2022-06-29 10:25
BTW here are more people having this issue: https://docs.microsoft.com/en-us/answers/questions/442600/teams-caching-issue-launching-canvas-app-from-team.html

**Comment by sueess** [comment] 2022-06-29 11:56
Once again:

**MS Teams Desktop**
<img width="1093" alt="tab-problem-3" src="https://user-images.githubusercontent.com/6587992/176430135-0701b0b5-cf50-43c6-90de-d94d5c01b284.png">

**MS Teams Web**

<img width="1360" alt="Bildschirmfoto 2022-06-29 um 13 45 37" src="https://user-images.githubusercontent.com/6587992/176430220-80879781-ad8d-4975-9c98-26ce7239225a.png">


**MS Teams Desktop (after sign-out / sign-in)**
<img width="833" alt="Bildschirmfoto 2022-06-29 um 13 55 44" src="https://user-images.githubusercontent.com/6587992/176430609-678adfde-5b57-471b-94e8-fdfc29480b9e.png">

**Comment by sayali-MSFT** [comment] 2022-06-29 11:59
@sueess -We are able to repro the issue, we are check it internally it's Bug or feature request then raised bug accordingly and let you know.

**Comment by sueess** [comment] 2022-06-29 12:56
@sayali-MSFT This is not a feature, this is obviously a bug all have to deal with. So why should we add that to a feature request?

**Comment by ChetanSharma-msft** [comment] 2022-06-29 13:10
@sueess - As per my understanding, cache issue needs to be handled at the client side.
Have you created any custom tab using React or  .net MVC?
Are you trying to load the images from CSS file?

**Comment by ChetanSharma-msft** [comment] 2022-06-29 13:29
@sueess -  Could you please try with the below approach also, once on your next deployment/refresh?

“You can append a random query parameter to the stylesheet URL (for example via JavaScript or server side code). It will not change the CSS file that is being loaded, but it will prevent caching, because the browser detects a different URL and will not load the cached stylesheet. <link rel="stylesheet" type="text/css" href="[mysite/style.css**?id=1234**](http://mysite/style.css?id=1234)">”

**Comment by sueess** [comment] 2022-06-29 14:12
@ChetanSharma-msft 

We are using hashing to avoid loading old Javascript (you see that in @MajaEffenberg screenshots). The caching issue is on the HTML, which is referenced in the manifest. If you deploy our web page, we cannot resubmit the manifest always with a different hash (it would take days until the new manifest reached all users).

Can you please have a closer look at this post: https://github.com/OfficeDev/microsoft-teams-library-js/issues/1205#issuecomment-1153921806
if you look at the two screenshots, you can see the same page at the same time, once on the Desktop Teams and once on the Web Teams. The web Teams shows the most recent page (with different hashes) and the Desktop Teams shows an old page. So there is clearly an issue with the Desktop version.

Do you understand?

The solution: MS Teams has to avoid to cache the HTML, which are referenced in the manifest. Or at least do a hard reload, when somebody clicks on the refresh icon.

**Comment by ChetanSharma-msft** [comment] 2022-06-29 14:26
@sueess - Thanks a lot for your suggestions.
We will check this issue with engineering team and get back to you.

**Comment by sueess** [comment] 2022-06-29 14:28
Cool, thanks! That would be great, cause I'm sure many apps suffer from that.

**Comment by sayali-MSFT** [comment] 2022-07-01 04:30
@sueess -do you have a network trace of this scenario? 
 network trace from the Teams Desktop Client demonstrating the issue . Instructions for opening a debugger in the Desktop Client can be found here: https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools#access-devtools-on-the-desktop

**Comment by sueess** [comment] 2022-07-01 12:05
It's not possible to record the network traffic on a tab, because MS Teams closes the console (which is responsible for the iframe) whenever you reload the page. That may be another bug :)

https://user-images.githubusercontent.com/6587992/176891040-1abded3f-2bae-4283-a481-48c9920f93e6.mov

**Comment by sayali-MSFT** [comment] 2022-07-07 05:24
@sueess - To reload your app with the debugger attached you can just switch to its frame:
![MicrosoftTeams-image (72)](https://user-images.githubusercontent.com/93527375/177697431-2353afb2-c929-412c-9334-b061f6fc5770.png)
And then execute the window.location.reload() command:
![MicrosoftTeams-image (73)](https://user-images.githubusercontent.com/93527375/177697465-5c8124d4-1bd0-41c0-bb5b-6079621a8191.png)

**Comment by sayali-MSFT** [comment] 2022-07-08 11:15
@sueess -Did you get chance to check?

**Comment by MajaEffenberg** [comment] 2022-07-08 14:48
@sayali-MSFT Thanks for the information, we were able to reload the app with the debugger mode.

Below I am posting a video showing different scripts in Desktop Teams App and Windows and Teams Web App for the same user at the same time. Desktop Teams App load old not existing version of page and web app load new version (no titles at the top of the page).

https://user-images.githubusercontent.com/89073193/178015187-5e52157c-41a7-448f-a171-6f1ac93553a5.mp4

**Comment by sayali-MSFT** [comment] 2022-07-15 04:35
@MajaEffenberg -A video is not helpful. We need a network trace that shows the cached resources being loaded.

**Comment by ChetanSharma-msft** [comment] 2022-07-22 06:05
@MajaEffenberg - Hope you are doing well !!
Can you please share the network trace so that engineering team can further investigate on your issue?

**Comment by MajaEffenberg** [comment] 2022-08-02 15:52
We are unable to reproduce the error right now as it appears randomly after deploying a new version of the tabs app, which means we cannot provide network trace.

We can give you more information when this error reappears, but I think we should not close this issue as the error has not been fixed.

**Comment by AndrewCraswell** [comment] 2022-08-04 21:46
Hey @sueess, this is an issue our team ran into very early on in our app development. As you note, the old HTML file itself is being cached. This can be handled from the server side. It's important to configure your server to identify the HTML file should not be cached.

For example, in the past I've used CDN settings like these to add `Cache-Control` headers on the index.html response to ensure that the file will never be cached by the browser or Teams client:
![image](https://user-images.githubusercontent.com/1908292/182958255-ec2eddb3-f6dc-488a-9800-243dcc4eea70.png)

This is why it's important to check the network trace, to understand what the response headers are on the index.html file.

**Comment by nwojod-MSFT** [comment] 2022-10-07 21:46
Closing this issue. Feel free to reopen if you still encounter the problem.

**Closed by nwojod-MSFT** 2022-10-07 21:46 UTC
Labels: teams-developer-support
