### ISSUE TITLE
Deeplink to a tab is not working on the iOS

### ISSUE THREAD

**Issue by naorcho** [OfficeDev/microsoft-teams-library-js#1201] opened 2022-06-07 11:46 UTC
Hi,

We tried to contact the support but they suggested opening a ticket here :)

We are using the Teams app with a single tab. From the bot, you can tap a button and open the tab with deep-link, which works great on the web/desktop/Android. On iOS there is an error: 'Link not supported' with the message: 'You can't open this link on the mobile app. Please open it on the desktop or web app.'

The link works based on this [docs](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?tabs=teamsjs-v2#deep-link-to-your-tab) 

We also added webUrl to support 'unsupported devices'. Seams like the mobile app is not working well with deep-links.

This is our link: 
[https://teams.microsoft.com/l/entity/431a9917-9c32-480e-a584-6c149e7b7213/3cb5afa8-f89e-40b9-a172-6caa52d048c6?webUrl=customPage%2Fhttps%3A%2F%2Fapp.eloops.com%2Fmsg%2Fread%2Felns1cT3ublmGKUic8x5W1fVH%2F1126649%2F%7BUSER_ID%7D&context=%7B%22subEntityId%22%3A+%22%257B%2522token%2522%253A%2520%2522LyVYgcPuzi6V4dbRBDYm%2522%252C%2520%2522redirect%2522%253A%2520%2522customPage%252Fhttps%253A%252F%252Fapp.eloops.com%252Fmsg%252Fread%252Felns1cT3ublmGKUic8x5W1fVH%252F1126649%252F%257BUSER_ID%257D%2522%252C%2520%2522access_code%2522%253A%2520%2522qateam%2522%257D%22%7D](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fteams.microsoft.com%2Fl%2Fentity%2F431a9917-9c32-480e-a584-6c149e7b7213%2F3cb5afa8-f89e-40b9-a172-6caa52d048c6%3FwebUrl%3DcustomPage%252Fhttps%253A%252F%252Fapp.eloops.com%252Fmsg%252Fread%252Felns1cT3ublmGKUic8x5W1fVH%252F1126649%252F%257BUSER_ID%257D%26context%3D%257B%2522subEntityId%2522%253A%2B%2522%25257B%252522token%252522%25253A%252520%252522LyVYgcPuzi6V4dbRBDYm%252522%25252C%252520%252522redirect%252522%25253A%252520%252522customPage%25252Fhttps%25253A%25252F%25252Fapp.eloops.com%25252Fmsg%25252Fread%25252Felns1cT3ublmGKUic8x5W1fVH%25252F1126649%25252F%25257BUSER_ID%25257D%252522%25252C%252520%252522access_code%252522%25253A%252520%252522qateam%252522%25257D%2522%257D&data=05%7C01%7Co365su11%40microsoft.com%7C2ee4689703e342ef027a08da47e46574%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637901343536834221%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gkSPQsVnY4demPpdsY3k3biedllnxtmC1xpgtk1LpXs%3D&reserved=0)

Maybe there is another property we can add to solve it by opening the link outside? Any other solution?

Update:
Any link starting with https://teams.microsoft.com/l/entity/ (the deep link by Microsoft) is not working on iOS and brings the error alert. Adding webUrl (as the fallback URL) is not working either, although it is part of the documentation.

**Comment by naorcho** [comment] 2022-06-14 05:47
Should I expect a resolution here? I haven't got any email/update from you :)

**Comment by Meghana-MSFT** [comment] 2022-06-14 16:41
We are looking into this issue, we will update you.

**Comment by naorcho** [comment] 2022-06-16 08:51
I added some more info to make it clear

**Comment by Meghana-MSFT** [comment] 2022-06-17 06:22
We have checked by pasting deeplinks to Static tab and configurable tab in a chat. On clicking of those links in iOS gives the above-mentioned popup saying link not supported. We are investigating it with the internal team.

**Comment by naorcho** [comment] 2022-06-18 05:21
Regarding your question, yes we used the shareDeepLink that way: 

```
https://teams.microsoft.com/l/entity/<appId>/<entityId>?webUrl=<entityWebUrl>&label=<entityLabel>&context=<context>

```

**Comment by naorcho** [comment] 2022-06-30 18:32
Thanks, @tiennguyen1293 
I see also this: https://docs.microsoft.com/en-us/answers/questions/357996/teams-app-deeplink-couldn39t-work-on-mobile-device.html

Hopefully, we will see a fix soon.

**Comment by Meghana-MSFT** [comment] 2022-07-14 14:44
@naorcho - We tried it on the latest store build, the issue is not reproducible. Could you please try it on the latest build and confirm the same?

**Comment by Meghana-MSFT** [comment] 2022-07-22 13:04
@naorcho - Could you please try it on the latest build and confirm the fix?

**Comment by naorcho** [comment] 2022-07-22 18:06
The latest Teams app from the AppStore v4.12.0 still show the links not supposed. Should I expect another version? As this one is from a week ago.

**Comment by Meghana-MSFT** [comment] 2022-07-25 10:09
Could you please try once by directly pasting the deeplink in Teams application and check if it is working or not?

**Comment by naorcho** [comment] 2022-07-26 05:39
Still does not work when I do it with a direct link: https://cdn.appyvent.com/elns1cT3ublmGKUic8x5W1fVH/dashboard_uploads/LBPqRjLJS6aT9xKzslyp_poster_1658813848.mp4

**Comment by unikoski** [comment] 2022-08-01 11:22
I have the exact same issue - I am using teams version 4.13.1. Is there any work being done on this issue?

**Comment by ChetanSharma-msft** [comment] 2022-08-01 11:54
Hello @naorcho, @unikoski - Please try updating your Teams client to the latest version and check it once ?

**Comment by naorcho** [comment] 2022-08-01 12:09
Thank you for the update,
Unfortunately, it still doesn't work.
I had an update and now the latest version number is 4.13.1.
That's what I have on settings 

Version: 4.13.1
Build : 4.13.77.2022133801/0728 (general)
Calling Version : 2022.21.01.6

**Comment by unikoski** [comment] 2022-08-01 13:03
> I have the exact same issue - I am using teams version 4.13.1. Is there any work being done on this issue?



> Hello @naorcho, @unikoski - Please try updating your Teams client to the latest version and check it once ?

Yeah, this was *after* an update - version 4.13.1

**Comment by ChetanSharma-msft** [comment] 2022-08-01 13:19
Thanks for the confirmation.
We will investigate on your issue and get back to you.

**Comment by unikoski** [comment] 2022-09-06 11:27
@ChetanSharma-msft Any progress on this?
@naorcho - Have you discovered anything to work around the problem?

**Comment by naorcho** [comment] 2022-09-06 18:45
I have just tried again and now it seems to work. @unikoski can you check?
@ChetanSharma-msft FYI

**Comment by unikoski** [comment] 2022-09-08 11:11
@ChetanSharma-msft - Hi  I checked - still not working. I installed latest version of teams. I turned off my phone and on again. Sadness. @naorcho  - thanks for the update - yours is still working?

**Comment by naorcho** [comment] 2022-09-11 06:24
@unikoski 
Still working. I'm using this version:
Version : 4.15.1
Build : 4.15.77.2022153904/0826 (general)
Calling Version : 2022.30.01.1
Release Branch : 2022Aug-T1

**Comment by ChetanSharma-msft** [comment] 2022-11-17 16:00
We are closing this issue for now, please feel free to reopen it, if required.

**Closed by ChetanSharma-msft** 2022-11-17 16:00 UTC
Labels: bug, teams-developer-support
