### ISSUE TITLE
Bug: ChannelType is undefined in 1.8.0

### ISSUE THREAD

**Issue by abdulkareemnalband** [OfficeDev/microsoft-teams-library-js#436] opened 2020-10-13 07:52 UTC
```ts
import * as microsoftTeams , {ChannelType} from '@microsoft/teams-js'

microsoftTeams.getContext(ctx  => ctx.channelType === ChannelType.Private )
```

above snippet used to work in `1.7.0` , not anymore in `1.8.0`

looks like 65d0ab8e0a81245041b53145652cd724341b6340 has caused this regression

**Comment by anandvnath** [comment] 2020-10-27 06:54
@abdulkareemnalband 

Can you please share more about your project setup?
1. Is it a JS project pulling dependency for the Microsoft Teams SDK or is it a TS based project?
2. `import * as microsoftTeams , {ChannelType} from '@microsoft/teams-js' `. This statement itself throws an error for me . https://stackoverflow.com/questions/45231419/typescript-multiple-imports
3. Can you verify if other enums such as `HostClientType` or `FrameContexts` or `TeamType` works fine for you in 1.8.0? One difference I found is that `ChannelType` was not part of the exported list in index.ts. 

I tried many ways to reproduce this issue and still not able to. Getting answers to above questions will immensely help in narrowing down the problem.

One difference I do notice

**Comment by RamaMohanaChary** [comment] 2020-10-27 11:33
@abdulkareemnalband:

Could you please try with below import statements.
import * as microsoftTeams from "@microsoft/teams-js";
import {ChannelType} from '@microsoft/teams-js';

**Comment by abdulkareemnalband** [comment] 2020-10-28 02:51
@anandvnath 
1. Its typescript angular project
2. Sorry I mistyped here 
     I'm importing them as either `import * as microsoftTeams  from '@microsoft/teams-js'` or `import {ChannelType} from '@microsoft/teams-js'` not as unified import
3. I don't know about others but `FrameContexts ` enum is working

**Comment by anandvnath** [comment] 2020-10-28 17:10
@abdulkareemnalband 

Thanks for you update.

Its good news that you found `FrameContexts` enum to be working. I suspect then the issue is specific to `ChannelType` as it is not imported in index.ts. Let me verify this with the help of internal team using an angular project.

**Comment by anandvnath** [comment] 2020-10-30 06:58
@abdulkareemnalband 

Thanks for your update. Can you please share a sample app that I can use to repro the issue? This will also help me verify the fix.

**Comment by abdulkareemnalband** [comment] 2020-11-02 07:20
@anandvnath 
here is stackblitz link with 1.7 where it works https://stackblitz.com/edit/teams-17?file=src/app/app.component.ts
here is stackblitz link with 1.8 where it does not work https://stackblitz.com/edit/team-18?file=src/app/app.component.ts

**Comment by anandvnath** [comment] 2020-11-11 11:28
@abdulkareemnalband 

Sorry for the delay! 

I was able to successfully test that the fix in my branch solves the problem. Thanks for sharing your app. Indeed it was the missing ChannelType export that created this issue when we moved from const enum to enum.

If you wish to try the fix out, you can use https://github.com/OfficeDev/microsoft-teams-library-js/tree/anandnat/issue-436-channeltype

1. Clone the repo
2. Checkout the branch anandnat/issue-436-channeltype
3. Run yarn install` `yarn build`.

`dist` folder will be generated which contains the JS SDK files. Go to `node_modules/@microsoft/teams-js/` in your app and replace the `dist` folder.

I will raise a pull request and get this merged.

**Closed** 2020-11-11 17:30 UTC
Labels: needs triage :mag:, teams-developer-support
