### ISSUE TITLE
Share to meeting stage

### ISSUE THREAD

**Issue by xXTraceXx** [OfficeDev/microsoft-teams-library-js#2426] opened 2024-07-25 16:07 UTC
Hi,

in your examples like https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-share-to-stage-signing/csharp you share to the meeting stage via a button click that invokes `shareAppContentToStage`. The button lives in the iframe.

The `shareAppContentToStage` gets via parameter an url that should be opened on the stage. 

Additionally there is a share button beside the 'close sidepanel' button. This will open the same url that you shared via `shareAppContentToStage` if you have invoked 'shareAppContentToStage' already. 

Question:
1. why you have to implement a own "share button" instead of using the already existing?
2. why you have to invoke `shareAppContentToStage` once to be then able to share to a specific url?

I am forced to call `shareAppContentToStage` immediatley, so i can be sure, if someone pressed the "share button" on the sidepanel will open the right url?!

**Comment by lakhveerk** [comment] 2024-07-25 18:51
Hello!
Would you say below is the relevant code? 

```
  const shareDocumentAndTakeControlCallback = useCallback(() => {
    takeControl();
    meeting.shareAppContentToStage(
      shareToStageCallback,
      `${window.location.protocol}//${window.location.host}/stage/${id}`,
    );
  }, [takeControl, ### shareToStageCallback]);
```

Clicking the below button will fire `shareDocumentAndTakeControlCallback` which further will call `meeting.shareAppContentToStage` and share the app to the stage. 

```
  <Button
    content={shareButtonText}
    iconPosition="before"
    onClick={shareDocumentAndTakeControlCallback}
  />
```

You mentioned 'share button'. What does that do? Is it hooked directly to  `shareAppContentToStage` call? Can you please elaborate more on this:
> I am forced to call shareAppContentToStage immediately, so i can be sure, if someone pressed the "share button" on the sidepanel will open the right url?!

**Comment by xXTraceXx** [comment] 2024-07-26 08:36
Yes of course. 

Like in the examples they implemented their own "Share to meeting" Button (see following picture) that calls `shareAppContentToStage` like you mentioned.

![Screenshot from 2024-07-26 10-16-38](https://github.com/user-attachments/assets/0a8d3f6b-a0ac-41a0-9ce8-cbfd56bf5761)

But every sidepanel has already a "sidepanel share button" (in the old teams it was beside the "close sidepanel button", in the new teams it is called "Share" at the bottom of the sidepanel).

Old teams
![Screenshot from 2024-07-26 10-20-30](https://github.com/user-attachments/assets/0a931093-af14-4790-b856-c1d1f69b5325)

New teams
![Screenshot from 2024-07-26 10-22-11](https://github.com/user-attachments/assets/fbe8acd8-7236-4260-a552-fa32e767a22d)

Lets assume our sidepanel url is `example.net/sidepanel`. Then i observed the "share button" behaves like this:
1) You have already called `shareAppContentToStage` with url `example.net/meetingstage` => the meetingstage will open `example.net/meetingstage`
2) You have NOT called `shareAppContentToStage` => the meetingstage will open the sidepanel url `example.net/sidepanel` 

So to be sure, that every click on the "share button" will open `example.net/meetingstage` i have to call `shareAppContentToStage` immediatley after the sidepanel opened. 

I think a better solution would be to config a meetingstage url, without calling `shareAppContentToStage`.

I hope u got my point^^. Please feel free to ask again if u missed a point.

**Comment by lakhveerk** [comment] 2024-07-30 19:05
Thank you for the detailed explanation! 
It doesn't make sense to immediately call shareAppContextToStage because it will share the specified URL right away. 

The built-in Share button opens whatever is loaded on the side panel. To open any other specific url, you have to call `shareAppContentToStage` API. This can be done with a separate button. 

Currently, the built in Share button is not customizable. Please let me know if `shareAppContentToStage` is not workign as intended.

**Comment by lakhveerk** [comment] 2024-08-06 16:38
I am going to close this bug, but feel free to reopen it or open a new bug if `shareAppContentToStage` does not work correctly. Like I said, it should share the given url right away. You won't need to call this API and then wait for the end user to click on build-in 'share' button.

**Closed by lakhveerk** 2024-08-06 16:38 UTC
