### ISSUE TITLE
microsoftTeams.authentication.authenticate : "failureCallback" is invoked with the reason "CancelledByUser" even if notifySuccess(token) has been called (only on desktop teams app, works fine on web Teams app)

### ISSUE THREAD

**Issue by Ahmad-Rayyan** [OfficeDev/microsoft-teams-library-js#741] opened 2021-11-21 10:53 UTC
Hi,
 On some devices (This is random and hard to reproduce), the "failureCallback" got called even if the notifySuccess has been invoked from the authentication popup window. The reason is always  "CancelledByUser" but this is not the case because the popup got closed automatically after calling the "notifySuccess".

NOTE: 
- Win10
- Teams app v1.4.00.26376
- Microsoft teams SDK v1.11.0

- The issue disappears when the app is pop-up to a new window 
 
Thanks,

**Comment by Ahmad-Rayyan** [comment] 2021-11-21 12:29
Another point : 
microsoftTeams.initialize(() => {
      console.log("microsoftTeams.initialize done");
});

initialize never return, "microsoftTeams.initialize done" is never printed o the device with the issue

**Comment by PodgeHeavin** [comment] 2021-11-22 16:37
@Ahmad-Rayyan this is a duplicate of #629 which was raised on August 11th and still there is no fix by Microsoft

**Comment by HunaidHanfee-MSFT** [comment] 2021-11-24 18:09
@Ahmad-Rayyan - Please track the issue on it. We have got update from engineering team as well - https://github.com/OfficeDev/microsoft-teams-library-js/issues/629#issuecomment-975926875. I am closing it here.

**Closed by HunaidHanfee-MSFT** 2021-11-24 18:09 UTC
Labels: teams-developer-support, needs triage :mag:
