### ISSUE TITLE
Teams Call Deeplink not working on iOS

### ISSUE THREAD

**Issue by StefanH114** [OfficeDev/microsoft-teams-library-js#1403] opened 2022-10-18 09:02 UTC
Calling a Deeplink for a Teams Call is not working on iOS (tested for iOS 16.0.2/16.0.3 & iPadOS 15.6.1).
The Deeplinks work fine for Android or Desktop App.

Is there a workaround for iOS systems?

Example: 
```
app.openLink(
                      `https://teams.microsoft.com/l/call/0/0?users=${imEmailArray[0]}&withVideo=true`
                    );
```
or
```

call.startCall({
                      targets: [imEmailArray[0]],
                      requestedModalities: [call.CallModalities.Video],
                    });
```

**Comment by Meghana-MSFT** [comment] 2022-10-18 13:42
@StefanH114 - We tried this issue at our end using below code
`microsoftTeams.app.openLink("https://teams.microsoft.com/l/call/0/0?users=adelev@M365x654992.onmicrosoft.com&withVideo=true");`

Below are our observations

1. iOS/Android - It is starting a video call
2. Web/Desktop - It is starting an audio call ignoring the video=true

We see the same behavior as mentioned here in this thread https://github.com/OfficeDev/microsoft-teams-library-js/issues/1032.

Could you please share if you are doing it in a different way?

**Comment by StefanH114** [comment] 2022-10-18 15:09
@Meghana-MSFT 
We are using the same call. 
To give you more insight:

- We have one iOS 15.6.1 Device (MDM-managed) that works fine, but with all other iOS 15.6.1 device we face the issue mentioned above.
- All 16.*.* devices are also not working.
- We also can call persons outside the organisation with all our devices. 
- Another 15.*.* iOS device is able to call certain users and certain users not

Generally speaking it seems really confusing and unrelieable on iOS.
Just to be clear we also tried the 
```js
call.startCall({
                      targets: [imEmailArray[0]],
                      requestedModalities: [call.CallModalities.Video],
                    });
```
As mentioned in the Docs (https://learn.microsoft.com/de-de/microsoftteams/platform/concepts/build-and-test/deep-links?tabs=teamsjs-v2)
In the mobile(androir)/web/Desktop everything works perfectly fine.

**Comment by Meghana-MSFT** [comment] 2022-10-19 06:54
@StefanH114 - We are checking this discrepancy in behavior internally; we will update you.

**Comment by StefanH114** [comment] 2022-10-19 07:08
@Meghana-MSFT 

UPDATE: We tested the deeplinks directly from chat (e.g. https://teams.microsoft.com/l/call/0/0?users=xxx.xxx@xxx.com&withVideo=true) - On Android devices and PCs this worked flawlessly - on iOS we experienced the same inconsistent/mixed results as when useing it via teamsjs from a personal tab

**Comment by MichaMican** [comment] 2022-10-26 09:05
@Meghana-MSFT Meghana-MSFT Any updates? I'm facing the same issue.

**Comment by Meghana-MSFT** [comment] 2022-10-28 12:07
We tried it at our end and below are our observations:

1. Pasting deeplink in chat directly https://teams.microsoft.com/l/call/0/0?users=adelev@M365x654992.onmicrosoft.com&withVideo=true - Works fine in Android and iOS. In web/Desktop only audio call is happening, video=true is ignored
2.  Tried by setting this sample - [Microsoft-Teams-Samples/samples/tab-deeplink/nodejs at main · OfficeDev/Microsoft-Teams-Samples (github.com)](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-deeplink/nodejs) 
![image](https://user-images.githubusercontent.com/81138249/198582053-33d5b376-9dba-49f3-8411-b012bf9c9137.png)
Nothing is happening when we click on these buttons in iOS and Android. In web/Desktop only audio call is happening, video=true is ignored
3. Tried with below code, Works fine in Android and iOS. In web/Desktop only audio call is happening, video=true is ignored
` microsoftTeams.app.openLink("https://teams.microsoft.com/l/call/0/0users=adelev@M365x654992.onmicrosoft.com&withVideo=true");`
	

We are still investigating; we will get back to you with an update. Thank you.

**Comment by StefanH114** [comment] 2022-10-28 12:14
@Meghana-MSFT 
1. The deeplink in chat only works with contacts outside our organization in iOS. In Android it works fine.
2. We see the same behaviour
3. Again thos is only working for contacts outside our organization in iOS

**Comment by ChetanSharma-msft** [comment] 2022-11-18 10:40
Hello @StefanH114 - Sorry for delay in response.
We are checking this behavior with engineering team and get back to you, once we get updates from them.

**Comment by Meghana-MSFT** [comment] 2023-01-11 07:37
@StefanH114 - Can you please share the client logs. Engineering team wants to look into logs for further investigation. Thanks.

**Comment by Meghana-MSFT** [comment] 2023-02-01 11:40
@StefanH114 - Can you please share the [client logs](https://learn.microsoft.com/en-us/microsoftteams/log-files). Engineering team wants to look into logs for further investigation. Thanks.

**Comment by Meghana-MSFT** [comment] 2023-03-06 07:45
Engineering team is not able to repro this issue, Could you please follow these steps in iOS and Send feedback. 
Teams app under Settings > Help and feedback > Send feedback

Send feedback option should attach the logs automatically. But it needs to be done after reproducing the issue (deeplink not respecting withVideo=true)

**Comment by Steffi3rd** [comment] 2023-05-04 10:25
Hello! 

I have the same issue (same as https://github.com/MicrosoftDocs/msteams-docs/issues/6595) 
My app is blocked by Microsoft Testers because on iOS deeplink doesn't work. 

**"Lien non pris en charge" / "Link not supported".
"Please open it on desktop"**

It works well on desktop. 

I have the right format https://teams.microsoft.com/l/entity/${config.appTeamsId}/${tabId}.
I have even add https://teams.microsoft.com/l/entity/${config.appTeamsId}/${tabId}&webUrl=${webUrl)

None of them work on mobile, but works on desktop

![IMG_FE7866B78A8F-1](https://user-images.githubusercontent.com/814410/236177654-2ce5d955-9723-44fe-b77a-720ba4804377.jpeg)

My app (which is React tabs + bot) is working fine in production on iOS except that bug.

How to fix that please???

**Comment by Meghana-MSFT** [comment] 2023-05-08 06:06
The /l/app deeplink will not work on iOS unless the target app (in the deeplink) has updated the Apple App Store Connect Team ID on the Partner Center and republished the app.
For app to be acquired on iOS the developer needs to update there apple team ID. refer this doc https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/update-apple-store-team-connect-id

**Comment by Meghana-MSFT** [comment] 2023-06-06 13:28
Thank you for confirming, We are closing this issue for now. Please feel free to reach out to us if you have any issues further. Thank you.

**Closed** 2023-06-07 04:37 UTC
Labels: bug, teams-developer-support, needs attention
