### ISSUE TITLE
unwanted horizontal line at the bottom of cards in static tab

### ISSUE THREAD

**Issue by unikoski** [OfficeDev/microsoft-teams-library-js#1327] opened 2022-08-31 07:03 UTC
We have a teams app using a static tab that displays three adaptiveCards.

As you can see in the screen shot these cards all have an unwanted horizontal line at the end of card.
![Screen Shot 2022-08-31 at 9 58 58](https://user-images.githubusercontent.com/19687618/187613887-111a6da9-d555-4502-bc22-d3c5d17d664c.png)

If I take these cards and post them in the designer I do not see these cards, and if I post them to the chat I do not see these lines. 

How can I get rid of them?

**Comment by Prasad-MSFT** [comment] 2022-09-01 05:38
@unikoski - Could you please share the card JSON which you are using, so that we can try once from our end?

**Comment by unikoski** [comment] 2022-09-01 12:28
This happens to all my cards, I have included one here as an example:
```
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.4",
  "rtl": false,
  "minHeight": null,
  "body": [
    {
      "type": "Container",
      "horizontalAlignment": "left",
      "verticalContentAlignment": "center",
      "separator": false,
      "items": [
        {
          "type": "ColumnSet",
          "columns": [
            {
              "type": "Column",
              "horizontalAlignment": "Center",
              "verticalContentAlignment": "center",
              "separator": false,
              "spacing": "default",
              "items": [
                {
                  "type": "ActionSet",
                  "actions": [
                    {
                      "type": "Action.Submit",
                      "title": "Create new ticket",
                      "data": {
                        "solarAction": "createIncident",
                        "backToPage": 1
                      },
                      "isEnabled": true,
                      "associatedInputs": "Auto",
                      "verb": "invoke"
                    }
                  ],
                  "spacing": "default",
                  "horizontalAlignment": "left"
                }
              ],
              "width": "auto",
              "style": "Default"
            },
            {
              "type": "Column",
              "horizontalAlignment": "Center",
              "verticalContentAlignment": "center",
              "separator": false,
              "spacing": "default",
              "items": [
                {
                  "type": "ActionSet",
                  "actions": [
                    {
                      "type": "Action.Submit",
                      "title": "<<",
                      "data": {
                        "solarAction": "getPage",
                        "page": 1
                      },
                      "isEnabled": false,
                      "associatedInputs": "Auto",
                      "verb": "invoke"
                    }
                  ],
                  "spacing": "default",
                  "horizontalAlignment": "left"
                }
              ],
              "width": "auto",
              "style": "Default"
            },
            {
              "type": "Column",
              "horizontalAlignment": "Center",
              "verticalContentAlignment": "center",
              "separator": false,
              "spacing": "default",
              "items": [
                {
                  "type": "TextBlock",
                  "text": "1 / 98",
                  "size": "default",
                  "horizontalAlignment": "left",
                  "weight": "default",
                  "spacing": "default",
                  "color": "default",
                  "wrap": true
                }
              ],
              "width": "auto",
              "style": "Default"
            },
            {
              "type": "Column",
              "horizontalAlignment": "Center",
              "verticalContentAlignment": "center",
              "separator": false,
              "spacing": "default",
              "items": [
                {
                  "type": "ActionSet",
                  "actions": [
                    {
                      "type": "Action.Submit",
                      "title": ">>",
                      "data": {
                        "solarAction": "getPage",
                        "page": 2
                      },
                      "isEnabled": true,
                      "associatedInputs": "Auto",
                      "verb": "invoke"
                    }
                  ],
                  "spacing": "default",
                  "horizontalAlignment": "left"
                }
              ],
              "width": "auto",
              "style": "Default"
            }
          ],
          "rtl": false,
          "separator": false,
          "horizontalAlignent": "left",
          "spacing": "default"
        }
      ],
      "id": null,
      "spacing": "default",
      "minHeight": null,
      "height": "auto",
      "isVisible": true
    }
  ]
}
```

If I plug this into adaptivecards.io/designer it looks like this (No extra line):
![Screen Shot 2022-09-01 at 15 26 51](https://user-images.githubusercontent.com/19687618/187913476-42587e54-767a-4d26-8f08-64b51801ab59.png)



If I send it to the chat it looks like this (no extra line):
![Screen Shot 2022-09-01 at 15 20 03](https://user-images.githubusercontent.com/19687618/187913371-8c8b8795-004e-454c-958b-4fc632db2f92.png)


In the tab it looks like I sent in the original posting - with the line at the bottom.

**Comment by Prasad-MSFT** [comment] 2022-09-01 13:35
@unikoski - Yes as mentioned in Adaptive Card Designer, it renders normally.
![image](https://user-images.githubusercontent.com/62237649/187926487-86e054bc-6c3e-4e69-94e9-6e555b4fd51d.png)
There is no separator in JSON as well. So, it seems it renders in this way in tab.

**Comment by unikoski** [comment] 2022-09-01 14:44
> @unikoski - Yes as mentioned in Adaptive Card Designer, it renders normally. ![image](https://user-images.githubusercontent.com/62237649/187926487-86e054bc-6c3e-4e69-94e9-6e555b4fd51d.png) There is no separator in JSON as well. So, it seems it renders in this way in tab.

But it **DOES NOT** render this way in the tab! 
I will add a screenshot again so you can see.
![Screen Shot 2022-09-01 at 17 42 13](https://user-images.githubusercontent.com/19687618/187942631-9ee5d559-bf44-4764-ba3b-1a540eb87002.png)
So as you can see, there is an extra, unrequested separator at the bottom of the card.

**All** my cards appear this way in the static tab.

**Comment by unikoski** [comment] 2022-09-04 12:53
@Prasad-MSFT to make it even clearer:
![Drawing](https://user-images.githubusercontent.com/19687618/188314477-47b5c715-844d-4707-beb6-fed86d47e752.jpeg)

**Comment by Prasad-MSFT** [comment] 2022-09-08 09:54
@unikoski - We are also getting horizontal line at the bottom of cards in tab. There doesn't seem to be any way to remove that.
![image](https://user-images.githubusercontent.com/62237649/189092699-6bca4bdb-576f-44d6-bcb4-f1ef024ffbcd.png)
This seems by design.

**Comment by ChetanSharma-msft** [comment] 2022-10-12 18:58
We are closing this issue for now, Please feel free to reopen it, if required.

**Closed by ChetanSharma-msft** 2022-10-12 18:58 UTC
Labels: teams-developer-support
