### ISSUE TITLE
DisplayName is returning undefined

### ISSUE THREAD

**Issue by AlbertoPerez8** [OfficeDev/microsoft-teams-library-js#1776] opened 2023-05-31 20:13 UTC
I'm currently building a Teams app with the Teams Toolkit, and in it I'm attempting to receive the current logged in user's display name. This is being done with a developer tenant filled with dummy accounts, but the selected account has been verified to make sure it has a first name, a last name, and a display name through the tenant's admin portal. When I run the app, when I call the context holding the user's info with useTeams(), the display name is returning undefined. This has happened using both @microsoft/teams-js versions 2.8 and 2.11. Is there a setup procedure that I am missing or is there some sort of bug present. 

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/36648131/fbcd9c32-8c01-437e-bf0c-d2b4a485e840)

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/36648131/7c7f6b53-744b-4544-8b37-5d3cce05a0e0)

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/36648131/faec155d-83bd-46e0-a9be-ffd9f3850db4)

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/36648131/8e0221c6-5def-4cdc-a191-737ae8f5ac41)

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/36648131/635593a1-ad74-4006-a11f-baebb420ed35)

**Comment by ChetanSharma-msft** [comment] 2023-06-01 08:28
Hello @AlbertoPerez8 - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by sayali-MSFT** [comment] 2023-06-02 12:44
@AlbertoPerez8 -We have tried to setup the code but getting some error, we will let you know the update.
If it is bug, then we can raise it accordingly.
Could you please share the code snippets which are used to get the display name?

**Comment by AlbertoPerez8** [comment] 2023-06-02 13:28
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/36648131/1364cbbd-5f30-4ab2-b968-e2500bb5018c)
This is all the code that directly works with the useTeams function to extract the display name and other information from the Teams context

**Comment by sayali-MSFT** [comment] 2023-06-02 13:44
@AlbertoPerez8 -Thanks for providing information. We will check it internally and get back to you once we get any update.

**Comment by sayali-MSFT** [comment] 2023-06-30 06:11
@AlbertoPerez8 -We got the reply through engineering team, "This is by design. Teams has never returned the displayName in the app context."

They are considering this as feature request.

Currently we don’t have ETA or Update on this feature request. We will let you know once we have any updates on it. Thanks.

**Comment by sayali-MSFT** [comment] 2023-06-30 06:12
We are closing this issue for now, please feel free to reopen it, if required.

**Closed** 2023-06-30 06:18 UTC
Labels: request: feature, teams-developer-support
