### ISSUE TITLE
ThumbnailCard title does not allow text-overflow:ellipsis CSS rule

### ISSUE THREAD

**Issue by catmanjan** [OfficeDev/microsoft-teams-library-js#1645] opened 2023-03-16 02:38 UTC
We have a ThumbnailCard with the following Title:

```
var card = new ThumbnailCard
{
    Title = $"<div style=\"text-overflow:ellipsis;font-weight:600;max-width:270px;overflow:hidden;white-space:nowrap;\">blah</div>"
};
```

This works, except for some reason teams is removing the text-overflow:ellipsis rule. All the other CSS rules remain as expected, see below:

![image](https://user-images.githubusercontent.com/137350/225495938-deac86d5-7e4c-47c8-9188-08bd082fb1ff.png)

**Comment by Nivedipa-MSFT** [comment] 2023-03-16 05:19
@catmanjan - Thanks for reporting your issue. We will test this and update you soon.

**Comment by Nivedipa-MSFT** [comment] 2023-03-16 07:33
@catmanjan - We are able to repro your issue. We have raised a bug for the same. We will let you know once we get any updates from them.

**Comment by Nivedipa-MSFT** [comment] 2023-09-20 18:32
@catmanjan - We received an update from the engineering team stating that this is by design. We do not allow the complete set of CSS rules for enriching card content, including the title, subtitle, and text of thumbnail cards. Only a selected set of CSS rules is permitted, while the rest are removed.

**Comment by Nivedipa-MSFT** [comment] 2023-09-20 18:33
@catmanjan - We are closing this issue for now. Please feel free to reopen if required.

**Comment by catmanjan** [comment] 2023-09-20 23:32
@Nivedipa-MSFT how do I reopen this issue?

Where are the limitations regarding support CSS and HTML tags documented?

**Comment by Nivedipa-MSFT** [comment] 2023-10-03 10:02
@catmanjan - We are checking this with engineering team, we will update you soon.

**Comment by ChetanSharma-msft** [comment] 2023-11-25 06:03
Hello @catmanjan - Sorry for delay in response.
Currently we don't have any specific documentation for exact CSS supported for cards and you can refer this doc for HTML: https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cconnector-html#format-cards-with-html

We are checking it with engineering team and let you know the updates.

**Comment by ChetanSharma-msft** [comment] 2023-11-26 10:51
Hello @catmanjan - We got an update from engineering team that we do not recommend relying on CSS for styling in cards. The supported attribute is documented here https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format

**Comment by ChetanSharma-msft** [comment] 2023-11-26 10:54
We are closing this issue for now, please feel free to reopen it, if required.

**Closed by ChetanSharma-msft** 2023-11-26 10:54 UTC
Labels: bug, teams-developer-support
