### ISSUE TITLE
getContext on fail handler

### ISSUE THREAD

**Issue by jonathanhotono** [OfficeDev/microsoft-teams-library-js#655] opened 2021-09-16 12:45 UTC
I'm trying to detect whether a sharepoint page is loaded on microsoftTeams tab (viva connection) using `getContext()`. This works well when you're in teams but outside teams (normal browser) there is no onFailure handler being triggered. Is there any way to detect the onFailure event? 
```
try {
  microsoftTeams.initialize();
  microsoftTeams.getContext(tContext => {
    //successful on teams but not triggered on normal web browser
  })
} catch (error) {
  //this isn't triggering.. 
}
```

**Comment by HunaidHanfee-MSFT** [comment] 2021-09-28 17:16
Microsoft teams SDK is specifically for Microsoft Teams. It doesn't trigger outside of teams it is by design.

I am closing this issue as of now, feel free to open if you have any query.

**Closed by HunaidHanfee-MSFT** 2021-09-28 17:16 UTC
Labels: teams-developer-support, needs triage :mag:
