### ISSUE TITLE
iOS Outlook - app bottom navigation overlaps view port

### ISSUE THREAD

**Issue by onmomo** [OfficeDev/microsoft-teams-library-js#2222] opened 2024-03-14 13:08 UTC
We experienced the following issue with the iOS Outlook app.

## iOS Outlook app
![IMG_4F5E8EFB5BD0-1](https://github.com/OfficeDev/microsoft-teams-library-js/assets/1713109/61470231-545f-4e2b-8079-f4d6e0dd949c)

The apply (ANWENDEN) button is positioned so that it is always visible at the end of the user’s view. This means that if there is a bottom navigation/toolbar visible it should be shown above it. 
CSS implementation details: 
The component becomes fill screen by applying height: 100%
It consists of three divs - one for the header, one for the content and one for the footer with the buttons ()
The content div applies flex-grow: 1 to keep the content positioned at the top below the header.

We can't reproduce this with the Teams iOS mobile app, where the mobile app bottom navigation is excluded from the 100% viewport, which is what we expect.
## iOS Teams app
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/1713109/da8b9e9d-1fd9-4d9e-9d39-866fe4b5864d)

The same issue can be seen on other parts, that rely on the iOS Outlook bottom navigation bar being excluded from the visible viewport.

## iOS Outlook app
![IMG_65DCBEE81CD8-1](https://github.com/OfficeDev/microsoft-teams-library-js/assets/1713109/3aef92ce-c8db-4a6a-8fca-dfce83800929)

Please advise, this blocks our teams app store validation.

**Comment by ChetanSharma-msft** [comment] 2024-03-15 07:06
Hello @onmomo - Could you please share the repro steps or let us know if we can test any existing 1st party app to repro your issue?

**Comment by ErythroME** [comment] 2024-03-15 13:51
Hi @onmomo, you can fix the height issue in Outlook iOS by using 100dvh (with fallback for compatibility https://caniuse.com/mdn-api_css_dvh_static) as body height.

**Comment by onmomo** [comment] 2024-03-15 16:01
> Hi @onmomo, you can fix the height issue in Outlook iOS by using CSS 100dvh (with fallback for compatibility https://caniuse.com/mdn-api_css_dvh_static) as body height.

Thanks a lot @ErythroME. We will definitely look into this. Looks promising (https://blog.logrocket.com/improving-mobile-design-latest-css-viewport-units/#dynamic-viewport-units). We're not sure yet if vuetify does support it, though.

**Comment by sakov-ms** [comment] 2024-03-15 20:41
Thank you @onmomo for raising this issue. Do try out the solution proposed by @ErythroME and let us know if that works.

**Comment by sakov-ms** [comment] 2024-03-19 21:24
Thank you for this detailed investigation. We are checking this issue and will provide updates soon.

**Comment by AE-MS** [comment] 2024-05-09 20:40
Here's what the Outlook team said about this issue:

The implementation works differently for MS Teams and Outlook for iOS because by design there are differences in the
bottom navigation. Teams's bottom navigation bar does not cover & blur the underlying website, but Outlook for iOS does. Therefore using dvh is the preferred implementation for current support; changing the behavior on Outlook for iOS will also cause regression on other Apps therefore currently there is no plan to change the behavior on Outlook. Using CSS 100dvh (with fallback for compatibility https://caniuse.com/mdn-api_css_dvh_static) as body height should be able to workaround this issue, if it doesn’t work please post example CSS code using the dvh property for us to investigate.

**Comment by onmomo** [comment] 2024-06-07 07:24
> Here's what the Outlook team said about this issue:
> 
> The implementation works differently for MS Teams and Outlook for iOS because by design there are differences in the bottom navigation. Teams's bottom navigation bar does not cover & blur the underlying website, but Outlook for iOS does. Therefore using dvh is the preferred implementation for current support; changing the behavior on Outlook for iOS will also cause regression on other Apps therefore currently there is no plan to change the behavior on Outlook. Using CSS 100dvh (with fallback for compatibility https://caniuse.com/mdn-api_css_dvh_static) as body height should be able to workaround this issue, if it doesn’t work please post example CSS code using the dvh property for us to investigate.

@AE-MS @TrevorJoelHarris I understand that The MSTeams and Outlook for iOS bottom navigation is different. But since Microsoft allows to use teams apps ([manifest >= 1.13](https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview?tabs=Android)) to work on on M365, MS Teams and Outlook and Desktop and web, you should ensure that these platforms behave similar. Implementing edge cases in our integration for every single mobile app Microsoft published or plans to publish in the future will increase the integration efforts significantly and will make us reevaluate if this is actually worth the investment.

We were not able to make the suggested dvh workaround since we are using vuetify framework and refrain from reimplementing and testing our UI on all platform again just to make it work on the Outlook mobile app.

**Comment by AE-MS** [comment] 2024-06-12 22:27
I've related your response to the Outlook team and they'll get back to us next week to ensure they're aligned on the path forward.

**Comment by onmomo** [comment] 2024-07-01 09:31
@AE-MS Three weeks have been past since, could we please reopen this issue? Just go back a test report from the teamsub teams, highlighting more issue due to this implementation details on Outlook Mobile app.

**Comment by jekloudaMSFT** [comment] 2024-07-02 17:10
Hi @onmomo, I'm following up with the Outlook team. Can you please share more details on the other issues you're running into? Are they more scenarios that are being blocked by the navigation bar?

**Comment by onmomo** [comment] 2024-07-23 15:14
@jekloudaMSFT We can't correctly identify the viewport height with the current implementation of the iOS outlook navigation. This leads to all kinds of UX issues reported by the teamssub team. I don't think it makes a lot of sense to share more screenshots of the Outlook navigation overlapping our app in different views. The main issue is, that iOS Outlook did implement the navigation bar in a way that prevents ISVs to provide cross support for Teams Mobile and Outlook mobile. Further details can be found in this comment
* https://github.com/OfficeDev/microsoft-teams-library-js/issues/2222#issuecomment-2154250071

this is not solved and was just highlighted again by teamsubm team, blocking again our app validation, please reopen.

**Comment by TechL3ad** [comment] 2024-07-24 07:17
@onmomo Can you send your manifest file to me (maxiao@microsoft.com)? Just want to test it locally to see what's going on

**Comment by ChetanSharma-msft** [comment] 2024-08-04 07:16
Hello @onmomo - Please confirm if you have already shared the manifest file to test?

**Comment by onmomo** [comment] 2024-08-05 07:44
@ChetanSharma-msft @TechL3ad  I still need to isolate the problem in order to share a manifest. Will get back to you

**Comment by sakov-ms** [comment] 2024-08-27 19:58
Closing this for now.

**Closed by sakov-ms** 2024-08-27 19:58 UTC
Labels: teams-developer-support, needs attention, v2, outlook ios
