### ISSUE TITLE
temas sdk 2.0.0-beta.2,  taskModule.submit And dialog.submit not working on IOS 

### ISSUE THREAD

**Issue by amitShimon1983** [OfficeDev/microsoft-teams-library-js#1041] opened 2022-03-31 09:54 UTC
Hi, 
I have a tab app with a button when the user clicks I'm opening a task module, on web desktop, and on android, everything works well, but on IOS devices when I'm trying to submit the task results and close the task module the app not reacting.
`
//This is how I'm opening a task module
const taskInfo: any = {
    title: null,
    height: null,
    width: null,
    url: null,
    card: null,
    fallbackUrl: null,
    completionBotId: null,
  };

  taskInfo.url = url;
  taskInfo.title = title;
  taskInfo.height = 'large';
  taskInfo.width = 'large';
  dialog.open(taskInfo, submitHandler);
// this is how I submit the results
dialog.submit({
    message,
  });`

I tried to
add the manifest app id, did not work.
change the dialog to tasks.startTask && task.submit did not work.

**Comment by Meghana-MSFT** [comment] 2022-03-31 14:11
We are looking into this, we will update you.

**Comment by amitShimon1983** [comment] 2022-04-05 07:43
Hi sorry for the delay, this is the link I was follow, https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots?tabs=nodejs. but I'm using dialog instead task

**Comment by Meghana-MSFT** [comment] 2022-04-05 18:27
Thanks for the link, but this link does not include the beta.2 SDK?

**Comment by amitShimon1983** [comment] 2022-04-07 13:22
Hi, I didn't find any documentation about converting from v1 to v2. but inside the SDK you have a deprecation message telling you to replace from task object to dialog object

**Comment by AE-MS** [comment] 2022-04-08 23:28
FWIW deprecation message does indicate to replace task with dialog and @Meghana-MSFT the docs for dialog are [here](https://docs.microsoft.com/en-us/microsoftteams/platform/m365-apps/using-teams-client-sdk-preview?tabs=manifest-teams-toolkit%2Cjavascript#dialog-namespace)

**Comment by amitShimon1983** [comment] 2022-04-10 07:24
Hi, Thank you for that link!

**Comment by Meghana-MSFT** [comment] 2022-04-22 17:37
@amitShimon1983 - Please follow the document related to [Updating to the Teams client SDK v2 Preview](https://docs.microsoft.com/en-us/microsoftteams/platform/m365-apps/using-teams-client-sdk-preview?tabs=manifest-teams-toolkit%2Cjavascript#updating-to-the-teams-client-sdk-v2-preview). As mentioned by AE-MS everything that was working previously should work now as well. Could you please confirm if your issue is resolved now?

**Comment by Meghana-MSFT** [comment] 2022-04-28 11:33
@amitShimon1983 - Could you please confirm if your issue is resolved now?

**Comment by amitShimon1983** [comment] 2022-04-28 15:50
Hi i did all of this but I still have that problem please give me a solution.

**Comment by Meghana-MSFT** [comment] 2022-05-05 13:08
We are able to repro this issue, we have raised a bug for the same. We will keep you posted if there are any updates.

**Comment by lakhveerk** [comment] 2022-05-25 17:44
The issue has been fixed in [2.0 release](https://www.npmjs.com/package/@microsoft/teams-js/v/2.0.0) of the library which is now available and has been [published to the CDN](https://res.cdn.office.net/teams-js/2.0.0/js/MicrosoftTeams.min.js).

Please let us know if you are able to upgrade to 2.0.0, and confirm that the issue is fixed for your scenario

**Comment by Meghana-MSFT** [comment] 2022-11-23 10:32
This bug has been fixed and is publicly available now. We tested it in below version, and it works fine now.
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/81138249/203524830-14918403-1f95-49ca-a006-329a21b94180.png)

**Closed** 2022-11-29 19:01 UTC
Labels: bug, teams-developer-support, needs author feedback, status: no recent activity, v2
