### ISSUE TITLE
Module '"@microsoft/teams-js"' has no exported member 'app'

### ISSUE THREAD

**Issue by SubbaReddi** [OfficeDev/microsoft-teams-library-js#1291] opened 2022-08-05 00:32 UTC
Hi Team,
When i try to use **import { app } from '@microsoft/teams-js'**; in any react project, facing following error:
**error TS2305: Module '"@microsoft/teams-js"' has no exported member 'app'**

Using following in package.json: "@microsoft/teams-js": "^2.2.0",

To reproduce issue, you can create SPFx webpart using teams toolkit and add above line of code in .tsx file.

**Comment by sayali-MSFT** [comment] 2022-08-05 13:19
@SubbaReddi - We are looking into this we will get back to you soon.

**Comment by sayali-MSFT** [comment] 2022-08-08 15:29
@SubbaReddi -Could you please try with the below package.
package.json: "@microsoft/teams-js": "^2.0.0",

**Comment by SubbaReddi** [comment] 2022-08-08 17:35
Same issue exists with 2.0.0 as well

**Comment by sayali-MSFT** [comment] 2022-08-09 09:24
@SubbaReddi -We are able to repro that issue , We have raised bug for the same and concerned team is looking into it. We will inform you once we get any update. 
Thanks!

**Comment by sayali-MSFT** [comment] 2022-08-12 08:34
@tiennguyen1293 -Engineering team working on this issue. Currently we don’t have ETA or Update on this thread.
We will update this thread once the bug is fixed.

**Comment by AJIXuMuK** [comment] 2022-08-15 20:55
@tiennguyen1293 @SubbaReddi - you should not use custom dependency and imports when developing SPFx web part.
You must use `this.context.sdks.microsoftTeams` instead.
The example is provided in the default scaffolded project:
![image](https://user-images.githubusercontent.com/17036219/184716799-744e3bef-7da0-44d5-87cb-c16a79a1700c.png)

**Comment by SubbaReddi** [comment] 2022-08-15 23:24
@AJIXuMuK :
I am facing issue with default scaffolded project:
![image](https://user-images.githubusercontent.com/69682598/184740004-518c1227-65f3-4b0a-a46a-c9076db948aa.png)

**Comment by AJIXuMuK** [comment] 2022-08-16 17:12
@SubbaReddi - that is correct because currently SPFx support v 1.12.1, not v2.

**Comment by SubbaReddi** [comment] 2022-08-16 19:35
@AJIXuMuK : If V2 Teams sdk is not supported for SPFx, do you see if it is documented. If not, can you recommend to update in documentation?

**Comment by embailie** [comment] 2022-08-17 18:21
@SubbaReddi Thank you for the suggestion. Can you confirm you're able to use the app as intended now? If Yes, we will move forward with updating documentation and closing this issue.

**Comment by SubbaReddi** [comment] 2022-08-18 01:56
@embailie : My requirement is to use Teams SDK V2 features. As V2 is not supported with SPFx, i cannot use. So, please update limitation in documentation about the same.

**Comment by AE-MS** [comment] 2022-08-18 21:11
Thanks for letting us know; we're working on the documentation update as we speak.

In case we can also be helpful with your scenario, can you tell us more about the Teams V2 features you're looking to use? We might be able to offer a workaround in the meantime.

**Comment by SubbaReddi** [comment] 2022-08-21 22:23
@AE-MS : SPFx webpart is added to SharePoint page. Teams tab app is created for SharePoint site. Here would like to understand whether user is accessing SharePoint page in browser or accessing through teams tab app.

**Comment by embailie** [comment] 2022-08-24 17:54
The documentation has been updated to clarify that when using SPFx, custom versions of Teams JS SDK is not supported.

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/build-for-teams-considerations

**Comment by AE-MS** [comment] 2022-08-27 00:56
> @AE-MS : SPFx webpart is added to SharePoint page. Teams tab app is created for SharePoint site. Here would like to understand whether user is accessing SharePoint page in browser or accessing through teams tab app.

Ah, okay. Unfortunately, there is no "official" way to do this in teamsJs pre-2.0, which isn't helpful for you since you are limited by the version SPFx currently supports. (The 2.0+ way of doing it is described in issue #1150 )

**Closed** 2022-10-11 11:20 UTC
Labels: bug, teams-developer-support
