### ISSUE TITLE
Detection of whether react app is running in Teams or Web browser?

### ISSUE THREAD

**Issue by lazycipher** [OfficeDev/microsoft-teams-library-js#515] opened 2021-02-25 09:34 UTC
Currently, I'm trying to get context using getContext() and trying to decide whether it's running in Teams or Browser.
Is there any other better way to move ahead with this?

Also, is there any forum dedicated to this MSTeams Development?

**Comment by Mamatha-MSFT** [comment] 2021-02-28 06:36
Hi @lazycipher, microsoftTeams.getContext() works only inside teams and returns null on a browser. 
`microsoftTeams.initialize()
  microsoftTeams.getContext((context) => {
          if (context === null || context === undefined) {.......}}`
Could you please try this?

**Comment by lazycipher** [comment] 2021-02-28 06:46
Hi @Mamatha-MSFT,
I've tried this thing already.
Actually, what happens is, the callback doesn't get executed on browser.
It only executes when trying to access from any teams client.

**Comment by lazycipher** [comment] 2021-02-28 19:20
@Mamatha-MSFT, Please refer to this code once -> https://stackblitz.com/edit/react-cuadoi?file=src%2FApp.js

**Comment by Mamatha-MSFT** [comment] 2021-03-01 12:04
@lazycipher Could you please try this and let me know if the issue still persists.
`var teamsInitialized = false;
microsoftTeams.initialize(() => {
  teamsInitialized = true;
});

setTimeout(() => {
   if(teamsInitialized) {
    // teams running
   } else {
    // otherwise
   }
}, 1000);'

**Comment by Mamatha-MSFT** [comment] 2021-03-03 04:50
@lazycipher please let us know if your issue has been resolved.

**Comment by ydogandjiev** [comment] 2021-03-03 05:17
@lazycipher, your best option is to add an explicit QSP to the URLs that you load within Teams (e.g. `&inTeams=true`). 

If that doesn't work for your scenario then your best bet is to use the `checkInTeams` helper that Wictor Wilén implemented in his super awesome helper library:
https://github.com/wictorwilen/msteams-react-base-component#additional-helper-methods

Do note that this helper depends on some internal details of the way Teams hosts apps which might not hold true indefinitely into the future.

**Comment by lazycipher** [comment] 2021-03-03 08:32
Got it! I'll implement and test this in the next big release of the app.
Currently used something else as a workaround.
Thank you @Mamatha-MSFT, @ydogandjiev.

**Comment by lazycipher** [comment] 2021-03-03 08:34
Though, Won't it be better to have the callback executed irrespective of it being in Teams or not?
It can handle many scenarios quite easily. @ydogandjiev

**Comment by ydogandjiev** [comment] 2021-03-11 16:42
@lazycipher, how would the callback execute when not in Teams? All SDK APIs are simply a translation layer that serializes the calls your app makes and sends them to Teams for handling. If Teams isn't there then the APIs do not work.

**Comment by enak** [comment] 2021-03-12 03:06
> @Mamatha-MSFT, Please refer to this code once -> https://stackblitz.com/edit/react-cuadoi?file=src%2FApp.js

`microsoftTeams.getContext` will never call the callback in the example that you provide because the Teams parent window (or Teams App) does not exist and therefore never calls the callback. It also errors out since initialize was not called: `Error: The library has not yet been initialized.`.

Following is from https://github.com/OfficeDev/microsoft-teams-library-js/blob/master/src/public/publicAPIs.ts#L159

    sendMessageToParent('getContext', (context: Context) => {
      if (!context.frameContext) {
        // Fallback logic for frameContext properties
        context.frameContext = GlobalVars.frameContext;
      }
      callback(context);
    });

Instead of having three states: TEAMS, NOT_TEAMS, and DONT_KNOW_YET, we only currently have two since NOT_TEAMS is unreachable. Here is a [code example](https://codesandbox.io/s/gallant-bush-p25lz?file=/src/App.js) that explains the problem.

**Comment by enak** [comment] 2021-03-13 21:44
This issue is a duplicate of #469.

**Comment by olafur164** [comment] 2021-11-08 10:51
We use:
```
const userAgent = window.navigator.userAgent.toLowerCase();
const isTeamsUserAgent = userAgent.includes('teamsmobile');

export const isInTeams = () => isTeamsUserAgent || window.parent !== window;
```

**Comment by v-chetsh** [comment] 2021-12-06 08:05
@lazycipher - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by v-chetsh** [comment] 2021-12-06 08:09
We are closing this issue because it is a duplicate of this issue: https://github.com/OfficeDev/microsoft-teams-library-js/issues/469
Please feel free to reopen it, if required.

**Closed by v-chetsh** 2021-12-06 08:09 UTC
Labels: teams-developer-support, needs triage :mag:
