### ISSUE TITLE
Cannot submitTask with a result parameter on Android or IOS

### ISSUE THREAD

**Issue by BrendanAndrade** [OfficeDev/microsoft-teams-library-js#455] opened 2020-11-23 17:50 UTC
This was working properly on October 26.

**Reproduction Steps:**
Open a html/css task module from a deeplink within a message in a Channel through the Teams IOS or Android app. 

Using the teams-js library call:
`microsoftTeams.initialize();`
`microsoftTeams.tasks.submitTask( {foo: 'bar'} ); //or microsoftTeams.task.submitTask( {foo: 'bar'}, 'appId' );`

The task does not submit and the Teams displays 'An error occurred'. This error occurs with teams-js 1.7 and 1.8. Android Teams app version 1416/1.0.0.2020111001. Tested with Android Version 10 and 6.0.1.

Calling microsoftTeams.task.submitTask(null) does correctly close the task without submitting.

**Additional info:** With desktop app, getContext in the html/css task module returns:

> {
  "locale": "en-us",
  "theme": "default",
  "entityId": "",
  "subEntityId": "",
  "isFullScreen": false,
  "sessionId": "foo",
  "chatId": "",
  "meetingId": "",
  "hostClientType": "desktop",
  "tenantSKU": "unknown",
  "jsonTabUrl": "microsoft-teams-json-tab.azurewebsites.net",
  "userLicenseType": "Unknown",
  "appSessionId": "foo",
  "isMultiWindow": false,
  "appIconPosition": 79,
  "frameContext": "task",
  "parentMessageId": "",
  "isTeamArchived": false,
  "teamType": 0,
  "userTeamRole": 0,
  "channelRelativeUrl": foo",
  "channelId": "foo",
  "channelName": "General",
  "channelType": "Regular",
  "defaultOneNoteSectionId": "",
  "groupId": "foo",
  "teamId": "foo",
  "teamName": "App Test Team",
  "teamSiteUrl": "foo",
  "teamSiteDomain": "foo",
  "teamSitePath": "foo",
  "ringId": "general",
  "tid": "foo",
  "loginHint": "foo",
  "upn": "foo",
  "userPrincipalName": "foo",
  "userObjectId": "foo"
}

On Android it returns: 

> {
  "appSessionID": "foo",
  "channelId": "",
  "channelName": "",
  "channelRelativeUrl": "",
  "channelType": "",
  "chatId": "",
  "entityId": "",
  "frameContext": "content",
  "groupId": "",
  "hostClientType": "android",
  "isFullScreen": false,
  "isTeamArchived": false,
  "locale": "en-us",
  "loginHint": "foo",
  "parentMessageId": 0,
  "ringId": "general",
  "sessionId": "foo",
  "subEntityId": "",
  "teamId": "",
  "teamName": "",
  "teamSitePath": "",
  "teamSiteUrl": "",
  "teamType": 0,
  "tenantSKU": "unknown",
  "theme": "default",
  "tid": "foo",
  "upn": "foo",
  "userLicenseType": "",
  "userObjectId": "foo",
  "userPrincipalName": "foo",
  "userTeamRole": 1
}

**Comment by Trinetra-MSFT** [comment] 2020-11-23 19:33
We are checking this issue, I will get back to you in sometime.

**Comment by phpmaps** [comment] 2020-11-26 18:36
@Trinetra-MSFT  My team has also encountering this issue with submitTask on Android and iOS.  With regards to our teams-js library, we are using v1.8.0 of @microsoft/teams-js.

The same repro steps apply : 

```
microsoftTeams.initialize();
microsoftTeams.tasks.submitTask( {foo: 'bar'} ); //or microsoftTeams.task.submitTask( {foo: 'bar'}, 'appId' );

```

Then after the cursor completes submitTask (and popup goes away) our Teams bot channel endpoint at ```/api/messages``` exposed via the latest botbuilder JS libs, 4.11.0,  never raises the ```handleTeamsTaskModuleSubmit()``` life cycle method when using Teams on Android or IOS.

@Wajeed-msft @Trinetra-MSFT  is ```submitTask()``` expected to raise the botbuilder  ```handleTeamsTaskModuleSubmit()``` method from Android and IOS devices?  

 From research, the handler is called as expected on Teams desktop clients (Win and Mac) and in Teams browser clients.   

Please feel free to reach out if you have questions.   This issue and the disappearing chat tab issue https://github.com/microsoft/botbuilder-js/issues/2894 are pain points and we are looking for fixes or workarounds, if any are available.

**Comment by BrendanAndrade** [comment] 2020-12-16 20:43
Hi, any update on this issue? Thank you.

**Comment by Trinetra-MSFT** [comment] 2020-12-18 10:34
@BrendanAndrade , This is an Bug for iOS I tested, submit for task Module is not working. I will file a Bug for this now,

**Comment by BrendanAndrade** [comment] 2020-12-18 16:42
@Trinetra-MSFT it also seems to be a bug for Android

**Comment by Nikitha-MSFT** [comment] 2021-01-21 12:52
@BrendanAndrade - Bug is Resolved now, we have tested this at our end, could you please also check and confirm?
The issue is with the Teams client which is fixed now.

**Comment by amitShimon1983** [comment] 2022-03-31 09:34
hi in which version the bug was fixed?

**Comment by Meghana-MSFT** [comment] 2022-11-09 07:40
Checked this again on latest version: 1416/1.0.0.2022395202 and it works fine.

**Comment by Wajeed-msft** [comment] 2022-11-23 09:24
Please feel free to re-open this issue if you are still facing it.

**Closed by Wajeed-msft** 2022-11-23 09:24 UTC
Labels: bug, teams-developer-support, needs author feedback, status: no recent activity
