### ISSUE TITLE
Increase the height and width of the config tab

### ISSUE THREAD

**Issue by adityap31** [OfficeDev/microsoft-teams-library-js#1399] opened 2022-10-13 11:33 UTC
How can we increase the height and width of the config tab?

<img width="563" alt="image" src="https://user-images.githubusercontent.com/2426723/195585401-fbfcb9e8-bdd9-4843-968d-d8a92077c742.png">

**Comment by Nivedipa-MSFT** [comment] 2022-10-13 11:59
@adityap31 - We cannot increase the height and width of the config tab. This is by design.

**Comment by adityap31** [comment] 2022-10-13 12:38
Thanks @Nivedipa-MSFT However, we would like to achieve something like the below image.

<img width="762" alt="image" src="https://user-images.githubusercontent.com/2426723/195597881-0c4bbe7e-fae1-4f7a-9525-33b5f16b4cc2.png">

**Comment by nwojod-MSFT** [comment] 2022-10-14 21:20
@adityap31 thank you for raising this issue. Although this is not supported now, we believe this will be a good feature to have. The team will review it, the level of work required, and prioritize accordingly. Because of the volume of requests we receive, we are unable to promise when this feature will be implemented. However, we will provide an estimate on this thread as soon as we have a committed timeline. Thank you for your patience.

**Closed** 2023-08-22 15:28 UTC
Labels: request: feature, teams-developer-support
