### ISSUE TITLE
JWT token does not contain scope permissions.

### ISSUE THREAD

**Issue by Thommurgia** [OfficeDev/microsoft-teams-library-js#1668] opened 2023-03-24 12:31 UTC
I'm trying to get authenticate my user in a teams application, I need this token to use microsoft graph API and then this token must contains some autorisation, like User.Read, or chat.ReadWrite.

I'm using @Microsoft/teams-js, first the method app.initialize() and then authentication.getAuthToken().

I'm receiving my token correctly but without the right permissions that are setup in my azure application dashboard.

I tried many things but nothings helped. Does someone have advices or some explanations on how am i suposed to ask for these permissions ?

**Comment by AE-MS** [comment] 2023-03-24 17:26
Hi @Thommurgia,

Unfortunately due to current limitations with AAD protocols and libraries, there's no way to directly get a token in your Teams app with the scopes you need (like Chat.ReadWrite). You have to request a token from Teams, and then use the Azure AD on-behalf-of (OBO) flow to exchange the token you received for a different token containing the scopes needed to use the Microsoft Graph API. There is documentation describing how to implement the OBO flow in the [Acquire access token for MS Graph](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-graph-api?tabs=dotnet#acquire-access-token-for-ms-graph) section of the identity page.

Is this the sort of thing you're looking for?

We know that it is inconvenient to jump through these hoops just to make MS Graph calls -- we're actively working on a feature that will make this dramatically simpler. However, there's a lot of complexity involved across multiple products, so we don't have anything to offer quite yet, but we're working hard to make this simpler.

**Comment by Thommurgia** [comment] 2023-03-25 16:19
Hello @AE-MS,

Ok, i understand, I've read things about the Authentication.authenticate method but I don't really understand the difference between this one and getAuthToken().
I suppose the authenticate method won't help me to get a Token with the right permissions ?

Another solution i tried was to use MSAL (Microsoft Authentication Library). This library allow me with the method loginPopup() and its configuration to get my token with th right permissions. Unfortunately, this library isn't working with teams desktop for security reasons and teams desktop blocking pop-ups.
I could "bypass" this problem adding asyncPopup: true in MSAL configuration. Now it open a new browser page as a pop-up.
But, this library works with a redirect URI, if I use a localhost redirection uri it won't redirect me to teams desktop but will open teams in browser. And if I use a deeplink to the teams application as a redirect URI, this will reload the application and then restart the authentication flow then cycle.

It's strange that I can't get permissions even if I setup my Azure Active Directory with the permissions in "exposed API" page, do you know where this configuration is used if not in my case ?

Hope you will find a solution, it would simplify a lot these case study.

Have a nice day
Thomas

**Comment by iambmelt** [comment] 2023-03-30 22:36
@Thommurgia 

There are two _possible_ ways to authenticate your user and acquire a token for Microsoft Graph.

1. The first way uses the `getAuthToken()` method on teams.js to acquire a token _for your mid-tier_, so that you can perform an OBO exchange against AAD to acquire a token for Graph. **`getAuthToken()` cannot acquire a token directly for Graph for you.** This is the _most preferred method_ of accessing Graph from you application, because this flow fully supports Intune and Conditional Access policies, support which most enterprise grade applications need. The documentation [here ](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-overview)(if you walk through it sequentially) will guide you on the mid-tier registration process, as well as what client-side code is needed to call it. You can find [code samples for this pattern here](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-code#code-samples).
2. The second way (less preferred, due to the Intune & Conditional Access restrictions [mentioned here](https://learn.microsoft.com/en-us/microsoftteams/troubleshoot/tabs/tabs-dont-work-after-enabling-conditional-access)) is to use MSAL.js or one of its helper wrappers like [Teams Msal2 Provider](https://learn.microsoft.com/en-us/graph/toolkit/providers/teams-msal2?tabs=ts). In this pattern, you will need to register a [single page application](https://learn.microsoft.com/en-us/azure/active-directory/develop/single-page-app-quickstart?pivots=devlang-angular) and use the provided `acquireToken()` & `ssoSilent()` methods to acquire tokens from Graph directly. This technique lets you avoid provisioning a mid-tier service at the sacrifice of not fully supporting Intune and Conditional Access policies today.

**Comment by Thommurgia** [comment] 2023-03-31 06:54
@iambmelt 
![image](https://user-images.githubusercontent.com/56476727/229044495-d6b58630-b0e5-4420-b1d9-47de80410984.png)
If I'm understanding it correctly I'm stuck at the fifth state.
I have a token but it doesn't contains the right permissions.
Then I can't use this token for Graph API, 

I think that I'm missing the moment I ask for permissions while a pop-up display asking for permissions, like this one. 
![image](https://user-images.githubusercontent.com/56476727/229045728-142ad842-848b-4830-b831-941cbb533412.png)

**Comment by iambmelt** [comment] 2023-03-31 17:04
@Thommurgia 

Correct, this is by design. Please see my comment above ^^
> getAuthToken() cannot acquire a token directly for Graph for you.

Teams.js' `getAuthToken()` can only acquire a token for your mid-tier app. Your mid-tier, not the client side running in the user's browser, must be used to call Graph (per the sequence diagram shared above).

The flow is the following
- Call `getAuthToken()` on the client side
- Send the access token returned by `getAuthToken()` to your mid-tier
- Use the [OBO protocol ](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow#first-case-access-token-request-with-a-shared-secret)to exchange the token you sent to your mid-tier for an access token for Graph
- Call Graph from the mid-tier with the access token returned in the previous step
- Send the data retrieved from Graph back to the client.

The reason you must call Graph from your mid-tier is because a `client_secret` is needed to prove the identity of your application. Because the token returned to your client-side by `getAuthToken()` was fetched by Teams' application id, you must send this token to your mid-tier and perform an OBO flow in order to use your own application's identity to acquire a token from Graph.

If you're still jammed up, I would suggest checking out [Single sign-on (SSO) in Microsoft Teams tabs with Azure Active Directory](https://www.youtube.com/watch?v=kruUnaZgQaY) and seeing if this clarifies.

**Comment by sayali-MSFT** [comment] 2023-06-29 03:34
Could you please confirm if your issue has resolved with provided suggestions or still looking for any help?

We are closing this issue for now, please feel free to reopen it, if required.

**Closed** 2023-06-29 08:29 UTC
Labels: teams-developer-support
