### ISSUE TITLE
Channel App back button does it wrong on iOS

### ISSUE THREAD

**Issue by BerndGewehr** [OfficeDev/microsoft-teams-library-js#1442] opened 2022-11-06 16:39 UTC
When my web app tab shall be left, the teams back button in iOS does not go back to the channel list of apps, it goes like browser history back including login pages and raises some errors this way.

In my example, we created a simple app that just shows the getcontext() result in a web page after AAD SAML authentication.

Every time the page reloads, I just hit the back button until I am finally back in the channels app list. 

https://user-images.githubusercontent.com/21081707/200183280-2a53abfb-8217-4376-a20c-ce0c7232593e.MOV

Users would prefer just to go back to the channel app list with one tap of the back button.

Are we doing something wrong?

**Comment by Nivedipa-MSFT** [comment] 2022-11-07 06:11
@BerndGewehr - Could you please share which version you are using for teams-js-sdk?

**Comment by BerndGewehr** [comment] 2022-11-11 06:03
I have upgraded all parts of the solution to the latest releases. No change to the behavior.

Does your web app use SSO with AAD? Ours does. Please would you give that another try?

The back button behaves like a browser history back while it should better behave like "press here once to leave the app and go back to the app list" - which is not the case at least on iOS.

Took the Store app for Huddo boards this timehttps://user-images.githubusercontent.com/21081707/201274227-4e763c7a-3551-4ee9-9191-e6683687b4c4.MOV

**Comment by Nivedipa-MSFT** [comment] 2022-11-16 04:03
@BerndGewehr - We will test this again using SSO with AAD and update you soon.

**Comment by Nivedipa-MSFT** [comment] 2022-11-16 09:24
@BerndGewehr - We have tested this using Huddo boards and we are able to repro this issue at our end.
We have raised a bug for the same. We will let you know once we have any updates on it.

**Comment by NickyTope** [comment] 2022-11-17 01:37
Nicky from Huddo Boards here.

This looks like an issue with the history implementation?
It appears like the back button is routing to "/" in this case we detect the empty route and send the user to "/my". This is done with a `<Navigate to="/my" replace />` from react-router-dom v6.4.3 which is supposed to replace the history entry but I can see how it could create this situation if the replace does not work as expected.

**Comment by BerndGewehr** [comment] 2022-11-17 05:40
@NickyTope we do not donallnthis in our code an run into the same issue, see first video from our test tool. Not your fault would I say.

**Comment by Nivedipa-MSFT** [comment] 2023-01-05 06:35
This is an expected behaviour as the back button would navigate the web page history
You can intercept the back button via the registerBackButtonHandler API
https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/design/personal-apps#configure-back-button

For achieving closing the App functionality, could you please raise a feature request here:
[Microsoft Teams Community](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472)

**Comment by BerndGewehr** [comment] 2023-01-05 08:15
https://feedbackportal.microsoft.com/feedback/idea/c5aec6ae-d08c-ed11-a81b-6045bdaf6a9e

**Comment by Wajeed-msft** [comment] 2023-03-06 11:38
Closing this from list of issues as feature idea is raised on [feedback portal](https://feedbackportal.microsoft.com/feedback/idea/c5aec6ae-d08c-ed11-a81b-6045bdaf6a9e).

**Closed by Wajeed-msft** 2023-03-06 11:38 UTC
Labels: bug, request: feature, teams-developer-support
