### ISSUE TITLE
SDK login not working in New Teams for GCC High customers

### ISSUE THREAD

**Issue by Happy202121** [OfficeDev/microsoft-teams-library-js#2329] opened 2024-05-16 21:29 UTC
Hello, 

We discovered that, for GCC High customers, the Teams JS SDK authentication module in is not working the same with New Teams as it does with Teams Classic.

In Teams Classic, the GCC High user opens our app, clicks a sign-in button, then an embedded browser opens to handle the authorization and authentication.

In New Teams, the GCC High user opens our app, clicks a sign-in button, then the default browser opens a new tab to try and handle the authorization and authentication. The resulting request has the wrong cookies and fails as a result.

Here's what we're using:

microsoftTeams.authentication.authenticate({
  url: loginUrl,  width: 820,  height: 620,  successCallback: function(result) {
    console.log('Login Successfully: ' + JSON.stringify(result));    that.reloadUserContext();  },  failureCallback: function(reason) {
    console.log('Login failed: ' + reason);

**Comment by jekloudaMSFT** [comment] 2024-05-16 22:40
Hi @Happy202121, I'm sorry you've run into this. Can you please share the microsoft-teams-library-js version your app uses?

**Comment by KaratLee** [comment] 2024-05-20 03:04
@jekloudaMSFT @Happy202121 microsoft-teams-library-js version: @microsoft/teams-js@1.8.0

**Comment by jekloudaMSFT** [comment] 2024-05-20 17:22
Hi @Happy202121 @KaratLee, I haven't been able to reproduce this issue with my own Teams application. Could you please follow the instructions [here](https://github.com/OfficeDev/microsoft-teams-library-js/wiki/TeamsJS-Logging#enabling-logging) to enable client side logging and then reply to this with the client logs you see when the auth page is opened in the browser? Can I also know if you receive a `Login Successfully: ` or `Login failed: ` log when this occurs?

**Comment by KaratLee** [comment] 2024-05-21 01:23
@jekloudaMSFT We got a prompt that the URL could not be opened: Login failed: URL was unable to be opened in embedded browser.
Cc @Happy202121 
<img width="1638" alt="image" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/37133480/23ca83e2-4fbd-4d74-859f-6ae39b2acce8">

**Comment by KaratLee** [comment] 2024-05-22 01:27
@jekloudaMSFT This is the installation package used by Microsoft gov environment customers. If you use the Microsoft gov environment account to access the Zoom for GCCH app on the Microsoft Teams new client, you should be able to see this problem.

[Zoom for GCCH.zip](https://github.com/OfficeDev/microsoft-teams-library-js/files/15396946/Zoom.for.GCCH.zip)

**Comment by jekloudaMSFT** [comment] 2024-05-22 16:30
Hi @KaratLee, I'm still investigating this issue and will raise it with Teams. Based on the logs, I suspect the issue may be a CSP violation causing the site to open in browser vs a new Teams window. Since the [Teams URL for GCC high](https://learn.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-u-s-government-gcc-high-endpoints?view=o365-worldwide#skype-for-business-online-and-microsoft-teams) is gov.teams.microsoft.us, does gov.teams.microsoft.us need to be added to the frame-ancestors allowed by https://applications.zoomgov.com?

**Comment by KaratLee** [comment] 2024-05-23 02:12
@jekloudaMSFT Thanks for your response. We'll try your suggestions, but this process works fine in Microsoft Teams classic

**Comment by KaratLee** [comment] 2024-05-31 05:11
> Hi @KaratLee, I'm still investigating this issue and will raise it with Teams. Based on the logs, I suspect the issue may be a CSP violation causing the site to open in browser vs a new Teams window. Since the [Teams URL for GCC high](https://learn.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-u-s-government-gcc-high-endpoints?view=o365-worldwide#skype-for-business-online-and-microsoft-teams) is gov.teams.microsoft.us, does gov.teams.microsoft.us need to be added to the frame-ancestors allowed by https://applications.zoomgov.com?

@jekloudaMSFT We followed your suggestion, but the problem is not solved. Can you help check it? 

![Screenshot2024_05_31_130344](https://github.com/OfficeDev/microsoft-teams-library-js/assets/37133480/d5ca7da4-5d9e-4d1b-b95c-32de5f50a8cb)

**Comment by KaratLee** [comment] 2024-06-03 01:26
@jekloudaMSFT Any updates?

**Comment by KaratLee** [comment] 2024-06-05 01:41
@jekloudaMSFT 
The 500 error appears before clicking login, so it should not be related to the current problem.
<img width="496" alt="image" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/37133480/8eeccb9c-438c-4e8e-80e3-9d6d9f386f8a">

**Comment by jekloudaMSFT** [comment] 2024-06-12 20:15
Hi @KaratLee, thanks for your patience. I was able to repro the issue with a test app in the GCCH environment. I'm raising this with the Teams team and will provide another update soon

**Comment by KaratLee** [comment] 2024-06-13 01:18
Thanks, looking forward to the update notification.
Cc. @Happy202121

**Comment by jekloudaMSFT** [comment] 2024-06-24 23:17
Hi @KaratLee @Happy202121, the Teams desktop team is working on a fix for this. I'll let you know when we have an ETA on the fix being available.

**Comment by Happy202121** [comment] 2024-07-11 16:41
Thanks @jekloudaMSFT, do you know which Teams client version will include this fix?

**Comment by KaratLee** [comment] 2024-07-25 01:43
@jekloudaMSFT Any update?

**Comment by AE-MS** [comment] 2024-07-25 22:40
> @jekloudaMSFT Any update?

Sorry for the delayed reply, jekloudMSFT is on vacation. ✈️🌴😎

In the meantime, I was able to verify that there is a fix for this in the Teams build that is being rolled out in August. It should be publicly available on or around August 22nd.

**Comment by Happy202121** [comment] 2024-08-28 21:14
Hi @jekloudaMSFT and @AE-MS , we had our customer update teams and try again, but it seems the same issue is occurring. Could you confirm if this fix was released as planned?

**Comment by jekloudaMSFT** [comment] 2024-08-28 22:14
Hi @Happy202121, can you please share the client version that was tested? I just checked and the rollout is at 40% right now, so it's possible the fix is not available for your customer yet

**Comment by Happy202121** [comment] 2024-09-03 19:22
Thanks @jekloudaMSFT , here's the info you requested: 
Teams version: 24193.1805.3040.8975
Client version: 49/24071128825

**Comment by jekloudaMSFT** [comment] 2024-09-03 21:31
Thank you, @Happy202121, 24080212008 is the version containing the fix, rollout is at 50% in GCCH now

**Comment by jekloudaMSFT** [comment] 2024-09-05 17:35
Hi @Happy202121, it looks like the rollout is now at 100%, can you please try updating and logging in again?

**Comment by Happy202121** [comment] 2024-09-30 17:45
Confirmed this is fixed now. Thanks for your help @jekloudaMSFT! :)

**Closed** 2024-10-01 21:31 UTC
Labels: teams-developer-support
