### ISSUE TITLE
Access window.top 

### ISSUE THREAD

**Issue by saiumesh-apty** [OfficeDev/microsoft-teams-library-js#715] opened 2021-11-15 17:57 UTC
Hello There!

we have an application which accesses window.top. we tried with personal tabs and task modules but always get the cross-origin issue. is there any way to access window.top and add a new HTML element using this package? 

was wondering if there's any function which returns window top

Thanks.

**Comment by sayali-MSFT** [comment] 2021-11-16 05:51
@saiumesh-apty  we are looking into the issue, We will update you.

**Comment by MarcinJuraszek** [comment] 2021-11-18 05:01
@saiumesh-apty Are you trying to add HTML elements to the Teams UI? That's not possible, and that's by design.

Can you tell us more about what you're trying to accomplish?

**Comment by saiumesh-apty** [comment] 2021-11-18 09:25
Hello, @MarcinJuraszek Thanks for the response. We have React application and want to render in all the pages of MS Teams and show some tooltips next to some of the Teams elements. for example like Grammarly.

**Comment by MarcinJuraszek** [comment] 2021-11-18 18:32
This is not a supported scenario.

**Comment by sayali-MSFT** [comment] 2021-11-19 10:44
We are closing this issue for now, Please feel free to reopen it, if required.

**Closed** 2021-11-19 10:45 UTC
Labels: teams-developer-support, needs triage :mag:
