### ISSUE TITLE
Deeplink with pages.navigateToApp() not working in Office and Outlook (v2 SDK)

### ISSUE THREAD

**Issue by TDE-Communardo** [OfficeDev/microsoft-teams-library-js#1247] opened 2022-07-14 11:27 UTC
Hi team,

we recently updated our Teams solution to use the new v2 SDK. While testing the new feature to use the app also in Office and Outlook we have noticed that the new **pages.navigateToApp(...)** functionality isn't working in the new environments. The same code works fine when the app is used in Teams.

### Error Message
**Office:** `Error in processing request : pages.navigateToApp with error Unhandled message`
**Outlook:** No error / warning visible

### Code-sample
Code used to navigate to a personal tab with the entityId "dashboard" from another personal tab inside the same app:

```
import { pages } from "@microsoft/teams-js";

...

if (pages.isSupported()) {
      pages.navigateToApp({appId: appId, pageId: "dashboard"});
}
```

### Version
` "@microsoft/teams-js": "^2.0.0" `

**Comment by Nivedipa-MSFT** [comment] 2022-07-15 06:02
@TDE-Communardo - Please let us know if you have any other query or shall we close this issue?

**Comment by TDE-Communardo** [comment] 2022-07-15 07:37
Hi @sbtron thanks for your response!
I verified the appids in all environments and it's the same on every host (the ones displayed in the urls you mentioned are the same as on the Teams app). 
The current app is also not published at the moment so existing versions should not interfere.
We are also using the latest version of Teams Toolkit which creates different AppIds for every environment. I was able to reproduce this issue with a locally hosted app (debug in Office / Outlook is available there) and also with an Azure-hosted dev environment (both have different AppIds). I also tried a clean install by removing the dev environment app entirely from the tenant and made a fresh install with the generated Teams app package.
We are also able to reproduce this issue on our centrally deployed test environment (separate Tenant, Azure-hosting and AppId).

Thanks in advance!

**Comment by TDE-Communardo** [comment] 2022-07-15 08:52
One additional remark:

I've checked the AppId used in our code again and it was the external AppId that's also written down in the app manifest. However that's not the ID displayed in the urls mentioned above.

It seems that it doesn't matter whether you are using the external appId or the real appId in the pages.navigateToApp(...) function. 
In Teams both AppIds make the navigation work properly. In Office and Outlook it's still the same result for both IDs: navigation is not working.

**Comment by Nivedipa-MSFT** [comment] 2022-07-20 12:03
@TDE-Communardo - We will try to repro it and let you you know the updates.

**Comment by Nivedipa-MSFT** [comment] 2022-07-26 13:25
@TDE-Communardo - We are able to repro this issue and we have raised a bug for it.

We will let you know once we get updates on it.

**Comment by nwojod-MSFT** [comment] 2022-08-02 20:21
@TDE-Communardo the team is working on a fix. No ETA yet. Will update this thread once there is a fixed ETA.

**Comment by nwojod-MSFT** [comment] 2022-08-08 14:57
@TDE-Communardo the ETA for a fix is end of August. Once the fix is rolled out, we will update this post.

**Comment by rolandbodenstaff** [comment] 2022-09-17 17:33
@nwojod-MSFT any update on this?

**Comment by nwojod-MSFT** [comment] 2022-09-19 15:25
@rolandbodenstaff, ETA got delayed a bit to accommodate few other changes. I will update this thread as soon as the changes are in effect. Thanks.

**Comment by nwojod-MSFT** [comment] 2022-10-19 21:20
@rolandbodenstaff apologies for the delay. The fix has been implemented, however, the team is running final tests. The team will roll out the fix in the coming days.

**Comment by Nivedipa-MSFT** [comment] 2022-11-17 11:21
@TDE-Communardo - We are checking the status of fix release with the engineering team. We will let you know once we have any update.

**Comment by Nivedipa-MSFT** [comment] 2022-12-15 09:09
@TDE-Communardo - The bug has fixed now. Could you please test this and confirm?

**Comment by sohamzycus** [comment] 2023-01-05 10:57
Can you please let me know in which version the bug has been fixed ? We're facing similar issue.

Our use case - 
1. Redirecting to Chat context from Tab with the click of a button.
2.  Tab contains button called 'See actions' - on clicking it, user should be redirected to Chat window. 
3. We're using @microsoft/teams-js  package with a call to pages.navigateToApp() functions - refer attached screenshot
4. It doesn't throw any error, just comes out of the function.

Can you please check and point us to the solution ? Thank you.

**Comment by Nivedipa-MSFT** [comment] 2023-01-05 12:13
@sohamzycus - We have tested this on Office version : 18.2210.1203.0 
Could you please share what error you are getting in console?
On which platform (Teams, Outlook, Office) are you facing this issue?
Are you using app ID which is retrieved from Teams Admin Center for deeplink?
Could you please share the screen recording of your issue to understand the scenario?

**Comment by sohamzycus** [comment] 2023-01-05 12:30
> 

@Nivedipa-MSFT  - Please find answers below -
Could you please share what error you are getting in console?
>> No error. It just breaks comes out of the ' if-else' block completely

On which host (Teams, Outlook, Office) are you facing this issue?
>> Teams

Are you using app ID which is retrieved from Teams Admin Center for deeplink?
>> Yes

Could you please share the screen recording of your issue to understand the scenario?
>> Will share soon.

**Comment by ChetanSharma-msft** [comment] 2023-01-16 06:57
Hello @sohamzycus - Thanks for sharing the information.
We will further investigate your issue and let you know the updates.

**Comment by AE-MS** [comment] 2023-01-17 19:53
@sohamzycus thanks for providing those extra details. To ensure that I can reproduce and investigate your specific use case, can you provide some more information about how you're looking to use a link to chat? You mention that you are looking to redirect to chat context from a tab -- are you looking to create a new chat with some set of users? Or navigate to a specific channel conversation?

From the video you provided (thank you for recording it!) -- it looks like you are using the `pages.navigateToApp` method to try and open the chat. What parameters/data are you providing it? I can see you're providing an app id, but I can't quite tell what comes after that. Can you provide a sample example here of the parameters/data you are passing? You don't have to provide the exact data, in case it's confidential, just something representative of what you're passing.

Thank you!

**Comment by Nivedipa-MSFT** [comment] 2023-02-10 08:40
@sohamzycus - Could you please share below details:
1. Are you looking to create a new chat with some set of users? Or navigate to a specific channel conversation?
2. What parameters/data are you providing to pages.navigateToApp?
3. Can you provide a sample example here of the parameters/data you are passing?

**Closed** 2023-02-16 19:01 UTC
Labels: bug, teams-developer-support, needs author feedback, status: no recent activity, v2
