### ISSUE TITLE
`failureCallback` is defined as optional, yet the library throws errors if it is not provided.

### ISSUE THREAD

**Issue by ascott18** [OfficeDev/microsoft-teams-library-js#549] opened 2021-04-20 22:20 UTC
This library throws errors due to its attempts to call `failureCallback` during authentication when no `failureCallback` has been provided. Per the declared types of this project, `failureCallback` is optional.

This is allowed to happen because this project uses weak Typescript configuration - namely, strict mode is not enabled and only a handful of individual strictness flags are enabled. `strictNullChecks` is among those strictness flags that are disabled in this project. Please enable full strict mode (https://www.typescriptlang.org/tsconfig#strict) and fix all the errors that it surfaces.

Call stack:
```
TypeError: n.failureCallback is not a function
    at failureCallback (webpack:///node_modules/@microsoft/teams-js/dist/MicrosoftTeams.min.js:1:36439)
    at apply (webpack:///node_modules/@microsoft/teams-js/dist/MicrosoftTeams.min.js:1:2816)
    at u (webpack:///node_modules/@microsoft/teams-js/dist/MicrosoftTeams.min.js:1:6944)
    at processMessage (webpack:///node_modules/@microsoft/teams-js/dist/MicrosoftTeams.min.js:1:37798)
```

**Comment by ChetanSharma-msft** [comment] 2022-11-06 10:50
Hello @ascott18 - Sorry for delay in response.
Could you please confirm whether you are still facing this issue or is it resolved?

**Comment by AE-MS** [comment] 2022-11-08 06:27
Hi @ascott18, thanks for reporting this issue. I didn't see an example of the problematic code in your original post, so I did a code inspection on the current version of the teams-js library to see all the uses of the `failureCallback`. Today, it seems that each attempt to call the `failureCallback` is guarded by a check to ensure that it's valid before calling it. Obviously your original report is from a very long time ago, so the issue could have coincidentally been fixed in the meantime.

Do you recall the code you were using when you ran into this problem? I can use that to validate that the issue is indeed fixed and that I'm not overlooking a particular scenario.

Also, totally agree with your point about enabling `strict` in the TypeScript compiler flags. Unfortunately, that's one of those things that is difficult to enable once you've let the codebase grow unchecked without it. We're in the process of working through enabling `strictNullChecks` first, then working through the other "strict" checks to eventually enable be able to enable that flag.

**Comment by ascott18** [comment] 2022-11-09 02:46
We're no longer actively developing our Teams application, as the level of support we were getting from Microsoft for critical, blocking issues with the platform and SDK was insufficient.

**Comment by nwojod-MSFT** [comment] 2023-03-08 15:52
I'm closing this issue given that the OP is no longer developing for this, and we cannot confirm is this issue still persists.

**Closed by nwojod-MSFT** 2023-03-08 15:52 UTC
Labels: teams-developer-support, needs attention
