### ISSUE TITLE
Microsoft Teams tasks.submitTask does not work on IOS

### ISSUE THREAD

**Issue by helloworldsmart** [OfficeDev/microsoft-teams-library-js#794] opened 2021-12-24 06:58 UTC
I have had the same problem about Microsoft Teams tasks.submitTask does not work on IOS

https://stackoverflow.com/questions/69590787/microsoft-teams-tasks-submittask-does-not-work-on-ios

```
microsoftTeams.tasks.submitTask({ isClosed: true });
// or
microsoftTeams.tasks.submitTask(null);
```

Microsoft Teams tasks.submitTask desktop and android is ok, but not work on ios

`"@microsoft/teams-js": "^1.11.0"`

Thank you

**Comment by v-chetsh** [comment] 2021-12-24 08:09
@helloworldsmart - Could you please share any sample link which you are following?

**Comment by helloworldsmart** [comment] 2021-12-24 08:40
@v-chetsh https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/invoking-task-modules

**Comment by Meghana-MSFT** [comment] 2021-12-27 08:57
@helloworldsmart - There is a bug raised for this issue. Engineering team is looking into the issue. We will inform you if there is any update on the bug.

**Comment by v-chetsh** [comment] 2022-01-24 07:57
@helloworldsmart - Engineering team is still looking into the issue. We will inform you if there is any update on the bug.

**Comment by helloworldsmart** [comment] 2022-02-08 10:15
Please help to expedite this, it is really not good for our production UX.

**Comment by helloworldsmart** [comment] 2022-02-10 05:34
> @helloworldsmart - Engineering team is still looking into the issue. We will inform you if there is any update on the bug.

**Comment by Prasad-MSFT** [comment] 2022-02-14 12:41
@helloworldsmart - Could you please try with v1.10.0 of microsoft/teams-js ,its working fine and it enables us to close the task module (submitTask) & gives the user context as well in iOS.

**Comment by helloworldsmart** [comment] 2022-02-15 07:28
But our project app used latest v1.11.0 , can't rollback to v1.10.0 ....
Thank you ~

**Comment by Prasad-MSFT** [comment] 2022-02-16 11:33
Ok, we will check the progress with engineering team and will update accordingly

**Comment by helloworldsmart** [comment] 2022-02-17 02:57
We look forward to hearing from you soon.
Thank you ~

**Comment by johnmiroki** [comment] 2022-05-24 06:50
any updates?

**Comment by lakhveerk** [comment] 2022-05-25 17:10
Our team believes they’ve identified the issue and fixed it in 1.12.1. However, there is an issue in the cdn release of the library. We are looking into that. Meanwhile you can consume it through npm. 

The other option is that you can upgrade to the [2.0 release](https://www.npmjs.com/package/@microsoft/teams-js/v/2.0.0) of the library which is now available and has been [published to the CDN](https://res.cdn.office.net/teams-js/2.0.0/js/MicrosoftTeams.min.js). 

Please let us know if you are able to upgrade to 2.0.0, and confirm that the issue is fixed for your scenario.

**Comment by lakhveerk** [comment] 2022-05-25 20:34
I just checked back with the team, and it appears that the calling dialog.submit('testString') closes the dialog but does not call the submitHandler with the submitted 'testString' string. We apologize for the inconvenience and continue to investigate the issue.

**Comment by Wajeed-msft** [comment] 2022-09-29 10:56
The fix for this should be rolled out and available around November timeframe. I'll keep this thread updated with changes if any.

**Comment by Prasad-MSFT** [comment] 2022-11-17 10:16
@helloworldsmart - We are checking with engineering team and will let you know if there is any update.
Thanks!

**Comment by Prasad-MSFT** [comment] 2022-11-23 11:29
@helloworldsmart - This bug has been fixed and is publicly available now. We tested it in below version, and it works fine now.
![image](https://user-images.githubusercontent.com/62237649/203535899-fdfa0056-f461-4572-958c-d196a3b08c06.png)
Could you please confirm if it's working fine for you?

**Closed** 2022-11-29 19:01 UTC
Labels: bug, teams-developer-support, needs author feedback, status: no recent activity
