### ISSUE TITLE
microsoftTeams.media.scanBarCode not working for the first time

### ISSUE THREAD

**Issue by ngPunch** [OfficeDev/microsoft-teams-library-js#1383] opened 2022-10-06 16:17 UTC
First time on scan, the camera opens and reads the bar code but the details of bar code not displaying. On retry it works. Issue is reproduced consistently. Have followed the same steps as mentioned in https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/qr-barcode-scanner-capability

**Comment by sayali-MSFT** [comment] 2022-10-07 05:50
@ngPunch - Thanks for reporting your issue.
We will investigation this issue and get back to you.

**Comment by sayali-MSFT** [comment] 2022-10-07 17:35
@ngPunch - We are not able to reproduce the issue, Could you please share the error message so that we can investigate from our end?

**Comment by sayali-MSFT** [comment] 2022-10-11 13:02
@ngPunch -Did you get the chance to check?

**Comment by ngPunch** [comment] 2022-10-11 16:28
There is no error as such but when the function gets called, the decode text is undefined and after couple of seconds (sporadically) it hits the callback function, but UI does not reflect the change until i click on some html element like time picker. I am using "@microsoft/teams-js": "^1.11.0",

I even started trying the newer version  "@microsoft/teams-js": "2.3.0", In this case the camera is not even opening to scan. Can you help me with sample code for newer version?

We are using angular and i have something like this:

In ngOnInit I use the initialize
app.initialize().then(() => {});

And on scan bar code event I call:

barCode.scanBarCode({ timeOutIntervalInSec: 60 }).then((decodedText: string) => {
//Do something with the decoded text
},
(err) => {
  //Handle on error
})

**Comment by sayali-MSFT** [comment] 2022-10-12 13:44
@ngPunch - Could you please try with the below package.
package.json: "@microsoft/teams-js": "^1.9.0"

Reference sample-https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-product-inspection/nodejs

I am also trying to use the newer version package and let you know the update.

**Comment by ngPunch** [comment] 2022-10-12 16:32
I tried with version 1.9. Again i noticed same issue where in after scan the fields are not autopopulated until i click on some element on the page. I am not sure why this happens.

**Comment by sayali-MSFT** [comment] 2022-10-13 12:28
@ngPunch - We are able to repro that issue , We have raised bug for the same and concerned team is looking into it. We will inform you once we get any update. Thanks!

**Comment by ngPunch** [comment] 2022-10-19 17:04
Were you able to reproduce the issue in version 1.9 or 2.3.0?
Also when will the issue be fixed. Can you give an ETA as we need this in order to go to production

**Comment by sayali-MSFT** [comment] 2022-10-20 04:34
Tried with the both 1.9 and 2.3.0. 
Engineering team working on this issue. Currently we don’t have ETA or Update on this thread. 
We will update this thread once the bug is fixed and will look to prioritize fixing it.

**Comment by ngPunch** [comment] 2022-10-20 14:06
Please do prioritize fixing this as out production release is being impacted. Now i am unable to perform any action consistently inside the call back once camera reads the QR code. For example if i try displaying a dialog with say an error, its not loading and gets hanged. Let me know if u need any more info.

**Comment by sayali-MSFT** [comment] 2022-11-17 13:33
@ngPunch -Could you please share below information?
 What are you trying to build with barcode scanner? What's the usecase?

**Comment by sayali-MSFT** [comment] 2022-12-12 04:13
@ngPunch - We have looked into the issue again. From our end, the implementation is working fine, and the correct decoded string is being sent in the response to the API call in the first instance. We have also verified on our internal test app. There's a problem in your implementation of the app. You cannot be able to update the UI after getting the response. 
We suggest that to try rendering the UI component again after updating the UI.
Could you please debug further on your side as the response from Teams API is fine.

**Comment by sayali-MSFT** [comment] 2023-02-07 13:05
@ngPunch - Could you please confirm if your issue has resolved with with provided suggestions or still looking for any help?

**Comment by Wajeed-msft** [comment] 2023-03-06 12:22
Please feel free to re-open if you are still facing this issue.

**Closed by Wajeed-msft** 2023-03-06 12:22 UTC
Labels: bug, teams-developer-support
