### ISSUE TITLE
setFrameContext() does not update the frame context

### ISSUE THREAD

**Issue by jouhami** [OfficeDev/microsoft-teams-library-js#597] opened 2021-06-30 09:25 UTC
I have a similar need like the one discussed in this issue #204 but seems like the [`setFrameContext`](https://github.com/OfficeDev/microsoft-teams-library-js/issues/204#issuecomment-600742353) has no effect and here is how I'm doing it inside a `useEffect()` hook : 

```
useEffect(() => {
    const frameCtx = {
      contentUrl: "https://dsf154sd5.ngrok.io/app/content",
      websiteUrl: "https://dsf154sd5.ngrok.io/app/website",
    };
    console.log(
      "Setting frame context to : " + JSON.stringify(frameCtx, null, 2)
    );
    microsoftTeams.setFrameContext(frameCtx);
    microsoftTeams.appInitialization.notifySuccess();
}, []);
```

The `Go to website` and `Reload tab` actions are still pointing to the initial URLs in the manifests.

The domain  `dsf154sd5.ngrok.io`  is included in the validDomains in the manifest

`microsoftTeams.initialize()` is already invoked

**Comment by Prithvi-MSFT** [comment] 2021-08-04 13:58
Hi, we are looking into this issue and will get back to you

**Comment by HunaidHanfee-MSFT** [comment] 2021-08-06 12:34
Hello,
We have faced the same issue, confirming with internal team.
Thanks

**Comment by HunaidHanfee-MSFT** [comment] 2021-08-09 11:03
Hello @jouhami,
So, after confirming internally, we can use [_setFrameContext_ ](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams?view=msteams-client-js-latest#setFrameContext_FrameContext_)in configurable tabs and it worked fined. Please try using it in [configurable tabs](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#configurabletabs) and let us know if you face any issue.

Thanks

**Comment by jouhami** [comment] 2021-08-10 08:41
Unless I'm mistaken it is not mentioned in the documentation that it works only in configurable tabs. Is there any reason why it's not implemented the same way for personal tabs ?

**Comment by HunaidHanfee-MSFT** [comment] 2021-08-10 09:34
For the personal tab, discussion is ongoing. I will keep you updated.

**Comment by HunaidHanfee-MSFT** [comment] 2021-08-12 13:15
We have raised a bug for personal tabs.  We do not have an ETA to share but we will share updates on this thread. 
Thanks

**Comment by tiennguyen1293** [comment] 2022-03-28 11:53
I have faced the same issue.

**Comment by Prasad-MSFT** [comment] 2022-05-19 04:16
The issue is fixed now and is available publicly. Please do verify.

**Closed** 2022-05-19 04:51 UTC
Labels: teams-developer-support
