### ISSUE TITLE
How to implement the teams app sso using the @microsoft/teams-js package in react.js

### ISSUE THREAD

**Issue by Vijeshnk** [OfficeDev/microsoft-teams-library-js#1855] opened 2023-07-23 11:14 UTC
There is node example of how to implement
https://github.com/OfficeDev/msteams-tabs-sso-sample-nodejs
i want it implement in React.js , to my existing teams app build in react

i tried in the similar way but i stuck in getting the authtoken, there is the function in node to get the auth token but it shows , "The signature '(authTokenRequest?: AuthTokenRequest): void' of 'authentication.getAuthToken' is deprecated.",

for this code

```
   function getClientSideToken() {
        console.log("getClientSideToken")

        return new Promise((resolve, reject) => {

          

           authentication.getAuthToken({
           
                successCallback: (result) => {
                   
                    resolve(result);
                },
                failureCallback: function (error) {
                    reject("Error getting token: " + error);
                }
            });

        });

    }

```

**Comment by Prasad-MSFT** [comment] 2023-07-24 06:37
@Vijeshnk - Could you please let us know the SDK version you are using? Could you please try upgrading the version and check if it helps?

Ref: https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/authentication?view=msteams-client-js-latest#function-details

**Comment by AE-MS** [comment] 2023-07-24 17:36
Hi @Vijeshnk! If you are getting a message about `authentication.getAuthToken()` being deprecated, you might double-check that you are calling the [non-deprecated version of getAuthToken](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/authentication?view=msteams-client-js-latest#@microsoft-teams-js-authentication-getauthtoken) (the one that takes an [AuthTokenRequestParameters](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/authentication.authtokenrequestparameters?view=msteams-client-js-latest) object.)

Can you tell us more about what you're looking to do with the SSO token you get? Just so we can ensure that we can best help with any other questions you have.

**Comment by vijeshnk1** [comment] 2023-07-26 17:38
the issue is resolved with this code 
```
 function getClientSideToken() {
    console.log("getClientSideToken");

    return new Promise((resolve, reject) => {
      console.log("1. Get auth token from Microsoft Teams");
      authentication
        .getAuthToken({})
        .then((token) => {
          console.log("Success: " + token);
          getToken(token);
        })
        .catch((error) => {
          console.log("Error getting token: " + error);
        });
    });
  }
```

**Closed** 2023-07-28 11:17 UTC
Labels: teams-developer-support
